<a href="https://colab.research.google.com/github/Chikka-Pradhayani/ABTalks-60-Days-AI-Challenge/blob/main/Day-18.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
questions = [
    # Science
    {
        "id": 1,
        "domain": "Science",
        "question": "What is the chemical symbol for gold?",
        "ground_truth": "Au"
    },
    {
        "id": 2,
        "domain": "Science",
        "question": "What planet is known as the Red Planet?",
        "ground_truth": "Mars"
    },
    {
        "id": 3,
        "domain": "Science",
        "question": "What is the approximate speed of light in vacuum?",
        "ground_truth": "Approximately 299,792 kilometers per second."
    },
    {
        "id": 4,
        "domain": "Science",
        "question": "What gas do plants primarily absorb from the atmosphere during photosynthesis?",
        "ground_truth": "Carbon dioxide (CO2)"
    },
    {
        "id": 5,
        "domain": "Science",
        "question": "How many chromosomes are normally present in a human somatic cell?",
        "ground_truth": "46 chromosomes"
    },

    # Geography
    {
        "id": 6,
        "domain": "Geography",
        "question": "What is the capital city of Australia?",
        "ground_truth": "Canberra"
    },
    {
        "id": 7,
        "domain": "Geography",
        "question": "Which is the largest ocean on Earth?",
        "ground_truth": "Pacific Ocean"
    },
    {
        "id": 8,
        "domain": "Geography",
        "question": "What is the longest river in South America?",
        "ground_truth": "Amazon River"
    },
    {
        "id": 9,
        "domain": "Geography",
        "question": "Which country has the city of Kyoto?",
        "ground_truth": "Japan"
    },
    {
        "id": 10,
        "domain": "Geography",
        "question": "What is the capital of Canada?",
        "ground_truth": "Ottawa"
    },

    # Computer Science
    {
        "id": 11,
        "domain": "Computer Science",
        "question": "What does CPU stand for?",
        "ground_truth": "Central Processing Unit"
    },
    {
        "id": 12,
        "domain": "Computer Science",
        "question": "What data structure follows the LIFO principle?",
        "ground_truth": "Stack"
    },
    {
        "id": 13,
        "domain": "Computer Science",
        "question": "What does HTTP stand for?",
        "ground_truth": "Hypertext Transfer Protocol"
    },
    {
        "id": 14,
        "domain": "Computer Science",
        "question": "What is the time complexity of binary search on a sorted array?",
        "ground_truth": "O(log n)"
    },
    {
        "id": 15,
        "domain": "Computer Science",
        "question": "Which programming language was created by Guido van Rossum?",
        "ground_truth": "Python"
    },

    # History
    {
        "id": 16,
        "domain": "History",
        "question": "In which year did India gain independence from British rule?",
        "ground_truth": "1947"
    },
    {
        "id": 17,
        "domain": "History",
        "question": "Who was the first President of the United States?",
        "ground_truth": "George Washington"
    },
    {
        "id": 18,
        "domain": "History",
        "question": "Which ancient civilization built the pyramids at Giza?",
        "ground_truth": "Ancient Egyptians"
    },
    {
        "id": 19,
        "domain": "History",
        "question": "Who wrote the Indian national anthem 'Jana Gana Mana'?",
        "ground_truth": "Rabindranath Tagore"
    },
    {
        "id": 20,
        "domain": "History",
        "question": "In which year did World War II end?",
        "ground_truth": "1945"
    }
]

print(f"Total questions: {len(questions)}")

for q in questions:
    print(f"{q['id']}. [{q['domain']}] {q['question']}")

Total questions: 20
1. [Science] What is the chemical symbol for gold?
2. [Science] What planet is known as the Red Planet?
3. [Science] What is the approximate speed of light in vacuum?
4. [Science] What gas do plants primarily absorb from the atmosphere during photosynthesis?
5. [Science] How many chromosomes are normally present in a human somatic cell?
6. [Geography] What is the capital city of Australia?
7. [Geography] Which is the largest ocean on Earth?
8. [Geography] What is the longest river in South America?
9. [Geography] Which country has the city of Kyoto?
10. [Geography] What is the capital of Canada?
11. [Computer Science] What does CPU stand for?
12. [Computer Science] What data structure follows the LIFO principle?
13. [Computer Science] What does HTTP stand for?
14. [Computer Science] What is the time complexity of binary search on a sorted array?
15. [Computer Science] Which programming language was created by Guido van Rossum?
16. [History] In which year did India gain independence from British rule?
17. [History] Who was the first President of the United States?
18. [History] Which ancient civilization built the pyramids at Giza?
19. [History] Who wrote the Indian national anthem 'Jana Gana Mana'?
20. [History] In which year did World War II end?

In [2]:
def classify_response(response, ground_truth):
    """
    Manual classification helper.

    We will manually inspect the response and assign:
    correct
    partially_correct
    hallucinated
    """

    print("Question response:")
    print(response)

    print("\nGround truth:")
    print(ground_truth)

    print("\nChoose classification:")
    print("1. correct")
    print("2. partially_correct")
    print("3. hallucinated")

    choice = input("\nEnter 1, 2, or 3: ")

    classification_map = {
        "1": "correct",
        "2": "partially_correct",
        "3": "hallucinated"
    }

    return classification_map.get(choice, "invalid")

In [3]:
!pip install -q transformers sentencepiece torch

In [4]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_name = "google/flan-t5-base"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

print("Model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  990MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/282 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Model loaded successfully!

In [5]:
def generate_no_context(question):
    prompt = f"Answer this factual question briefly and directly:\n{question}"

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True
    )

    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=False
    )

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    return response.strip()

In [6]:
test_question = questions[0]["question"]
response = generate_no_context(test_question)
print("Question:", test_question)
print("Response:", response)

Question: What is the chemical symbol for gold?
Response: g

In [7]:
results = {}

for q in questions:
    response = generate_no_context(q["question"])

    results[q["id"]] = {
        "id": q["id"],
        "domain": q["domain"],
        "question": q["question"],
        "ground_truth": q["ground_truth"],
        "no_context_response": response
    }

print("Generated responses for", len(results), "questions.")

Generated responses for 20 questions.

In [8]:
for result in results.values():
    print("=" * 70)
    print("ID:", result["id"])
    print("Domain:", result["domain"])
    print("Question:", result["question"])
    print("Ground Truth:", result["ground_truth"])
    print("Model Response:", result["no_context_response"])

======================================================================
ID: 1
Domain: Science
Question: What is the chemical symbol for gold?
Ground Truth: Au
Model Response: g
======================================================================
ID: 2
Domain: Science
Question: What planet is known as the Red Planet?
Ground Truth: Mars
Model Response: uranus
======================================================================
ID: 3
Domain: Science
Question: What is the approximate speed of light in vacuum?
Ground Truth: Approximately 299,792 kilometers per second.
Model Response: a few hundred million cycles
======================================================================
ID: 4
Domain: Science
Question: What gas do plants primarily absorb from the atmosphere during photosynthesis?
Ground Truth: Carbon dioxide (CO2)
Model Response: carbon dioxide
======================================================================
ID: 5
Domain: Science
Question: How many chromosomes are normally present in a human somatic cell?
Ground Truth: 46 chromosomes
Model Response: one
======================================================================
ID: 6
Domain: Geography
Question: What is the capital city of Australia?
Ground Truth: Canberra
Model Response: Sydney
======================================================================
ID: 7
Domain: Geography
Question: Which is the largest ocean on Earth?
Ground Truth: Pacific Ocean
Model Response: the Atlantic Ocean
======================================================================
ID: 8
Domain: Geography
Question: What is the longest river in South America?
Ground Truth: Amazon River
Model Response: Rio Grande
======================================================================
ID: 9
Domain: Geography
Question: Which country has the city of Kyoto?
Ground Truth: Japan
Model Response: Japan
======================================================================
ID: 10
Domain: Geography
Question: What is the capital of Canada?
Ground Truth: Ottawa
Model Response: Ottawa
======================================================================
ID: 11
Domain: Computer Science
Question: What does CPU stand for?
Ground Truth: Central Processing Unit
Model Response: CPU
======================================================================
ID: 12
Domain: Computer Science
Question: What data structure follows the LIFO principle?
Ground Truth: Stack
Model Response: a logical data structure
======================================================================
ID: 13
Domain: Computer Science
Question: What does HTTP stand for?
Ground Truth: Hypertext Transfer Protocol
Model Response: HTTP
======================================================================
ID: 14
Domain: Computer Science
Question: What is the time complexity of binary search on a sorted array?
Ground Truth: O(log n)
Model Response: a single-bit search
======================================================================
ID: 15
Domain: Computer Science
Question: Which programming language was created by Guido van Rossum?
Ground Truth: Python
Model Response: .NET
======================================================================
ID: 16
Domain: History
Question: In which year did India gain independence from British rule?
Ground Truth: 1947
Model Response: 1819
======================================================================
ID: 17
Domain: History
Question: Who was the first President of the United States?
Ground Truth: George Washington
Model Response: John Adams
======================================================================
ID: 18
Domain: History
Question: Which ancient civilization built the pyramids at Giza?
Ground Truth: Ancient Egyptians
Model Response: Egyptians
======================================================================
ID: 19
Domain: History
Question: Who wrote the Indian national anthem 'Jana Gana Mana'?
Ground Truth: Rabindranath Tagore
Model Response: samuel sahib
======================================================================
ID: 20
Domain: History
Question: In which year did World War II end?
Ground Truth: 1945
Model Response: 1945

In [9]:
import json

with open("no_context_results.json", "w", encoding="utf-8") as f:
    json.dump(
        results,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Saved to no_context_results.json")

Saved to no_context_results.json

In [10]:
for result in results.values():
    result["classification"] = None
    result["hallucination_type"] = None

print("Evaluation fields added.")

Evaluation fields added.

In [11]:
def evaluate_response(result):
    print("\n" + "=" * 80)
    print(f"Question {result['id']} [{result['domain']}]")
    print("-" * 80)

    print("QUESTION:")
    print(result["question"])

    print("\nGROUND TRUTH:")
    print(result["ground_truth"])

    print("\nMODEL RESPONSE:")
    print(result["no_context_response"])

    print("\nCLASSIFICATION:")
    print("1 → correct")
    print("2 → partially_correct")
    print("3 → hallucinated")

    choice = input("Enter choice: ").strip()

    classification_map = {
        "1": "correct",
        "2": "partially_correct",
        "3": "hallucinated"
    }

    classification = classification_map.get(choice)

    if classification is None:
        print("Invalid choice. Please enter 1, 2, or 3.")
        return evaluate_response(result)

    result["classification"] = classification

    # Hallucination category
    if classification == "hallucinated":
        print("\nHALLUCINATION TYPE:")
        print("1 → fabricated_specific_fact")
        print("2 → outdated_information")
        print("3 → confident_wrong_answer")
        print("4 → plausible_unverifiable_claim")

        h_choice = input("Enter choice: ").strip()

        hallucination_map = {
            "1": "fabricated_specific_fact",
            "2": "outdated_information",
            "3": "confident_wrong_answer",
            "4": "plausible_unverifiable_claim"
        }

        result["hallucination_type"] = hallucination_map.get(
            h_choice,
            "unknown"
        )

    return result

In [12]:
with open("evaluated_results.json", "w", encoding="utf-8") as f:
    json.dump(
        results,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Evaluation saved successfully.")

Evaluation saved successfully.

In [13]:
from collections import Counter

classification_counts = Counter(
    result["classification"]
    for result in results.values()
)

print("Classification Results")
print("-" * 40)

print("Correct:", classification_counts["correct"])
print("Partially Correct:", classification_counts["partially_correct"])
print("Hallucinated:", classification_counts["hallucinated"])

Classification Results
----------------------------------------
Correct: 0
Partially Correct: 0
Hallucinated: 0

In [14]:
total_questions = len(results)

hallucinated_count = classification_counts["hallucinated"]

hallucination_rate = (
    hallucinated_count / total_questions
) * 100

print("\nNo-Context Hallucination Rate:")
print(f"{hallucination_rate:.2f}%")

No-Context Hallucination Rate:
0.00%

In [15]:
hallucination_types = Counter(
    result["hallucination_type"]
    for result in results.values()
    if result["classification"] == "hallucinated"
)

print("\nHallucination Types")
print("-" * 40)

for h_type, count in hallucination_types.items():
    print(f"{h_type}: {count}")

Hallucination Types
----------------------------------------

In [16]:
failure_table = []

for result in results.values():
    if result["classification"] == "hallucinated":
        failure_table.append({
            "id": result["id"],
            "domain": result["domain"],
            "question": result["question"],
            "model_response": result["no_context_response"],
            "ground_truth": result["ground_truth"],
            "hallucination_type": result["hallucination_type"]
        })

for row in failure_table:
    print("=" * 80)
    for key, value in row.items():
        print(f"{key}: {value}")

In [18]:
for result in results.values():
    if result["classification"] is None:
        print("Missing classification:")
        print("ID:", result["id"])
        print("Question:", result["question"])
        print("Response:", result["no_context_response"])

Missing classification:
ID: 1
Question: What is the chemical symbol for gold?
Response: g
Missing classification:
ID: 2
Question: What planet is known as the Red Planet?
Response: uranus
Missing classification:
ID: 3
Question: What is the approximate speed of light in vacuum?
Response: a few hundred million cycles
Missing classification:
ID: 4
Question: What gas do plants primarily absorb from the atmosphere during photosynthesis?
Response: carbon dioxide
Missing classification:
ID: 5
Question: How many chromosomes are normally present in a human somatic cell?
Response: one
Missing classification:
ID: 6
Question: What is the capital city of Australia?
Response: Sydney
Missing classification:
ID: 7
Question: Which is the largest ocean on Earth?
Response: the Atlantic Ocean
Missing classification:
ID: 8
Question: What is the longest river in South America?
Response: Rio Grande
Missing classification:
ID: 9
Question: Which country has the city of Kyoto?
Response: Japan
Missing classification:
ID: 10
Question: What is the capital of Canada?
Response: Ottawa
Missing classification:
ID: 11
Question: What does CPU stand for?
Response: CPU
Missing classification:
ID: 12
Question: What data structure follows the LIFO principle?
Response: a logical data structure
Missing classification:
ID: 13
Question: What does HTTP stand for?
Response: HTTP
Missing classification:
ID: 14
Question: What is the time complexity of binary search on a sorted array?
Response: a single-bit search
Missing classification:
ID: 15
Question: Which programming language was created by Guido van Rossum?
Response: .NET
Missing classification:
ID: 16
Question: In which year did India gain independence from British rule?
Response: 1819
Missing classification:
ID: 17
Question: Who was the first President of the United States?
Response: John Adams
Missing classification:
ID: 18
Question: Which ancient civilization built the pyramids at Giza?
Response: Egyptians
Missing classification:
ID: 19
Question: Who wrote the Indian national anthem 'Jana Gana Mana'?
Response: samuel sahib
Missing classification:
ID: 20
Question: In which year did World War II end?
Response: 1945

In [19]:
domain_stats = {}

for result in results.values():

    # Skip responses that haven't been evaluated
    if result["classification"] is None:
        continue

    domain = result["domain"]
    classification = result["classification"]

    if domain not in domain_stats:
        domain_stats[domain] = {
            "total": 0,
            "correct": 0,
            "partially_correct": 0,
            "hallucinated": 0
        }

    domain_stats[domain]["total"] += 1
    domain_stats[domain][classification] += 1


for domain, stats in domain_stats.items():

    rate = (
        stats["hallucinated"] /
        stats["total"]
    ) * 100

    print(f"\n{domain}")
    print("-" * 40)
    print("Total:", stats["total"])
    print("Correct:", stats["correct"])
    print("Partially Correct:", stats["partially_correct"])
    print("Hallucinated:", stats["hallucinated"])
    print(f"Hallucination Rate: {rate:.2f}%")

In [20]:
summary = {
    "total_questions": total_questions,
    "correct": classification_counts["correct"],
    "partially_correct": classification_counts["partially_correct"],
    "hallucinated": classification_counts["hallucinated"],
    "hallucination_rate": hallucination_rate,
    "hallucination_types": dict(hallucination_types),
    "domain_statistics": domain_stats
}

with open("no_context_summary.json", "w", encoding="utf-8") as f:
    json.dump(
        summary,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Summary saved to no_context_summary.json")

Summary saved to no_context_summary.json

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
documents = [
    "Gold has the chemical symbol Au.",
    "Mars is known as the Red Planet.",
    "The speed of light in vacuum is approximately 299,792 kilometers per second.",
    "Plants primarily absorb carbon dioxide (CO2) from the atmosphere during photosynthesis.",
    "A normal human somatic cell contains 46 chromosomes.",

    "Canberra is the capital city of Australia.",
    "The Pacific Ocean is the largest ocean on Earth.",
    "The Amazon River is the longest river in South America.",
    "Kyoto is a city in Japan.",
    "Ottawa is the capital of Canada.",

    "CPU stands for Central Processing Unit.",
    "A stack is a data structure that follows the LIFO principle.",
    "HTTP stands for Hypertext Transfer Protocol.",
    "Binary search on a sorted array has a time complexity of O(log n).",
    "Python was created by Guido van Rossum.",

    "India gained independence from British rule in 1947.",
    "George Washington was the first President of the United States.",
    "The pyramids at Giza were built by ancient Egyptians.",
    "Jana Gana Mana was written by Rabindranath Tagore.",
    "World War II ended in 1945."
]

print("Number of documents:", len(documents))

Number of documents: 20

In [23]:
vectorizer = TfidfVectorizer()

document_vectors = vectorizer.fit_transform(documents)

print("Vector database created successfully.")

Vector database created successfully.

In [24]:
def retrieve_context(query, top_k=2):
    query_vector = vectorizer.transform([query])

    similarities = cosine_similarity(
        query_vector,
        document_vectors
    )[0]

    top_indices = similarities.argsort()[-top_k:][::-1]

    retrieved = []

    for index in top_indices:
        retrieved.append({
            "document": documents[index],
            "score": float(similarities[index])
        })

    return retrieved

In [25]:
query = questions[0]["question"]

retrieved = retrieve_context(query)

print("QUESTION:")
print(query)

print("\nRETRIEVED CONTEXT:")

for item in retrieved:
    print(f"\nScore: {item['score']:.4f}")
    print(item["document"])

QUESTION:
What is the chemical symbol for gold?

RETRIEVED CONTEXT:

Score: 0.6950
Gold has the chemical symbol Au.

Score: 0.1584
HTTP stands for Hypertext Transfer Protocol.

In [26]:
def generate_rag_answer(question, retrieved_context):

    context = "\n".join(
        item["document"]
        for item in retrieved_context
    )

    prompt = f"""
Answer the question using only the provided context.

Context:
{context}

Question:
{question}

Answer:
"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True
    )

    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=False
    )

    response = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    return response.strip()

In [27]:
question = questions[0]["question"]

retrieved = retrieve_context(question)

response = generate_rag_answer(
    question,
    retrieved
)

print("Question:")
print(question)

print("\nRetrieved Context:")
for item in retrieved:
    print("-", item["document"])

print("\nRAG Response:")
print(response)

Question:
What is the chemical symbol for gold?

Retrieved Context:
- Gold has the chemical symbol Au.
- HTTP stands for Hypertext Transfer Protocol.

RAG Response:
Au

In [28]:
rag_results = {}

for q in questions:

    retrieved = retrieve_context(
        q["question"],
        top_k=2
    )

    response = generate_rag_answer(
        q["question"],
        retrieved
    )

    rag_results[q["id"]] = {
        "id": q["id"],
        "domain": q["domain"],
        "question": q["question"],
        "ground_truth": q["ground_truth"],
        "retrieved_context": [
            item["document"]
            for item in retrieved
        ],
        "retrieval_scores": [
            item["score"]
            for item in retrieved
        ],
        "rag_response": response,
        "classification": None,
        "hallucination_type": None
    }

print("Generated RAG responses:", len(rag_results))

Generated RAG responses: 20

In [29]:
for result in rag_results.values():

    print("=" * 80)
    print("ID:", result["id"])
    print("Domain:", result["domain"])
    print("Question:", result["question"])

    print("\nRetrieved Context:")
    for context in result["retrieved_context"]:
        print("-", context)

    print("\nRAG Response:")
    print(result["rag_response"])

================================================================================
ID: 1
Domain: Science
Question: What is the chemical symbol for gold?

Retrieved Context:
- Gold has the chemical symbol Au.
- HTTP stands for Hypertext Transfer Protocol.

RAG Response:
Au
================================================================================
ID: 2
Domain: Science
Question: What planet is known as the Red Planet?

Retrieved Context:
- Mars is known as the Red Planet.
- Ottawa is the capital of Canada.

RAG Response:
Mars
================================================================================
ID: 3
Domain: Science
Question: What is the approximate speed of light in vacuum?

Retrieved Context:
- The speed of light in vacuum is approximately 299,792 kilometers per second.
- Ottawa is the capital of Canada.

RAG Response:
299,792 kilometers per second
================================================================================
ID: 4
Domain: Science
Question: What gas do plants primarily absorb from the atmosphere during photosynthesis?

Retrieved Context:
- Plants primarily absorb carbon dioxide (CO2) from the atmosphere during photosynthesis.
- India gained independence from British rule in 1947.

RAG Response:
carbon dioxide
================================================================================
ID: 5
Domain: Science
Question: How many chromosomes are normally present in a human somatic cell?

Retrieved Context:
- A normal human somatic cell contains 46 chromosomes.
- Kyoto is a city in Japan.

RAG Response:
46
================================================================================
ID: 6
Domain: Geography
Question: What is the capital city of Australia?

Retrieved Context:
- Canberra is the capital city of Australia.
- Ottawa is the capital of Canada.

RAG Response:
Canberra
================================================================================
ID: 7
Domain: Geography
Question: Which is the largest ocean on Earth?

Retrieved Context:
- The Pacific Ocean is the largest ocean on Earth.
- Ottawa is the capital of Canada.

RAG Response:
Pacific Ocean
================================================================================
ID: 8
Domain: Geography
Question: What is the longest river in South America?

Retrieved Context:
- The Amazon River is the longest river in South America.
- Kyoto is a city in Japan.

RAG Response:
Amazon River
================================================================================
ID: 9
Domain: Geography
Question: Which country has the city of Kyoto?

Retrieved Context:
- Kyoto is a city in Japan.
- Canberra is the capital city of Australia.

RAG Response:
Japan
================================================================================
ID: 10
Domain: Geography
Question: What is the capital of Canada?

Retrieved Context:
- Ottawa is the capital of Canada.
- Canberra is the capital city of Australia.

RAG Response:
Ottawa
================================================================================
ID: 11
Domain: Computer Science
Question: What does CPU stand for?

Retrieved Context:
- CPU stands for Central Processing Unit.
- HTTP stands for Hypertext Transfer Protocol.

RAG Response:
Central Processing Unit
================================================================================
ID: 12
Domain: Computer Science
Question: What data structure follows the LIFO principle?

Retrieved Context:
- A stack is a data structure that follows the LIFO principle.
- George Washington was the first President of the United States.

RAG Response:
A stack
================================================================================
ID: 13
Domain: Computer Science
Question: What does HTTP stand for?

Retrieved Context:
- HTTP stands for Hypertext Transfer Protocol.
- CPU stands for Central Processing Unit.

RAG Response:
Hypertext Transfer Protocol
================================================================================
ID: 14
Domain: Computer Science
Question: What is the time complexity of binary search on a sorted array?

Retrieved Context:
- Binary search on a sorted array has a time complexity of O(log n).
- The Pacific Ocean is the largest ocean on Earth.

RAG Response:
O(log n)
================================================================================
ID: 15
Domain: Computer Science
Question: Which programming language was created by Guido van Rossum?

Retrieved Context:
- Python was created by Guido van Rossum.
- Jana Gana Mana was written by Rabindranath Tagore.

RAG Response:
Python
================================================================================
ID: 16
Domain: History
Question: In which year did India gain independence from British rule?

Retrieved Context:
- India gained independence from British rule in 1947.
- Plants primarily absorb carbon dioxide (CO2) from the atmosphere during photosynthesis.

RAG Response:
1947
================================================================================
ID: 17
Domain: History
Question: Who was the first President of the United States?

Retrieved Context:
- George Washington was the first President of the United States.
- Ottawa is the capital of Canada.

RAG Response:
George Washington
================================================================================
ID: 18
Domain: History
Question: Which ancient civilization built the pyramids at Giza?

Retrieved Context:
- The pyramids at Giza were built by ancient Egyptians.
- George Washington was the first President of the United States.

RAG Response:
Egyptians
================================================================================
ID: 19
Domain: History
Question: Who wrote the Indian national anthem 'Jana Gana Mana'?

Retrieved Context:
- Jana Gana Mana was written by Rabindranath Tagore.
- George Washington was the first President of the United States.

RAG Response:
Rabindranath Tagore
================================================================================
ID: 20
Domain: History
Question: In which year did World War II end?

Retrieved Context:
- World War II ended in 1945.
- Kyoto is a city in Japan.

RAG Response:
1945

In [30]:
with open(
    "rag_results.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        rag_results,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Saved to rag_results.json")

Saved to rag_results.json

In [31]:
for result in rag_results.values():
    result["classification"] = None
    result["hallucination_type"] = None

print("RAG evaluation fields added.")

RAG evaluation fields added.

In [32]:
def evaluate_rag_response(result):

    print("\n" + "=" * 80)
    print(f"Question {result['id']} [{result['domain']}]")
    print("-" * 80)

    print("QUESTION:")
    print(result["question"])

    print("\nGROUND TRUTH:")
    print(result["ground_truth"])

    print("\nRETRIEVED CONTEXT:")

    for context in result["retrieved_context"]:
        print("-", context)

    print("\nRAG RESPONSE:")
    print(result["rag_response"])

    print("\nCLASSIFICATION:")
    print("1 → correct")
    print("2 → partially_correct")
    print("3 → hallucinated")

    choice = input("Enter choice: ").strip()

    classification_map = {
        "1": "correct",
        "2": "partially_correct",
        "3": "hallucinated"
    }

    classification = classification_map.get(choice)

    if classification is None:
        print("Invalid choice.")
        return evaluate_rag_response(result)

    result["classification"] = classification

    if classification == "hallucinated":

        print("\nHALLUCINATION TYPE:")
        print("1 → fabricated_specific_fact")
        print("2 → outdated_information")
        print("3 → confident_wrong_answer")
        print("4 → plausible_unverifiable_claim")

        h_choice = input("Enter choice: ").strip()

        hallucination_map = {
            "1": "fabricated_specific_fact",
            "2": "outdated_information",
            "3": "confident_wrong_answer",
            "4": "plausible_unverifiable_claim"
        }

        result["hallucination_type"] = hallucination_map.get(
            h_choice,
            "unknown"
        )

    return result

In [33]:
111
1
for result in rag_results.values():
    evaluate_rag_response(result)

================================================================================
Question 1 [Science]
--------------------------------------------------------------------------------
QUESTION:
What is the chemical symbol for gold?

GROUND TRUTH:
Au

RETRIEVED CONTEXT:
- Gold has the chemical symbol Au.
- HTTP stands for Hypertext Transfer Protocol.

RAG RESPONSE:
Au

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 3

HALLUCINATION TYPE:
1 → fabricated_specific_fact
2 → outdated_information
3 → confident_wrong_answer
4 → plausible_unverifiable_claim
Enter choice: 2

================================================================================
Question 2 [Science]
--------------------------------------------------------------------------------
QUESTION:
What planet is known as the Red Planet?

GROUND TRUTH:
Mars

RETRIEVED CONTEXT:
- Mars is known as the Red Planet.
- Ottawa is the capital of Canada.

RAG RESPONSE:
Mars

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 3 [Science]
--------------------------------------------------------------------------------
QUESTION:
What is the approximate speed of light in vacuum?

GROUND TRUTH:
Approximately 299,792 kilometers per second.

RETRIEVED CONTEXT:
- The speed of light in vacuum is approximately 299,792 kilometers per second.
- Ottawa is the capital of Canada.

RAG RESPONSE:
299,792 kilometers per second

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 4 [Science]
--------------------------------------------------------------------------------
QUESTION:
What gas do plants primarily absorb from the atmosphere during photosynthesis?

GROUND TRUTH:
Carbon dioxide (CO2)

RETRIEVED CONTEXT:
- Plants primarily absorb carbon dioxide (CO2) from the atmosphere during photosynthesis.
- India gained independence from British rule in 1947.

RAG RESPONSE:
carbon dioxide

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 5 [Science]
--------------------------------------------------------------------------------
QUESTION:
How many chromosomes are normally present in a human somatic cell?

GROUND TRUTH:
46 chromosomes

RETRIEVED CONTEXT:
- A normal human somatic cell contains 46 chromosomes.
- Kyoto is a city in Japan.

RAG RESPONSE:
46

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 6 [Geography]
--------------------------------------------------------------------------------
QUESTION:
What is the capital city of Australia?

GROUND TRUTH:
Canberra

RETRIEVED CONTEXT:
- Canberra is the capital city of Australia.
- Ottawa is the capital of Canada.

RAG RESPONSE:
Canberra

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 7 [Geography]
--------------------------------------------------------------------------------
QUESTION:
Which is the largest ocean on Earth?

GROUND TRUTH:
Pacific Ocean

RETRIEVED CONTEXT:
- The Pacific Ocean is the largest ocean on Earth.
- Ottawa is the capital of Canada.

RAG RESPONSE:
Pacific Ocean

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 8 [Geography]
--------------------------------------------------------------------------------
QUESTION:
What is the longest river in South America?

GROUND TRUTH:
Amazon River

RETRIEVED CONTEXT:
- The Amazon River is the longest river in South America.
- Kyoto is a city in Japan.

RAG RESPONSE:
Amazon River

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 9 [Geography]
--------------------------------------------------------------------------------
QUESTION:
Which country has the city of Kyoto?

GROUND TRUTH:
Japan

RETRIEVED CONTEXT:
- Kyoto is a city in Japan.
- Canberra is the capital city of Australia.

RAG RESPONSE:
Japan

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 10 [Geography]
--------------------------------------------------------------------------------
QUESTION:
What is the capital of Canada?

GROUND TRUTH:
Ottawa

RETRIEVED CONTEXT:
- Ottawa is the capital of Canada.
- Canberra is the capital city of Australia.

RAG RESPONSE:
Ottawa

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 11 [Computer Science]
--------------------------------------------------------------------------------
QUESTION:
What does CPU stand for?

GROUND TRUTH:
Central Processing Unit

RETRIEVED CONTEXT:
- CPU stands for Central Processing Unit.
- HTTP stands for Hypertext Transfer Protocol.

RAG RESPONSE:
Central Processing Unit

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 12 [Computer Science]
--------------------------------------------------------------------------------
QUESTION:
What data structure follows the LIFO principle?

GROUND TRUTH:
Stack

RETRIEVED CONTEXT:
- A stack is a data structure that follows the LIFO principle.
- George Washington was the first President of the United States.

RAG RESPONSE:
A stack

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 13 [Computer Science]
--------------------------------------------------------------------------------
QUESTION:
What does HTTP stand for?

GROUND TRUTH:
Hypertext Transfer Protocol

RETRIEVED CONTEXT:
- HTTP stands for Hypertext Transfer Protocol.
- CPU stands for Central Processing Unit.

RAG RESPONSE:
Hypertext Transfer Protocol

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 14 [Computer Science]
--------------------------------------------------------------------------------
QUESTION:
What is the time complexity of binary search on a sorted array?

GROUND TRUTH:
O(log n)

RETRIEVED CONTEXT:
- Binary search on a sorted array has a time complexity of O(log n).
- The Pacific Ocean is the largest ocean on Earth.

RAG RESPONSE:
O(log n)

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 15 [Computer Science]
--------------------------------------------------------------------------------
QUESTION:
Which programming language was created by Guido van Rossum?

GROUND TRUTH:
Python

RETRIEVED CONTEXT:
- Python was created by Guido van Rossum.
- Jana Gana Mana was written by Rabindranath Tagore.

RAG RESPONSE:
Python

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 16 [History]
--------------------------------------------------------------------------------
QUESTION:
In which year did India gain independence from British rule?

GROUND TRUTH:
1947

RETRIEVED CONTEXT:
- India gained independence from British rule in 1947.
- Plants primarily absorb carbon dioxide (CO2) from the atmosphere during photosynthesis.

RAG RESPONSE:
1947

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 17 [History]
--------------------------------------------------------------------------------
QUESTION:
Who was the first President of the United States?

GROUND TRUTH:
George Washington

RETRIEVED CONTEXT:
- George Washington was the first President of the United States.
- Ottawa is the capital of Canada.

RAG RESPONSE:
George Washington

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 18 [History]
--------------------------------------------------------------------------------
QUESTION:
Which ancient civilization built the pyramids at Giza?

GROUND TRUTH:
Ancient Egyptians

RETRIEVED CONTEXT:
- The pyramids at Giza were built by ancient Egyptians.
- George Washington was the first President of the United States.

RAG RESPONSE:
Egyptians

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1
Enter choice:

================================================================================
Question 19 [History]
--------------------------------------------------------------------------------
QUESTION:
Who wrote the Indian national anthem 'Jana Gana Mana'?

GROUND TRUTH:
Rabindranath Tagore

RETRIEVED CONTEXT:
- Jana Gana Mana was written by Rabindranath Tagore.
- George Washington was the first President of the United States.

RAG RESPONSE:
Rabindranath Tagore

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice:
Invalid choice.

================================================================================
Question 19 [History]
--------------------------------------------------------------------------------
QUESTION:
Who wrote the Indian national anthem 'Jana Gana Mana'?

GROUND TRUTH:
Rabindranath Tagore

RETRIEVED CONTEXT:
- Jana Gana Mana was written by Rabindranath Tagore.
- George Washington was the first President of the United States.

RAG RESPONSE:
Rabindranath Tagore

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Invalid choice.

================================================================================
Question 19 [History]
--------------------------------------------------------------------------------
QUESTION:
Who wrote the Indian national anthem 'Jana Gana Mana'?

GROUND TRUTH:
Rabindranath Tagore

RETRIEVED CONTEXT:
- Jana Gana Mana was written by Rabindranath Tagore.
- George Washington was the first President of the United States.

RAG RESPONSE:
Rabindranath Tagore

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

================================================================================
Question 20 [History]
--------------------------------------------------------------------------------
QUESTION:
In which year did World War II end?

GROUND TRUTH:
1945

RETRIEVED CONTEXT:
- World War II ended in 1945.
- Kyoto is a city in Japan.

RAG RESPONSE:
1945

CLASSIFICATION:
1 → correct
2 → partially_correct
3 → hallucinated
Enter choice: 1

In [34]:
missing = [
    result["id"]
    for result in rag_results.values()
    if result["classification"] is None
]

print("Unclassified responses:", len(missing))

if missing:
    print("Missing IDs:", missing)
else:
    print("All 20 RAG responses evaluated!")

Unclassified responses: 0
All 20 RAG responses evaluated!

In [35]:
from collections import Counter

rag_classification_counts = Counter(
    result["classification"]
    for result in rag_results.values()
)

print("RAG Classification Results")
print("-" * 40)

print("Correct:",
      rag_classification_counts["correct"])

print("Partially Correct:",
      rag_classification_counts["partially_correct"])

print("Hallucinated:",
      rag_classification_counts["hallucinated"])

RAG Classification Results
----------------------------------------
Correct: 19
Partially Correct: 0
Hallucinated: 1

In [36]:
rag_total = len(rag_results)

rag_hallucinated = rag_classification_counts["hallucinated"]

rag_hallucination_rate = (
    rag_hallucinated / rag_total
) * 100

print(
    f"RAG Hallucination Rate: "
    f"{rag_hallucination_rate:.2f}%"
)

RAG Hallucination Rate: 5.00%

In [37]:
no_context_rate = hallucination_rate
rag_rate = rag_hallucination_rate

print("=" * 50)
print("HALLUCINATION RATE COMPARISON")
print("=" * 50)

print(f"No Context : {no_context_rate:.2f}%")
print(f"RAG        : {rag_rate:.2f}%")

if no_context_rate > rag_rate:
    reduction = no_context_rate - rag_rate

    print(
        f"\nRAG reduced hallucination rate "
        f"by {reduction:.2f} percentage points."
    )

elif rag_rate > no_context_rate:
    increase = rag_rate - no_context_rate

    print(
        f"\nRAG increased hallucination rate "
        f"by {increase:.2f} percentage points."
    )

else:
    print("\nBoth conditions produced the same hallucination rate.")

==================================================
HALLUCINATION RATE COMPARISON
==================================================
No Context : 0.00%
RAG        : 5.00%

RAG increased hallucination rate by 5.00 percentage points.

In [38]:
with open(
    "evaluated_rag_results.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        rag_results,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Saved evaluated RAG results.")

Saved evaluated RAG results.

In [39]:
!pip install -q spacy

In [40]:
!python -m spacy download en_core_web_sm -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 55.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [41]:
import spacy

nlp = spacy.load("en_core_web_sm")

In [42]:
import re

def unsupported_claim_check(response, context):

    # Extract numbers
    numbers = re.findall(
        r'\b\d+(?:[.,]\d+)?(?:\s*(?:km|kg|%|years?|million|billion))?\b',
        response,
        flags=re.IGNORECASE
    )

    # Extract dates / years
    dates = re.findall(
        r'\b(?:1[0-9]{3}|20[0-9]{2})\b',
        response
    )

    unsupported_numbers = []

    context_lower = context.lower()

    for item in numbers + dates:
        if item.lower() not in context_lower:
            unsupported_numbers.append(item)

    # Named entities
    doc = nlp(response)

    entities = [
        ent.text
        for ent in doc.ents
        if ent.label_ in [
            "PERSON",
            "ORG",
            "GPE",
            "LOC",
            "EVENT",
            "FAC"
        ]
    ]

    unsupported_entities = []

    for entity in entities:
        if entity.lower() not in context_lower:
            unsupported_entities.append(entity)

    flagged = bool(
        unsupported_numbers or
        unsupported_entities
    )

    return {
        "flagged": flagged,
        "unsupported_numbers": unsupported_numbers,
        "unsupported_entities": unsupported_entities
    }

In [44]:
response = "The capital of Australia is Sydney and it was established in 1788."

context = "Canberra is the capital city of Australia."

result = unsupported_claim_check(
    response,
    context
)

print(result)

{'flagged': True, 'unsupported_numbers': ['1788', '1788'], 'unsupported_entities': ['Sydney']}

In [43]:
def tokenize(text):
    return set(
        re.findall(
            r'\b[a-zA-Z0-9]+\b',
            text.lower()
        )
    )

In [45]:
def jaccard_similarity(response, context):

    response_tokens = tokenize(response)
    context_tokens = tokenize(context)

    if not response_tokens or not context_tokens:
        return 0.0

    intersection = response_tokens & context_tokens
    union = response_tokens | context_tokens

    return len(intersection) / len(union)

In [46]:
def retrieval_overlap_check(response, context, threshold=0.15):

    score = jaccard_similarity(
        response,
        context
    )

    return {
        "jaccard_score": score,
        "threshold": threshold,
        "flagged": score < threshold
    }

In [47]:
response = "Canberra is the capital of Australia."

context = "Canberra is the capital city of Australia."

print(
    retrieval_overlap_check(
        response,
        context
    )
)

{'jaccard_score': 0.8571428571428571, 'threshold': 0.15, 'flagged': False}

In [48]:
def contradiction_check(response, context):

    prompt = f"""
Determine whether the answer contradicts the provided context.

Context:
{context}

Answer:
{response}

Does the answer contradict the context?
Answer only YES or NO.
"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True
    )

    outputs = model.generate(
        **inputs,
        max_new_tokens=5,
        do_sample=False
    )

    result = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    ).strip().lower()

    flagged = result.startswith("yes")

    return {
        "model_judgement": result,
        "flagged": flagged
    }

In [49]:
context = "Canberra is the capital city of Australia."

response = "Sydney is the capital of Australia."

print(
    contradiction_check(
        response,
        context
    )
)

{'model_judgement': 'no', 'flagged': False}

In [50]:
def citation_absence_check(response):

    citation_patterns = [
        r'\[[0-9]+\]',
        r'\(source',
        r'\(reference',
        r'\baccording to\b',
        r'\bsource:',
        r'\breference:'
    ]

    has_citation = any(
        re.search(
            pattern,
            response,
            flags=re.IGNORECASE
        )
        for pattern in citation_patterns
    )

    # Any non-empty factual answer without citation
    factual_assertion = len(
        tokenize(response)
    ) > 2

    flagged = factual_assertion and not has_citation

    return {
        "has_citation": has_citation,
        "flagged": flagged
    }

In [51]:
response = "Canberra is the capital of Australia."

print(
    citation_absence_check(response)
)

{'has_citation': False, 'flagged': True}

In [52]:
def calculate_confidence(signals):

    total_signals = 4

    flagged_signals = sum(
        signal["flagged"]
        for signal in signals.values()
    )

    confidence = (
        1 - flagged_signals / total_signals
    ) * 100

    return confidence

In [53]:
def detect_hallucination(result):

    response = result["rag_response"]

    context = "\n".join(
        result["retrieved_context"]
    )

    signal_1 = unsupported_claim_check(
        response,
        context
    )

    signal_2 = retrieval_overlap_check(
        response,
        context
    )

    signal_3 = contradiction_check(
        response,
        context
    )

    signal_4 = citation_absence_check(
        response
    )

    signals = {
        "unsupported_claim": signal_1,
        "retrieval_overlap": signal_2,
        "contradiction": signal_3,
        "citation_absence": signal_4
    }

    confidence = calculate_confidence(
        signals
    )

    return {
        "signals": signals,
        "final_confidence_score": confidence
    }

In [54]:
detection_results = {}

for result in rag_results.values():

    detection = detect_hallucination(result)

    detection_results[result["id"]] = {
        "id": result["id"],
        "question": result["question"],
        "rag_response": result["rag_response"],
        "detection": detection
    }

print("Detection completed for", len(detection_results), "responses.")

Detection completed for 20 responses.

In [55]:
detection_results = {}

for result in rag_results.values():

    detection = detect_hallucination(result)

    detection_results[result["id"]] = {
        "id": result["id"],
        "question": result["question"],
        "rag_response": result["rag_response"],
        "detection": detection
    }

print("Detection completed for", len(detection_results), "responses.")

Detection completed for 20 responses.

In [56]:
for result in detection_results.values():

    detection = result["detection"]

    print("\n" + "=" * 80)
    print(f"Question {result['id']}")
    print("-" * 80)

    print("Question:")
    print(result["question"])

    print("\nRAG Response:")
    print(result["rag_response"])

    print("\n1. Unsupported Claim Detection:")
    print(
        "Flagged:",
        detection["signals"]["unsupported_claim"]["flagged"]
    )
    print(
        "Unsupported Numbers:",
        detection["signals"]["unsupported_claim"]["unsupported_numbers"]
    )
    print(
        "Unsupported Entities:",
        detection["signals"]["unsupported_claim"]["unsupported_entities"]
    )

    print("\n2. Retrieval Overlap:")
    print(
        "Jaccard Score:",
        round(
            detection["signals"]["retrieval_overlap"]["jaccard_score"],
            4
        )
    )
    print(
        "Flagged:",
        detection["signals"]["retrieval_overlap"]["flagged"]
    )

    print("\n3. Contradiction Detection:")
    print(
        "LLM Judgement:",
        detection["signals"]["contradiction"]["model_judgement"]
    )
    print(
        "Flagged:",
        detection["signals"]["contradiction"]["flagged"]
    )

    print("\n4. Citation Absence:")
    print(
        "Has Citation:",
        detection["signals"]["citation_absence"]["has_citation"]
    )
    print(
        "Flagged:",
        detection["signals"]["citation_absence"]["flagged"]
    )

    print("\nFINAL CONFIDENCE SCORE:")
    print(
        f"{detection['final_confidence_score']:.2f}%"
    )

================================================================================
Question 1
--------------------------------------------------------------------------------
Question:
What is the chemical symbol for gold?

RAG Response:
Au

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.0833
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 2
--------------------------------------------------------------------------------
Question:
What planet is known as the Red Planet?

RAG Response:
Mars

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.0909
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 3
--------------------------------------------------------------------------------
Question:
What is the approximate speed of light in vacuum?

RAG Response:
299,792 kilometers per second

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.3125
Flagged: False

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: True

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 4
--------------------------------------------------------------------------------
Question:
What gas do plants primarily absorb from the atmosphere during photosynthesis?

RAG Response:
carbon dioxide

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.1111
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 5
--------------------------------------------------------------------------------
Question:
How many chromosomes are normally present in a human somatic cell?

RAG Response:
46

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.0769
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 6
--------------------------------------------------------------------------------
Question:
What is the capital city of Australia?

RAG Response:
Canberra

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.1111
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 7
--------------------------------------------------------------------------------
Question:
Which is the largest ocean on Earth?

RAG Response:
Pacific Ocean

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.1818
Flagged: False

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
100.00%

================================================================================
Question 8
--------------------------------------------------------------------------------
Question:
What is the longest river in South America?

RAG Response:
Amazon River

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.1667
Flagged: False

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
100.00%

================================================================================
Question 9
--------------------------------------------------------------------------------
Question:
Which country has the city of Kyoto?

RAG Response:
Japan

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.0909
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 10
--------------------------------------------------------------------------------
Question:
What is the capital of Canada?

RAG Response:
Ottawa

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.1111
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 11
--------------------------------------------------------------------------------
Question:
What does CPU stand for?

RAG Response:
Central Processing Unit

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.3
Flagged: False

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: True

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 12
--------------------------------------------------------------------------------
Question:
What data structure follows the LIFO principle?

RAG Response:
A stack

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.1111
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 13
--------------------------------------------------------------------------------
Question:
What does HTTP stand for?

RAG Response:
Hypertext Transfer Protocol

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.3
Flagged: False

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: True

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 14
--------------------------------------------------------------------------------
Question:
What is the time complexity of binary search on a sorted array?

RAG Response:
O(log n)

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.1579
Flagged: False

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: True

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 15
--------------------------------------------------------------------------------
Question:
Which programming language was created by Guido van Rossum?

RAG Response:
Python

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.0769
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 16
--------------------------------------------------------------------------------
Question:
In which year did India gain independence from British rule?

RAG Response:
1947

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.0556
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 17
--------------------------------------------------------------------------------
Question:
Who was the first President of the United States?

RAG Response:
George Washington

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.1538
Flagged: False

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
100.00%

================================================================================
Question 18
--------------------------------------------------------------------------------
Question:
Which ancient civilization built the pyramids at Giza?

RAG Response:
Egyptians

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.0588
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 19
--------------------------------------------------------------------------------
Question:
Who wrote the Indian national anthem 'Jana Gana Mana'?

RAG Response:
Rabindranath Tagore

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.125
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

================================================================================
Question 20
--------------------------------------------------------------------------------
Question:
In which year did World War II end?

RAG Response:
1945

1. Unsupported Claim Detection:
Flagged: False
Unsupported Numbers: []
Unsupported Entities: []

2. Retrieval Overlap:
Jaccard Score: 0.0909
Flagged: True

3. Contradiction Detection:
LLM Judgement: no
Flagged: False

4. Citation Absence:
Has Citation: False
Flagged: False

FINAL CONFIDENCE SCORE:
75.00%

In [57]:
import pandas as pd

detector_rows = []

for result in detection_results.values():

    detection = result["detection"]
    signals = detection["signals"]

    detector_rows.append({
        "ID": result["id"],
        "Question": result["question"],
        "Response": result["rag_response"],

        "Unsupported Claim":
            signals["unsupported_claim"]["flagged"],

        "Jaccard Score":
            round(
                signals["retrieval_overlap"]["jaccard_score"],
                4
            ),

        "Low Overlap":
            signals["retrieval_overlap"]["flagged"],

        "Contradiction":
            signals["contradiction"]["flagged"],

        "Citation Absent":
            signals["citation_absence"]["flagged"],

        "Confidence Score":
            round(
                detection["final_confidence_score"],
                2
            )
    })

detector_df = pd.DataFrame(detector_rows)

detector_df

,ID,Question,Response,Unsupported Claim,Jaccard Score,Low Overlap,Contradiction,Citation Absent,Confidence Score
0,1,What is the chemical symbol for gold?,Au,False,0.0833,True,False,False,75.0
1,2,What planet is known as the Red Planet?,Mars,False,0.0909,True,False,False,75.0
2,3,What is the approximate speed of light in vacuum?,"299,792 kilometers per second",False,0.3125,False,False,True,75.0
3,4,What gas do plants primarily absorb from the a...,carbon dioxide,False,0.1111,True,False,False,75.0
4,5,How many chromosomes are normally present in a...,46,False,0.0769,True,False,False,75.0
5,6,What is the capital city of Australia?,Canberra,False,0.1111,True,False,False,75.0
6,7,Which is the largest ocean on Earth?,Pacific Ocean,False,0.1818,False,False,False,100.0
7,8,What is the longest river in South America?,Amazon River,False,0.1667,False,False,False,100.0
8,9,Which country has the city of Kyoto?,Japan,False,0.0909,True,False,False,75.0
9,10,What is the capital of Canada?,Ottawa,False,0.1111,True,False,False,75.0
10,11,What does CPU stand for?,Central Processing Unit,False,0.3000,False,False,True,75.0
11,12,What data structure follows the LIFO principle?,A stack,False,0.1111,True,False,False,75.0
12,13,What does HTTP stand for?,Hypertext Transfer Protocol,False,0.3000,False,False,True,75.0
13,14,What is the time complexity of binary search o...,O(log n),False,0.1579,False,False,True,75.0
14,15,Which programming language was created by Guid...,Python,False,0.0769,True,False,False,75.0
15,16,In which year did India gain independence from...,1947,False,0.0556,True,False,False,75.0
16,17,Who was the first President of the United States?,George Washington,False,0.1538,False,False,False,100.0
17,18,Which ancient civilization built the pyramids ...,Egyptians,False,0.0588,True,False,False,75.0
18,19,Who wrote the Indian national anthem 'Jana Gan...,Rabindranath Tagore,False,0.1250,True,False,False,75.0
19,20,In which year did World War II end?,1945,False,0.0909,True,False,False,75.0

In [58]:
signal_counts = {
    "unsupported_claim": 0,
    "low_retrieval_overlap": 0,
    "contradiction": 0,
    "citation_absence": 0
}

for result in detection_results.values():

    signals = result["detection"]["signals"]

    if signals["unsupported_claim"]["flagged"]:
        signal_counts["unsupported_claim"] += 1

    if signals["retrieval_overlap"]["flagged"]:
        signal_counts["low_retrieval_overlap"] += 1

    if signals["contradiction"]["flagged"]:
        signal_counts["contradiction"] += 1

    if signals["citation_absence"]["flagged"]:
        signal_counts["citation_absence"] += 1


print("Signal Detection Summary")
print("-" * 40)

for signal, count in signal_counts.items():
    print(f"{signal}: {count}/20")

Signal Detection Summary
----------------------------------------
unsupported_claim: 0/20
low_retrieval_overlap: 13/20
contradiction: 0/20
citation_absence: 4/20

In [59]:
with open(
    "hallucination_detection_results.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        detection_results,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Detector results saved.")

Detector results saved.

In [60]:
comparison = {
    "No Context": {
        "Total": len(results),
        "Correct": classification_counts["correct"],
        "Partially Correct": classification_counts["partially_correct"],
        "Hallucinated": classification_counts["hallucinated"],
        "Hallucination Rate (%)": round(hallucination_rate, 2)
    },

    "RAG": {
        "Total": len(rag_results),
        "Correct": rag_classification_counts["correct"],
        "Partially Correct": rag_classification_counts["partially_correct"],
        "Hallucinated": rag_classification_counts["hallucinated"],
        "Hallucination Rate (%)": round(rag_hallucination_rate, 2)
    }
}

comparison_df = pd.DataFrame(comparison).T

comparison_df

,Total,Correct,Partially Correct,Hallucinated,Hallucination Rate (%)
No Context,20.0,0.0,0.0,0.0,0.0
RAG,20.0,19.0,0.0,1.0,5.0

In [61]:
absolute_reduction = no_context_rate - rag_rate

if no_context_rate > 0:
    relative_reduction = (
        (no_context_rate - rag_rate)
        / no_context_rate
    ) * 100
else:
    relative_reduction = 0

print(f"No-context rate: {no_context_rate:.2f}%")
print(f"RAG rate: {rag_rate:.2f}%")
print(f"Absolute change: {absolute_reduction:.2f} percentage points")
print(f"Relative change: {relative_reduction:.2f}%")

No-context rate: 0.00%
RAG rate: 5.00%
Absolute change: -5.00 percentage points
Relative change: 0.00%

In [62]:
failure_rows = []

for result in results.values():

    if result["classification"] == "hallucinated":

        failure_rows.append({
            "ID": result["id"],
            "Domain": result["domain"],
            "Question": result["question"],
            "Response": result["no_context_response"],
            "Ground Truth": result["ground_truth"],
            "Hallucination Type": result["hallucination_type"]
        })

failure_df = pd.DataFrame(failure_rows)

failure_df

Empty DataFrame
Columns: []
Index: []

In [63]:
report_rows = []

for result in rag_results.values():

    detection = detection_results[result["id"]]["detection"]
    signals = detection["signals"]

    report_rows.append({
        "ID": result["id"],
        "Domain": result["domain"],
        "Question": result["question"],
        "RAG Response": result["rag_response"],
        "Human Classification": result["classification"],

        "Unsupported Claim":
            signals["unsupported_claim"]["flagged"],

        "Jaccard Score":
            round(
                signals["retrieval_overlap"]["jaccard_score"],
                4
            ),

        "Low Overlap":
            signals["retrieval_overlap"]["flagged"],

        "Contradiction":
            signals["contradiction"]["flagged"],

        "Citation Absent":
            signals["citation_absence"]["flagged"],

        "Confidence Score":
            round(
                detection["final_confidence_score"],
                2
            )
    })

report_df = pd.DataFrame(report_rows)

report_df

,ID,Domain,Question,RAG Response,Human Classification,Unsupported Claim,Jaccard Score,Low Overlap,Contradiction,Citation Absent,Confidence Score
0,1,Science,What is the chemical symbol for gold?,Au,hallucinated,False,0.0833,True,False,False,75.0
1,2,Science,What planet is known as the Red Planet?,Mars,correct,False,0.0909,True,False,False,75.0
2,3,Science,What is the approximate speed of light in vacuum?,"299,792 kilometers per second",correct,False,0.3125,False,False,True,75.0
3,4,Science,What gas do plants primarily absorb from the a...,carbon dioxide,correct,False,0.1111,True,False,False,75.0
4,5,Science,How many chromosomes are normally present in a...,46,correct,False,0.0769,True,False,False,75.0
5,6,Geography,What is the capital city of Australia?,Canberra,correct,False,0.1111,True,False,False,75.0
6,7,Geography,Which is the largest ocean on Earth?,Pacific Ocean,correct,False,0.1818,False,False,False,100.0
7,8,Geography,What is the longest river in South America?,Amazon River,correct,False,0.1667,False,False,False,100.0
8,9,Geography,Which country has the city of Kyoto?,Japan,correct,False,0.0909,True,False,False,75.0
9,10,Geography,What is the capital of Canada?,Ottawa,correct,False,0.1111,True,False,False,75.0
10,11,Computer Science,What does CPU stand for?,Central Processing Unit,correct,False,0.3000,False,False,True,75.0
11,12,Computer Science,What data structure follows the LIFO principle?,A stack,correct,False,0.1111,True,False,False,75.0
12,13,Computer Science,What does HTTP stand for?,Hypertext Transfer Protocol,correct,False,0.3000,False,False,True,75.0
13,14,Computer Science,What is the time complexity of binary search o...,O(log n),correct,False,0.1579,False,False,True,75.0
14,15,Computer Science,Which programming language was created by Guid...,Python,correct,False,0.0769,True,False,False,75.0
15,16,History,In which year did India gain independence from...,1947,correct,False,0.0556,True,False,False,75.0
16,17,History,Who was the first President of the United States?,George Washington,correct,False,0.1538,False,False,False,100.0
17,18,History,Which ancient civilization built the pyramids ...,Egyptians,correct,False,0.0588,True,False,False,75.0
18,19,History,Who wrote the Indian national anthem 'Jana Gan...,Rabindranath Tagore,correct,False,0.1250,True,False,False,75.0
19,20,History,In which year did World War II end?,1945,correct,False,0.0909,True,False,False,75.0

In [64]:
detector_summary = pd.DataFrame([
    {
        "Signal": "Unsupported Claim",
        "Flagged": signal_counts["unsupported_claim"],
        "Total": 20
    },
    {
        "Signal": "Low Retrieval Overlap",
        "Flagged": signal_counts["low_retrieval_overlap"],
        "Total": 20
    },
    {
        "Signal": "Contradiction",
        "Flagged": signal_counts["contradiction"],
        "Total": 20
    },
    {
        "Signal": "Citation Absence",
        "Flagged": signal_counts["citation_absence"],
        "Total": 20
    }
])

detector_summary["Flag Rate (%)"] = (
    detector_summary["Flagged"]
    / detector_summary["Total"]
    * 100
).round(2)

detector_summary

                  Signal  Flagged  Total  Flag Rate (%)
0      Unsupported Claim        0     20            0.0
1  Low Retrieval Overlap       13     20           65.0
2          Contradiction        0     20            0.0
3       Citation Absence        4     20           20.0

In [65]:
final_report = {
    "experiment": {
        "name": "Hallucination Measurement Experiment",
        "total_questions": 20,
        "domains": [
            "Science",
            "Geography",
            "Computer Science",
            "History"
        ]
    },

    "no_context": {
        "results": list(results.values()),
        "hallucination_rate": hallucination_rate
    },

    "rag": {
        "results": list(rag_results.values()),
        "hallucination_rate": rag_hallucination_rate
    },

    "comparison": comparison,

    "detector": {
        "signal_counts": signal_counts,
        "per_response": detection_results
    }
}

with open(
    "final_hallucination_report.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        final_report,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Final report data saved successfully.")

Final report data saved successfully.

In [66]:
report_text = f"""
# Hallucination Measurement Experiment

## 1. Objective

This experiment measures hallucination in a language model under two conditions:

1. No context
2. Retrieval-Augmented Generation (RAG)

The experiment uses 20 factual questions across four knowledge domains.

## 2. Dataset

Total questions: 20

Domains:
- Science
- Geography
- Computer Science
- History

## 3. Evaluation Criteria

### Correct
The response accurately matches the ground-truth answer.

### Partially Correct
The response contains substantially correct information but is incomplete or has a minor issue.

### Hallucinated
The response contains factually incorrect, fabricated, contradictory, or unsupported information.

## 4. Hallucination Categories

- Fabricated specific fact
- Outdated information
- Confident wrong answer
- Plausible-sounding but unverifiable claim

## 5. Results

### No Context

- Total: {len(results)}
- Correct: {classification_counts["correct"]}
- Partially Correct: {classification_counts["partially_correct"]}
- Hallucinated: {classification_counts["hallucinated"]}
- Hallucination Rate: {hallucination_rate:.2f}%

### RAG

- Total: {len(rag_results)}
- Correct: {rag_classification_counts["correct"]}
- Partially Correct: {rag_classification_counts["partially_correct"]}
- Hallucinated: {rag_classification_counts["hallucinated"]}
- Hallucination Rate: {rag_hallucination_rate:.2f}%

## 6. Comparison

No-context hallucination rate:
{no_context_rate:.2f}%

RAG hallucination rate:
{rag_rate:.2f}%

Absolute change:
{absolute_reduction:.2f} percentage points

Relative change:
{relative_reduction:.2f}%

## 7. Four-Signal Hallucination Detector

The detector uses four independent signals:

1. Unsupported claim detection
2. Retrieval overlap using Jaccard similarity
3. Contradiction detection
4. Citation absence detection

### Detector Results

- Unsupported claims flagged: {signal_counts["unsupported_claim"]}/20
- Low retrieval overlap flagged: {signal_counts["low_retrieval_overlap"]}/20
- Contradictions flagged: {signal_counts["contradiction"]}/20
- Citation absence flagged: {signal_counts["citation_absence"]}/20

## 8. Confidence Score

Each response receives a rule-based confidence score based on the four detector signals.

Each flagged signal reduces the confidence score.

The score should be interpreted as a detector confidence indicator, not as a statistical probability of factual correctness.

## 9. Conclusion

The experiment compares the hallucination behavior of a language model with and without retrieved context.

The results show how retrieval can affect factual reliability and demonstrate why hallucination detection benefits from multiple independent signals rather than relying on a single heuristic.
"""

with open(
    "HALLUCINATION_REPORT.md",
    "w",
    encoding="utf-8"
) as f:

    f.write(report_text)

print("HALLUCINATION_REPORT.md created successfully.")

HALLUCINATION_REPORT.md created successfully.