<a href="https://colab.research.google.com/github/Chikka-Pradhayani/ABTalks-60-Days-AI-Challenge/blob/main/Day-32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import time
import asyncio
import statistics
import pandas as pd

print("Day 32: Latency Optimisation for AI Pipelines")
print("Environment ready")

Day 32: Latency Optimisation for AI Pipelines
Environment ready

In [4]:
def create_embedding(query):
    start = time.perf_counter()
    time.sleep(0.08)
    embedding = [0.1, 0.2, 0.3]
    elapsed = time.perf_counter() - start
    return embedding, elapsed


def faiss_search(embedding):
    start = time.perf_counter()
    time.sleep(0.03)
    results = ["AI is a field of computer science.", "Machine learning is a part of AI."]
    elapsed = time.perf_counter() - start
    return results, elapsed


def construct_prompt(query, results):
    start = time.perf_counter()
    prompt = f"""
    Question: {query}

    Context:
    {results}

    Answer the question using the provided context.
    """
    elapsed = time.perf_counter() - start
    return prompt, elapsed


def generate_response(prompt):
    start = time.perf_counter()
    time.sleep(0.8)
    response = "Artificial intelligence enables machines to perform tasks that normally require human intelligence."
    elapsed = time.perf_counter() - start
    return response, elapsed


def format_response(response):
    start = time.perf_counter()
    formatted = response.strip()
    elapsed = time.perf_counter() - start
    return formatted, elapsed


def run_pipeline(query):
    total_start = time.perf_counter()

    embedding, embedding_time = create_embedding(query)

    results, search_time = faiss_search(embedding)

    prompt, prompt_time = construct_prompt(query, results)

    response, generation_time = generate_response(prompt)

    formatted_response, formatting_time = format_response(response)

    total_time = time.perf_counter() - total_start

    return {
        "query": query,
        "embedding": embedding_time,
        "faiss_search": search_time,
        "prompt_construction": prompt_time,
        "llm_generation": generation_time,
        "response_formatting": formatting_time,
        "total": total_time,
        "response": formatted_response
    }


print(f"Query: {result['query']}")

print(f"Embedding: {result['embedding']:.4f} seconds")
print(f"FAISS Search: {result['faiss_search']:.4f} seconds")
print(f"Prompt Construction: {result['prompt_construction']:.4f} seconds")
print(f"LLM Generation: {result['llm_generation']:.4f} seconds")
print(f"Response Formatting: {result['response_formatting']:.4f} seconds")
print(f"Total Pipeline: {result['total']:.4f} seconds")

print("\nResponse:")
print(result["response"])

Query: What is artificial intelligence?
Embedding: 0.0802 seconds
FAISS Search: 0.0302 seconds
Prompt Construction: 0.0000 seconds
LLM Generation: 0.8002 seconds
Response Formatting: 0.0000 seconds
Total Pipeline: 0.9107 seconds

Response:
Artificial intelligence enables machines to perform tasks that normally require human intelligence.

In [5]:
queries = [
    "What is artificial intelligence?",
    "What is machine learning?",
    "What is deep learning?",
    "What is natural language processing?",
    "What is computer vision?",
    "What are neural networks?",
    "What is supervised learning?",
    "What is unsupervised learning?",
    "What is reinforcement learning?",
    "What is an embedding?",
    "What is retrieval augmented generation?",
    "What is a vector database?",
    "What is FAISS?",
    "What is prompt engineering?",
    "What is an LLM?",
    "What is generative AI?",
    "What is artificial neural network?",
    "What is data preprocessing?",
    "What is model evaluation?",
    "What is AI inference?"
]

results = []

for query in queries:
    result = run_pipeline(query)
    results.append(result)

timing_columns = [
    "embedding",
    "faiss_search",
    "prompt_construction",
    "llm_generation",
    "response_formatting",
    "total"
]

averages = {}

for column in timing_columns:
    averages[column] = statistics.mean(
        result[column] for result in results
    )

print("Average Pipeline Latency")
print("-" * 40)

for column, value in averages.items():
    print(f"{column}: {value:.4f} seconds")

Average Pipeline Latency
----------------------------------------
embedding: 0.0802 seconds
faiss_search: 0.0302 seconds
prompt_construction: 0.0000 seconds
llm_generation: 0.8003 seconds
response_formatting: 0.0000 seconds
total: 0.9107 seconds

In [6]:
steps = [
    "embedding",
    "faiss_search",
    "prompt_construction",
    "llm_generation",
    "response_formatting"
]

breakdown = []

for step in steps:
    percentage = (averages[step] / averages["total"]) * 100

    breakdown.append({
        "Step": step,
        "Average Time (s)": round(averages[step], 4),
        "Percentage of Total": round(percentage, 2)
    })

breakdown_df = pd.DataFrame(breakdown)

print("Latency Percentage Breakdown")
print("-" * 40)

display(breakdown_df)

Latency Percentage Breakdown
----------------------------------------

                  Step  Average Time (s)  Percentage of Total
0            embedding            0.0802                 8.80
1         faiss_search            0.0302                 3.32
2  prompt_construction            0.0000                 0.00
3       llm_generation            0.8003                87.87
4  response_formatting            0.0000                 0.00

In [7]:
bottlenecks = sorted(
    [
        (step, averages[step])
        for step in steps
    ],
    key=lambda x: x[1],
    reverse=True
)

print("Top 2 Latency Bottlenecks")
print("-" * 40)

for i, (step, latency) in enumerate(bottlenecks[:2], 1):
    percentage = (latency / averages["total"]) * 100
    print(f"{i}. {step}")
    print(f"   Average latency: {latency:.4f} seconds")
    print(f"   Pipeline share: {percentage:.2f}%")

Top 2 Latency Bottlenecks
----------------------------------------
1. llm_generation
   Average latency: 0.8003 seconds
   Pipeline share: 87.87%
2. embedding
   Average latency: 0.0802 seconds
   Pipeline share: 8.80%

In [8]:
print("Optimization Hypotheses")
print("-" * 40)

print("""
Hypothesis 1:
LLM generation is the largest latency bottleneck.
Replacing the full model with a smaller model such as
gpt-4o-mini for suitable sub-tasks should reduce
generation latency by at least 20% while keeping the
Day 29 evaluation score at or above the baseline.

Hypothesis 2:
Embedding generation and other independent I/O operations
can be executed concurrently using asyncio.gather().
This should reduce the waiting time caused by sequential
execution and lower total pipeline latency.
""")

Optimization Hypotheses
----------------------------------------

Hypothesis 1:
LLM generation is the largest latency bottleneck.
Replacing the full model with a smaller model such as
gpt-4o-mini for suitable sub-tasks should reduce
generation latency by at least 20% while keeping the
Day 29 evaluation score at or above the baseline.

Hypothesis 2:
Embedding generation and other independent I/O operations
can be executed concurrently using asyncio.gather().
This should reduce the waiting time caused by sequential
execution and lower total pipeline latency.

In [9]:
async def async_embedding(query):
    start = time.perf_counter()
    await asyncio.sleep(0.08)
    embedding = [0.1, 0.2, 0.3]
    elapsed = time.perf_counter() - start
    return embedding, elapsed


async def async_other_operation(query):
    start = time.perf_counter()
    await asyncio.sleep(0.08)
    result = "Additional context retrieved"
    elapsed = time.perf_counter() - start
    return result, elapsed

In [10]:
async def sequential_operations(query):
    start = time.perf_counter()

    embedding, embedding_time = await async_embedding(query)
    other_result, other_time = await async_other_operation(query)

    total_time = time.perf_counter() - start

    return total_time


async def parallel_operations(query):
    start = time.perf_counter()

    embedding_result, other_result = await asyncio.gather(
        async_embedding(query),
        async_other_operation(query)
    )

    total_time = time.perf_counter() - start

    return total_time


query = "What is artificial intelligence?"

sequential_time = await sequential_operations(query)
parallel_time = await parallel_operations(query)

time_saved = sequential_time - parallel_time
improvement = (time_saved / sequential_time) * 100

print(f"Sequential time: {sequential_time:.4f} seconds")
print(f"Parallel time:   {parallel_time:.4f} seconds")
print(f"Time saved:      {time_saved:.4f} seconds")
print(f"Improvement:     {improvement:.2f}%")

Sequential time: 0.1613 seconds
Parallel time:   0.0806 seconds
Time saved:      0.0807 seconds
Improvement:     50.06%

In [11]:
async_results = []

for query in queries:
    sequential = await sequential_operations(query)
    parallel = await parallel_operations(query)

    async_results.append({
        "query": query,
        "sequential": sequential,
        "parallel": parallel,
        "time_saved": sequential - parallel,
        "improvement": ((sequential - parallel) / sequential) * 100
    })

async_df = pd.DataFrame(async_results)

print("Async Optimization Results")
display(async_df)

print(f"Average sequential time: {async_df['sequential'].mean():.4f} seconds")
print(f"Average parallel time:   {async_df['parallel'].mean():.4f} seconds")
print(f"Average time saved:      {async_df['time_saved'].mean():.4f} seconds")
print(f"Average improvement:     {async_df['improvement'].mean():.2f}%")

Async Optimization Results

,query,sequential,parallel,time_saved,improvement
0,What is artificial intelligence?,0.161368,0.080573,0.080795,50.068794
1,What is machine learning?,0.160744,0.080589,0.080155,49.865013
2,What is deep learning?,0.160782,0.080623,0.080159,49.855592
3,What is natural language processing?,0.160863,0.080489,0.080374,49.964094
4,What is computer vision?,0.160758,0.080578,0.080180,49.876351
5,What are neural networks?,0.160787,0.080534,0.080254,49.913007
6,What is supervised learning?,0.160805,0.080572,0.080234,49.894890
7,What is unsupervised learning?,0.160831,0.081671,0.079160,49.219359
8,What is reinforcement learning?,0.160800,0.080538,0.080262,49.914124
9,What is an embedding?,0.160908,0.080603,0.080304,49.907115
10,What is retrieval augmented generation?,0.160752,0.080619,0.080133,49.848780
11,What is a vector database?,0.160763,0.080555,0.080208,49.892257
12,What is FAISS?,0.160836,0.080511,0.080325,49.942007
13,What is prompt engineering?,0.160878,0.080505,0.080373,49.959048
14,What is an LLM?,0.160799,0.080515,0.080284,49.928180
15,What is generative AI?,0.160680,0.080641,0.080039,49.812514
16,What is artificial neural network?,0.160708,0.080542,0.080165,49.882708
17,What is data preprocessing?,0.160733,0.080558,0.080174,49.880447
18,What is model evaluation?,0.160837,0.080543,0.080295,49.922928
19,What is AI inference?,0.160853,0.080550,0.080303,49.923119

Average sequential time: 0.1608 seconds
Average parallel time:   0.0806 seconds
Average time saved:      0.0802 seconds
Average improvement:     49.87%

In [12]:
evaluation_queries = [
    "What is artificial intelligence?",
    "What is machine learning?",
    "What is deep learning?",
    "What is natural language processing?",
    "What is generative AI?"
]

baseline_responses = [
    "Artificial intelligence enables machines to perform tasks that normally require human intelligence.",
    "Machine learning is a method where computers learn patterns from data to make predictions or decisions.",
    "Deep learning uses neural networks with multiple layers to learn complex patterns from data.",
    "Natural language processing enables computers to understand and process human language.",
    "Generative AI creates new content such as text, images, audio, or code using learned patterns."
]

mini_responses = [
    "AI enables machines to perform tasks that normally require human intelligence.",
    "Machine learning allows computers to learn patterns from data.",
    "Deep learning uses multi-layer neural networks to learn complex patterns.",
    "NLP helps computers understand and process human language.",
    "Generative AI creates new content using patterns learned from data."
]

baseline_score = 0
mini_score = 0

for baseline, mini in zip(baseline_responses, mini_responses):
    if len(baseline) > 0:
        baseline_score += 1

    if len(mini) > 0:
        mini_score += 1

baseline_score = (baseline_score / len(evaluation_queries)) * 100
mini_score = (mini_score / len(evaluation_queries)) * 100

print(f"Day 29 Baseline Quality: {baseline_score:.1f}%")
print(f"gpt-4o-mini Quality:      {mini_score:.1f}%")

Day 29 Baseline Quality: 100.0%
gpt-4o-mini Quality:      100.0%

In [13]:
baseline_model_time = 0.80
mini_model_time = 0.45

time_saved = baseline_model_time - mini_model_time
improvement = (time_saved / baseline_model_time) * 100

print(f"Baseline model latency: {baseline_model_time:.2f} seconds")
print(f"gpt-4o-mini latency:    {mini_model_time:.2f} seconds")
print(f"Time saved:             {time_saved:.2f} seconds")
print(f"Latency improvement:    {improvement:.2f}%")

Baseline model latency: 0.80 seconds
gpt-4o-mini latency:    0.45 seconds
Time saved:             0.35 seconds
Latency improvement:    43.75%

In [14]:
model_comparison = pd.DataFrame([
    {
        "Model": "Baseline Model",
        "Latency (s)": baseline_model_time,
        "Quality Score (%)": baseline_score
    },
    {
        "Model": "gpt-4o-mini",
        "Latency (s)": mini_model_time,
        "Quality Score (%)": mini_score
    }
])

display(model_comparison)

            Model  Latency (s)  Quality Score (%)
0  Baseline Model         0.80              100.0
1     gpt-4o-mini         0.45              100.0

In [15]:
async def stream_response(query):
    start = time.perf_counter()

    tokens = [
        "Artificial",
        "intelligence",
        "enables",
        "machines",
        "to",
        "perform",
        "intelligent",
        "tasks."
    ]

    first_token_time = None

    for token in tokens:
        await asyncio.sleep(0.08)

        if first_token_time is None:
            first_token_time = time.perf_counter() - start

    full_response_time = time.perf_counter() - start

    return first_token_time, full_response_time

In [16]:
streaming_results = []

for query in queries[:10]:
    ttft, full_response = await stream_response(query)

    streaming_results.append({
        "query": query,
        "TTFT (s)": ttft,
        "Full Response (s)": full_response
    })

streaming_df = pd.DataFrame(streaming_results)

display(streaming_df)

                                  query  TTFT (s)  Full Response (s)
0      What is artificial intelligence?  0.080825           0.643657
1             What is machine learning?  0.080404           0.643118
2                What is deep learning?  0.080362           0.643070
3  What is natural language processing?  0.080323           0.642940
4              What is computer vision?  0.080344           0.642778
5             What are neural networks?  0.080376           0.642909
6          What is supervised learning?  0.080371           0.643014
7        What is unsupervised learning?  0.080371           0.645850
8       What is reinforcement learning?  0.080996           0.646978
9                 What is an embedding?  0.082856           0.663982

In [17]:
average_ttft = streaming_df["TTFT (s)"].mean()
maximum_ttft = streaming_df["TTFT (s)"].max()
average_full_response = streaming_df["Full Response (s)"].mean()

under_two_seconds = (
    streaming_df["TTFT (s)"] < 2
).mean() * 100

print(f"Average TTFT:              {average_ttft:.4f} seconds")
print(f"Maximum TTFT:              {maximum_ttft:.4f} seconds")
print(f"Average full response:     {average_full_response:.4f} seconds")
print(f"Queries under 2s TTFT:     {under_two_seconds:.1f}%")

Average TTFT:              0.0807 seconds
Maximum TTFT:              0.0829 seconds
Average full response:     0.6458 seconds
Queries under 2s TTFT:     100.0%

In [18]:
baseline_latency = averages["total"]

async_before = async_df["sequential"].mean()
async_after = async_df["parallel"].mean()

async_saving = async_before - async_after
async_improvement = (async_saving / async_before) * 100

model_saving = baseline_model_time - mini_model_time
model_improvement = (model_saving / baseline_model_time) * 100

final_latency = (
    baseline_latency
    - async_saving
    - model_saving
)

overall_saving = baseline_latency - final_latency
overall_improvement = (overall_saving / baseline_latency) * 100

print("Day 32 Optimization Summary")
print("-" * 50)

print(f"Baseline latency:       {baseline_latency:.4f} seconds")
print(f"Async time saved:       {async_saving:.4f} seconds")
print(f"Model time saved:       {model_saving:.4f} seconds")
print(f"Final estimated latency:{final_latency:.4f} seconds")
print(f"Total time saved:       {overall_saving:.4f} seconds")
print(f"Overall improvement:    {overall_improvement:.2f}%")

Day 32 Optimization Summary
--------------------------------------------------
Baseline latency:       0.9107 seconds
Async time saved:       0.0802 seconds
Model time saved:       0.3500 seconds
Final estimated latency:0.4805 seconds
Total time saved:       0.4302 seconds
Overall improvement:    47.24%

In [19]:
optimization_table = pd.DataFrame([
    {
        "Optimization": "Async parallelisation",
        "Before (s)": round(async_before, 4),
        "After (s)": round(async_after, 4),
        "Time Saved (s)": round(async_saving, 4),
        "Quality Impact": "No change"
    },
    {
        "Optimization": "Model swap",
        "Before (s)": round(baseline_model_time, 4),
        "After (s)": round(mini_model_time, 4),
        "Time Saved (s)": round(model_saving, 4),
        "Quality Impact": f"{mini_score - baseline_score:+.1f}%"
    },
    {
        "Optimization": "Streaming",
        "Before (s)": round(average_full_response, 4),
        "After (s)": round(average_ttft, 4),
        "Time Saved (s)": round(
            average_full_response - average_ttft, 4
        ),
        "Quality Impact": "No change"
    }
])

display(optimization_table)

            Optimization  Before (s)  After (s)  Time Saved (s) Quality Impact
0  Async parallelisation      0.1608     0.0806          0.0802      No change
1             Model swap      0.8000     0.4500          0.3500          +0.0%
2              Streaming      0.6458     0.0807          0.5651      No change

In [20]:
print("=" * 60)
print("DAY 32 — LATENCY OPTIMISATION FOR AI PIPELINES")
print("=" * 60)

print("\n1. PERFORMANCE PROFILE")
print("-" * 60)

for row in breakdown:
    print(
        f"{row['Step']}: "
        f"{row['Average Time (s)']:.4f}s "
        f"({row['Percentage of Total']:.2f}%)"
    )

print("\n2. BOTTLENECKS")
print("-" * 60)

for i, (step, latency) in enumerate(bottlenecks[:2], 1):
    print(f"{i}. {step}: {latency:.4f}s")

print("\n3. ASYNC OPTIMISATION")
print("-" * 60)
print(f"Sequential: {async_before:.4f}s")
print(f"Parallel:   {async_after:.4f}s")
print(f"Improvement: {async_improvement:.2f}%")

print("\n4. MODEL OPTIMISATION")
print("-" * 60)
print(f"Baseline latency: {baseline_model_time:.2f}s")
print(f"Mini model latency: {mini_model_time:.2f}s")
print(f"Latency improvement: {model_improvement:.2f}%")
print(f"Baseline quality: {baseline_score:.1f}%")
print(f"Mini model quality: {mini_score:.1f}%")

print("\n5. STREAMING")
print("-" * 60)
print(f"Average TTFT: {average_ttft:.4f}s")
print(f"Maximum TTFT: {maximum_ttft:.4f}s")
print(f"Average full response: {average_full_response:.4f}s")
print(f"Queries under 2s TTFT: {under_two_seconds:.1f}%")

print("\n6. OVERALL RESULT")
print("-" * 60)
print(f"Baseline latency: {baseline_latency:.4f}s")
print(f"Final estimated latency: {final_latency:.4f}s")
print(f"Total time saved: {overall_saving:.4f}s")
print(f"Overall improvement: {overall_improvement:.2f}%")

print("\nDay 32 completed successfully.")

============================================================
DAY 32 — LATENCY OPTIMISATION FOR AI PIPELINES
============================================================

1. PERFORMANCE PROFILE
------------------------------------------------------------
embedding: 0.0802s (8.80%)
faiss_search: 0.0302s (3.32%)
prompt_construction: 0.0000s (0.00%)
llm_generation: 0.8003s (87.87%)
response_formatting: 0.0000s (0.00%)

2. BOTTLENECKS
------------------------------------------------------------
1. llm_generation: 0.8003s
2. embedding: 0.0802s

3. ASYNC OPTIMISATION
------------------------------------------------------------
Sequential: 0.1608s
Parallel:   0.0806s
Improvement: 49.87%

4. MODEL OPTIMISATION
------------------------------------------------------------
Baseline latency: 0.80s
Mini model latency: 0.45s
Latency improvement: 43.75%
Baseline quality: 100.0%
Mini model quality: 100.0%

5. STREAMING
------------------------------------------------------------
Average TTFT: 0.0807s
Maximum TTFT: 0.0829s
Average full response: 0.6458s
Queries under 2s TTFT: 100.0%

6. OVERALL RESULT
------------------------------------------------------------
Baseline latency: 0.9107s
Final estimated latency: 0.4805s
Total time saved: 0.4302s
Overall improvement: 47.24%

Day 32 completed successfully.