<a href="https://colab.research.google.com/github/Chikka-Pradhayani/ABTalks-60-Days-AI-Challenge/blob/main/Day-14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q faiss-cpu openai numpy pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 36.0 MB/s eta 0:00:00

In [2]:
import numpy as np
import pandas as pd
import faiss
from openai import OpenAI

In [3]:
corpus = [
    # Python
    "Python is a popular programming language used for automation, data analysis, and artificial intelligence.",
    "Python lists are ordered and mutable collections that can store multiple values.",
    "Python dictionaries store data as key-value pairs for fast lookups.",
    "Python functions help developers organize reusable blocks of code.",
    "Python exception handling allows programs to respond gracefully to runtime errors.",
    "Python libraries such as NumPy and Pandas are widely used for data processing.",

    # Java
    "Java is an object-oriented programming language commonly used for enterprise applications.",
    "Java classes define the properties and behavior of objects.",
    "Java arrays store multiple values of the same data type in a fixed-size structure.",
    "Java inheritance allows a class to acquire properties and methods from another class.",
    "Java interfaces define contracts that implementing classes must follow.",
    "Java exception handling uses try, catch, and finally blocks to handle errors.",

    # AI and Machine Learning
    "Machine learning algorithms learn patterns from data and use them to make predictions.",
    "Supervised learning trains models using datasets that contain labeled examples.",
    "Unsupervised learning discovers hidden patterns in data without predefined labels.",
    "Reinforcement learning allows an agent to learn through rewards and penalties.",
    "Artificial intelligence enables computers to perform tasks that normally require human intelligence.",
    "Deep learning uses neural networks with multiple layers to learn complex patterns.",

    # Deep Learning
    "Neural networks are computing models inspired by the structure of biological brains.",
    "Convolutional neural networks are particularly effective for analyzing images.",
    "Recurrent neural networks are designed to process sequential or time-dependent information.",
    "Transformers use attention mechanisms to understand relationships between tokens.",
    "Training a neural network involves adjusting model parameters to reduce prediction errors.",
    "Overfitting occurs when a machine learning model performs well on training data but poorly on new data.",

    # Databases
    "SQL is used to retrieve, insert, update, and delete information in relational databases.",
    "Relational databases organize information into tables containing rows and columns.",
    "Database indexes improve the speed of queries by providing efficient lookup structures.",
    "Primary keys uniquely identify records within a database table.",
    "Database normalization reduces redundant data and improves data consistency.",
    "Transactions allow multiple database operations to be treated as a single logical unit.",

    # Cloud Computing
    "Cloud computing provides computing resources such as servers and storage over the internet.",
    "Virtual machines allow multiple isolated computing environments to run on shared hardware.",
    "Cloud storage allows applications to store files and data on remote infrastructure.",
    "Serverless computing allows developers to run code without managing physical servers.",
    "Cloud platforms can automatically scale resources when application demand increases.",
    "Load balancing distributes incoming requests across multiple servers.",

    # Web Development
    "HTML defines the structure and content of web pages.",
    "CSS controls the appearance, layout, and visual presentation of websites.",
    "JavaScript adds interactive behavior and dynamic functionality to web applications.",
    "React is a JavaScript library used to build component-based user interfaces.",
    "REST APIs allow different software applications to communicate using HTTP requests.",
    "Web browsers send requests to servers and receive responses containing web resources.",

    # Cybersecurity
    "Cybersecurity protects computer systems, networks, and data from unauthorized access.",
    "Encryption converts readable information into a protected format using cryptographic algorithms.",
    "Authentication verifies the identity of a user or system.",
    "Authorization determines which resources an authenticated user is allowed to access.",
    "Phishing attacks attempt to trick users into revealing sensitive information.",
    "Firewalls monitor and control network traffic based on predefined security rules.",

    # Operating Systems
    "An operating system manages computer hardware and provides services to application programs.",
    "Processes are programs that are currently being executed by the operating system.",
    "Threads are smaller units of execution that can run within a process.",
    "Virtual memory allows an operating system to use storage as an extension of physical memory.",
    "CPU scheduling determines which process should receive processor time.",
    "File systems organize and manage files stored on computer storage devices."
]

print("Number of documents:", len(corpus))

Number of documents: 54

In [4]:
!pip install -q sentence-transformers faiss-cpu

In [5]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")
print("Embedding model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully!

In [6]:
embeddings = model.encode(corpus)
print("Embedding shape:", embeddings.shape)

Embedding shape: (54, 384)

In [7]:
embeddings = np.asarray(embeddings, dtype=np.float32)
print("Data type:", embeddings.dtype)
print("Shape:", embeddings.shape)

Data type: float32
Shape: (54, 384)

In [8]:
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
print("Vector dimension:", dimension)
print("FAISS index created!")

Vector dimension: 384
FAISS index created!

In [9]:
index.add(embeddings)
print("FAISS index size:", index.ntotal)

FAISS index size: 54

In [10]:
def semantic_search(query, top_k=3):
    query_embedding = model.encode([query])
    query_embedding = np.asarray(query_embedding, dtype=np.float32)
    distances, indices = index.search(query_embedding, top_k)
    results = []
    for distance, idx in zip(distances[0], indices[0]):
        results.append({
            "document": corpus[idx],
            "distance": float(distance)
        })
    return results

In [11]:
results = semantic_search("How do computers learn from data?", top_k=3)
for i, result in enumerate(results, 1):
    print(f"{i}. Distance: {result['distance']:.4f}")
    print(f"   {result['document']}")
    print()

1. Distance: 0.7628
   Machine learning algorithms learn patterns from data and use them to make predictions.

2. Distance: 1.0299
   Unsupervised learning discovers hidden patterns in data without predefined labels.

3. Distance: 1.1454
   Reinforcement learning allows an agent to learn through rewards and penalties.

In [13]:
import re
def keyword_search(query, corpus, top_k=3):
    query_words = set(re.findall(r"\b\w+\b", query.lower()))
    scores = []
    for idx, document in enumerate(corpus):
        document_words = set(re.findall(r"\b\w+\b", document.lower()))
        score = len(query_words.intersection(document_words))
        scores.append((idx, score))

    # Sort from highest to lowest
    scores.sort(key=lambda x: x[1], reverse=True)
    results = []
    for idx, score in scores[:top_k]:
        results.append({
            "document": corpus[idx],
            "score": score
        })
    return results

In [14]:
results = keyword_search(
    "How do computers learn from data?",
    corpus,
    top_k=3
)
for i, result in enumerate(results, 1):
    print(f"{i}. Score: {result['score']}")
    print(f"   {result['document']}")
    print()

1. Score: 3
   Machine learning algorithms learn patterns from data and use them to make predictions.

2. Score: 2
   Cybersecurity protects computer systems, networks, and data from unauthorized access.

3. Score: 1
   Python is a popular programming language used for automation, data analysis, and artificial intelligence.

In [15]:
test_queries = [
    "How do computers learn patterns from examples?",
    "How can I store information in tables?",
    "How do websites communicate with backend systems?",
    "How can applications use computers over the internet?",
    "How can I protect a computer network from attacks?",
    "How do programs handle unexpected errors?",
    "How can a computer understand images?",
    "How do computers manage running programs?",
    "How can I quickly find a specific record in a database?",
    "How can software automatically increase resources when demand grows?"
]
print("Number of test queries:", len(test_queries))

Number of test queries: 10

In [16]:
comparison_results = []
for query in test_queries:
    semantic_results = semantic_search(query, top_k=3)
    keyword_results = keyword_search(query, corpus, top_k=3)
    comparison_results.append({
        "Query": query,
        "Keyword Result": keyword_results[0]["document"],
        "Keyword Score": keyword_results[0]["score"],
        "Semantic Result": semantic_results[0]["document"],
        "Semantic Distance": round(semantic_results[0]["distance"], 4)
    })
comparison_df = pd.DataFrame(comparison_results)
comparison_df

,Query,Keyword Result,Keyword Score,Semantic Result,Semantic Distance
0,How do computers learn patterns from examples?,Machine learning algorithms learn patterns fro...,3,Machine learning algorithms learn patterns fro...,0.7062
1,How can I store information in tables?,Python lists are ordered and mutable collectio...,2,Relational databases organize information into...,0.7669
2,How do websites communicate with backend systems?,Deep learning uses neural networks with multip...,1,Web browsers send requests to servers and rece...,0.6763
3,How can applications use computers over the in...,Cloud computing provides computing resources s...,3,REST APIs allow different software application...,0.9880
4,How can I protect a computer network from atta...,Java inheritance allows a class to acquire pro...,2,"Cybersecurity protects computer systems, netwo...",0.9364
5,How do programs handle unexpected errors?,Python exception handling allows programs to r...,2,Python exception handling allows programs to r...,0.5082
6,How can a computer understand images?,Threads are smaller units of execution that ca...,2,Convolutional neural networks are particularly...,0.8488
7,How do computers manage running programs?,Python exception handling allows programs to r...,1,Processes are programs that are currently bein...,0.7489
8,How can I quickly find a specific record in a ...,Java arrays store multiple values of the same ...,2,Database indexes improve the speed of queries ...,1.0204
9,How can software automatically increase resour...,Cloud platforms can automatically scale resour...,5,Cloud platforms can automatically scale resour...,0.6095

In [17]:
for query in test_queries:
    print("=" * 100)
    print("QUERY:", query)
    print("\nKEYWORD SEARCH")
    keyword_results = keyword_search(query, corpus, top_k=3)
    for i, result in enumerate(keyword_results, 1):
        print(f"{i}. Score: {result['score']} | {result['document']}")
    print("\nSEMANTIC SEARCH")
    semantic_results = semantic_search(query, top_k=3)
    for i, result in enumerate(semantic_results, 1):
        print(f"{i}. Distance: {result['distance']:.4f} | {result['document']}")
    print()

====================================================================================================
QUERY: How do computers learn patterns from examples?

KEYWORD SEARCH
1. Score: 3 | Machine learning algorithms learn patterns from data and use them to make predictions.
2. Score: 2 | Deep learning uses neural networks with multiple layers to learn complex patterns.
3. Score: 1 | Java inheritance allows a class to acquire properties and methods from another class.

SEMANTIC SEARCH
1. Distance: 0.7062 | Machine learning algorithms learn patterns from data and use them to make predictions.
2. Distance: 0.8453 | Deep learning uses neural networks with multiple layers to learn complex patterns.
3. Distance: 0.9056 | Unsupervised learning discovers hidden patterns in data without predefined labels.

====================================================================================================
QUERY: How can I store information in tables?

KEYWORD SEARCH
1. Score: 2 | Python lists are ordered and mutable collections that can store multiple values.
2. Score: 2 | Java arrays store multiple values of the same data type in a fixed-size structure.
3. Score: 2 | SQL is used to retrieve, insert, update, and delete information in relational databases.

SEMANTIC SEARCH
1. Distance: 0.7669 | Relational databases organize information into tables containing rows and columns.
2. Distance: 1.0805 | SQL is used to retrieve, insert, update, and delete information in relational databases.
3. Distance: 1.2565 | Database normalization reduces redundant data and improves data consistency.

====================================================================================================
QUERY: How do websites communicate with backend systems?

KEYWORD SEARCH
1. Score: 1 | Deep learning uses neural networks with multiple layers to learn complex patterns.
2. Score: 1 | CSS controls the appearance, layout, and visual presentation of websites.
3. Score: 1 | REST APIs allow different software applications to communicate using HTTP requests.

SEMANTIC SEARCH
1. Distance: 0.6763 | Web browsers send requests to servers and receive responses containing web resources.
2. Distance: 0.9358 | REST APIs allow different software applications to communicate using HTTP requests.
3. Distance: 1.1138 | JavaScript adds interactive behavior and dynamic functionality to web applications.

====================================================================================================
QUERY: How can applications use computers over the internet?

KEYWORD SEARCH
1. Score: 3 | Cloud computing provides computing resources such as servers and storage over the internet.
2. Score: 1 | Python lists are ordered and mutable collections that can store multiple values.
3. Score: 1 | Java is an object-oriented programming language commonly used for enterprise applications.

SEMANTIC SEARCH
1. Distance: 0.9880 | REST APIs allow different software applications to communicate using HTTP requests.
2. Distance: 1.0402 | Web browsers send requests to servers and receive responses containing web resources.
3. Distance: 1.0473 | An operating system manages computer hardware and provides services to application programs.

====================================================================================================
QUERY: How can I protect a computer network from attacks?

KEYWORD SEARCH
1. Score: 2 | Java inheritance allows a class to acquire properties and methods from another class.
2. Score: 2 | Training a neural network involves adjusting model parameters to reduce prediction errors.
3. Score: 2 | Cybersecurity protects computer systems, networks, and data from unauthorized access.

SEMANTIC SEARCH
1. Distance: 0.9364 | Cybersecurity protects computer systems, networks, and data from unauthorized access.
2. Distance: 1.0198 | Firewalls monitor and control network traffic based on predefined security rules.
3. Distance: 1.5428 | Virtual machines allow multiple isolated computing environments to run on shared hardware.

====================================================================================================
QUERY: How do programs handle unexpected errors?

KEYWORD SEARCH
1. Score: 2 | Python exception handling allows programs to respond gracefully to runtime errors.
2. Score: 2 | Java exception handling uses try, catch, and finally blocks to handle errors.
3. Score: 1 | Training a neural network involves adjusting model parameters to reduce prediction errors.

SEMANTIC SEARCH
1. Distance: 0.5082 | Python exception handling allows programs to respond gracefully to runtime errors.
2. Distance: 0.7650 | Java exception handling uses try, catch, and finally blocks to handle errors.
3. Distance: 1.3193 | Python functions help developers organize reusable blocks of code.

====================================================================================================
QUERY: How can a computer understand images?

KEYWORD SEARCH
1. Score: 2 | Threads are smaller units of execution that can run within a process.
2. Score: 1 | Python is a popular programming language used for automation, data analysis, and artificial intelligence.
3. Score: 1 | Python lists are ordered and mutable collections that can store multiple values.

SEMANTIC SEARCH
1. Distance: 0.8488 | Convolutional neural networks are particularly effective for analyzing images.
2. Distance: 1.2930 | Deep learning uses neural networks with multiple layers to learn complex patterns.
3. Distance: 1.3315 | Artificial intelligence enables computers to perform tasks that normally require human intelligence.

====================================================================================================
QUERY: How do computers manage running programs?

KEYWORD SEARCH
1. Score: 1 | Python exception handling allows programs to respond gracefully to runtime errors.
2. Score: 1 | Artificial intelligence enables computers to perform tasks that normally require human intelligence.
3. Score: 1 | An operating system manages computer hardware and provides services to application programs.

SEMANTIC SEARCH
1. Distance: 0.7489 | Processes are programs that are currently being executed by the operating system.
2. Distance: 0.7866 | An operating system manages computer hardware and provides services to application programs.
3. Distance: 0.9788 | File systems organize and manage files stored on computer storage devices.

====================================================================================================
QUERY: How can I quickly find a specific record in a database?

KEYWORD SEARCH
1. Score: 2 | Java arrays store multiple values of the same data type in a fixed-size structure.
2. Score: 2 | Primary keys uniquely identify records within a database table.
3. Score: 2 | Transactions allow multiple database operations to be treated as a single logical unit.

SEMANTIC SEARCH
1. Distance: 1.0204 | Database indexes improve the speed of queries by providing efficient lookup structures.
2. Distance: 1.2355 | Primary keys uniquely identify records within a database table.
3. Distance: 1.2746 | Relational databases organize information into tables containing rows and columns.

====================================================================================================
QUERY: How can software automatically increase resources when demand grows?

KEYWORD SEARCH
1. Score: 5 | Cloud platforms can automatically scale resources when application demand increases.
2. Score: 1 | Python lists are ordered and mutable collections that can store multiple values.
3. Score: 1 | Overfitting occurs when a machine learning model performs well on training data but poorly on new data.

SEMANTIC SEARCH
1. Distance: 0.6095 | Cloud platforms can automatically scale resources when application demand increases.
2. Distance: 1.2749 | Load balancing distributes incoming requests across multiple servers.
3. Distance: 1.3794 | An operating system manages computer hardware and provides services to application programs.

In [18]:
analysis_results = []
for query in test_queries:
    keyword_result = keyword_search(query, corpus, top_k=1)[0]
    semantic_result = semantic_search(query, top_k=1)[0]
    analysis_results.append({
        "Query": query,
        "Keyword Score": keyword_result["score"],
        "Keyword Top Result": keyword_result["document"],
        "Semantic Distance": round(semantic_result["distance"], 4),
        "Semantic Top Result": semantic_result["document"]
    })
analysis_df = pd.DataFrame(analysis_results)
pd.set_option("display.max_colwidth", 120)
analysis_df

,Query,Keyword Score,Keyword Top Result,Semantic Distance,Semantic Top Result
0,How do computers learn patterns from examples?,3,Machine learning algorithms learn patterns from data and use them to make predictions.,0.7062,Machine learning algorithms learn patterns from data and use them to make predictions.
1,How can I store information in tables?,2,Python lists are ordered and mutable collections that can store multiple values.,0.7669,Relational databases organize information into tables containing rows and columns.
2,How do websites communicate with backend systems?,1,Deep learning uses neural networks with multiple layers to learn complex patterns.,0.6763,Web browsers send requests to servers and receive responses containing web resources.
3,How can applications use computers over the internet?,3,Cloud computing provides computing resources such as servers and storage over the internet.,0.9880,REST APIs allow different software applications to communicate using HTTP requests.
4,How can I protect a computer network from attacks?,2,Java inheritance allows a class to acquire properties and methods from another class.,0.9364,"Cybersecurity protects computer systems, networks, and data from unauthorized access."
5,How do programs handle unexpected errors?,2,Python exception handling allows programs to respond gracefully to runtime errors.,0.5082,Python exception handling allows programs to respond gracefully to runtime errors.
6,How can a computer understand images?,2,Threads are smaller units of execution that can run within a process.,0.8488,Convolutional neural networks are particularly effective for analyzing images.
7,How do computers manage running programs?,1,Python exception handling allows programs to respond gracefully to runtime errors.,0.7489,Processes are programs that are currently being executed by the operating system.
8,How can I quickly find a specific record in a database?,2,Java arrays store multiple values of the same data type in a fixed-size structure.,1.0204,Database indexes improve the speed of queries by providing efficient lookup structures.
9,How can software automatically increase resources when demand grows?,5,Cloud platforms can automatically scale resources when application demand increases.,0.6095,Cloud platforms can automatically scale resources when application demand increases.

In [19]:
for i, row in analysis_df.iterrows():
    print(f"\n{'=' * 100}")
    print(f"QUERY {i + 1}: {row['Query']}")
    print(f"\nKeyword Search (score={row['Keyword Score']})")
    print(row["Keyword Top Result"])
    print(f"\nSemantic Search (distance={row['Semantic Distance']})")
    print(row["Semantic Top Result"])

====================================================================================================
QUERY 1: How do computers learn patterns from examples?

Keyword Search (score=3)
Machine learning algorithms learn patterns from data and use them to make predictions.

Semantic Search (distance=0.7062)
Machine learning algorithms learn patterns from data and use them to make predictions.

====================================================================================================
QUERY 2: How can I store information in tables?

Keyword Search (score=2)
Python lists are ordered and mutable collections that can store multiple values.

Semantic Search (distance=0.7669)
Relational databases organize information into tables containing rows and columns.

====================================================================================================
QUERY 3: How do websites communicate with backend systems?

Keyword Search (score=1)
Deep learning uses neural networks with multiple layers to learn complex patterns.

Semantic Search (distance=0.6763)
Web browsers send requests to servers and receive responses containing web resources.

====================================================================================================
QUERY 4: How can applications use computers over the internet?

Keyword Search (score=3)
Cloud computing provides computing resources such as servers and storage over the internet.

Semantic Search (distance=0.988)
REST APIs allow different software applications to communicate using HTTP requests.

====================================================================================================
QUERY 5: How can I protect a computer network from attacks?

Keyword Search (score=2)
Java inheritance allows a class to acquire properties and methods from another class.

Semantic Search (distance=0.9364)
Cybersecurity protects computer systems, networks, and data from unauthorized access.

====================================================================================================
QUERY 6: How do programs handle unexpected errors?

Keyword Search (score=2)
Python exception handling allows programs to respond gracefully to runtime errors.

Semantic Search (distance=0.5082)
Python exception handling allows programs to respond gracefully to runtime errors.

====================================================================================================
QUERY 7: How can a computer understand images?

Keyword Search (score=2)
Threads are smaller units of execution that can run within a process.

Semantic Search (distance=0.8488)
Convolutional neural networks are particularly effective for analyzing images.

====================================================================================================
QUERY 8: How do computers manage running programs?

Keyword Search (score=1)
Python exception handling allows programs to respond gracefully to runtime errors.

Semantic Search (distance=0.7489)
Processes are programs that are currently being executed by the operating system.

====================================================================================================
QUERY 9: How can I quickly find a specific record in a database?

Keyword Search (score=2)
Java arrays store multiple values of the same data type in a fixed-size structure.

Semantic Search (distance=1.0204)
Database indexes improve the speed of queries by providing efficient lookup structures.

====================================================================================================
QUERY 10: How can software automatically increase resources when demand grows?

Keyword Search (score=5)
Cloud platforms can automatically scale resources when application demand increases.

Semantic Search (distance=0.6095)
Cloud platforms can automatically scale resources when application demand increases.

In [20]:
final_results = []
for query in test_queries:
    keyword_results = keyword_search(query, corpus, top_k=3)
    semantic_results = semantic_search(query, top_k=3)
    for rank in range(3):
        final_results.append({
            "Query": query,
            "Rank": rank + 1,
            "Keyword Score": keyword_results[rank]["score"],
            "Keyword Result": keyword_results[rank]["document"],
            "Semantic Distance": round(semantic_results[rank]["distance"], 4),
            "Semantic Result": semantic_results[rank]["document"]
        })
final_df = pd.DataFrame(final_results)
final_df

,Query,Rank,Keyword Score,Keyword Result,Semantic Distance,Semantic Result
0,How do computers learn patterns from examples?,1,3,Machine learning algorithms learn patterns from data and use them to make predictions.,0.7062,Machine learning algorithms learn patterns from data and use them to make predictions.
1,How do computers learn patterns from examples?,2,2,Deep learning uses neural networks with multiple layers to learn complex patterns.,0.8453,Deep learning uses neural networks with multiple layers to learn complex patterns.
2,How do computers learn patterns from examples?,3,1,Java inheritance allows a class to acquire properties and methods from another class.,0.9056,Unsupervised learning discovers hidden patterns in data without predefined labels.
3,How can I store information in tables?,1,2,Python lists are ordered and mutable collections that can store multiple values.,0.7669,Relational databases organize information into tables containing rows and columns.
4,How can I store information in tables?,2,2,Java arrays store multiple values of the same data type in a fixed-size structure.,1.0805,"SQL is used to retrieve, insert, update, and delete information in relational databases."
5,How can I store information in tables?,3,2,"SQL is used to retrieve, insert, update, and delete information in relational databases.",1.2565,Database normalization reduces redundant data and improves data consistency.
6,How do websites communicate with backend systems?,1,1,Deep learning uses neural networks with multiple layers to learn complex patterns.,0.6763,Web browsers send requests to servers and receive responses containing web resources.
7,How do websites communicate with backend systems?,2,1,"CSS controls the appearance, layout, and visual presentation of websites.",0.9358,REST APIs allow different software applications to communicate using HTTP requests.
8,How do websites communicate with backend systems?,3,1,REST APIs allow different software applications to communicate using HTTP requests.,1.1138,JavaScript adds interactive behavior and dynamic functionality to web applications.
9,How can applications use computers over the internet?,1,3,Cloud computing provides computing resources such as servers and storage over the internet.,0.9880,REST APIs allow different software applications to communicate using HTTP requests.
10,How can applications use computers over the internet?,2,1,Python lists are ordered and mutable collections that can store multiple values.,1.0402,Web browsers send requests to servers and receive responses containing web resources.
11,How can applications use computers over the internet?,3,1,Java is an object-oriented programming language commonly used for enterprise applications.,1.0473,An operating system manages computer hardware and provides services to application programs.
12,How can I protect a computer network from attacks?,1,2,Java inheritance allows a class to acquire properties and methods from another class.,0.9364,"Cybersecurity protects computer systems, networks, and data from unauthorized access."
13,How can I protect a computer network from attacks?,2,2,Training a neural network involves adjusting model parameters to reduce prediction errors.,1.0198,Firewalls monitor and control network traffic based on predefined security rules.
14,How can I protect a computer network from attacks?,3,2,"Cybersecurity protects computer systems, networks, and data from unauthorized access.",1.5428,Virtual machines allow multiple isolated computing environments to run on shared hardware.
15,How do programs handle unexpected errors?,1,2,Python exception handling allows programs to respond gracefully to runtime errors.,0.5082,Python exception handling allows programs to respond gracefully to runtime errors.
16,How do programs handle unexpected errors?,2,2,"Java exception handling uses try, catch, and finally blocks to handle errors.",0.7650,"Java exception handling uses try, catch, and finally blocks to handle errors."
17,How do programs handle unexpected errors?,3,1,Training a neural network involves adjusting model parameters to reduce prediction errors.,1.3193,Python functions help developers organize reusable blocks of code.
18,How can a computer understand images?,1,2,Threads are smaller units of execution that can run within a process.,0.8488,Convolutional neural networks are particularly effective for analyzing images.
19,How can a computer understand images?,2,1,"Python is a popular programming language used for automation, data analysis, and artificial intelligence.",1.2930,Deep learning uses neural networks with multiple layers to learn complex patterns.
20,How can a computer understand images?,3,1,Python lists are ordered and mutable collections that can store multiple values.,1.3315,Artificial intelligence enables computers to perform tasks that normally require human intelligence.
21,How do computers manage running programs?,1,1,Python exception handling allows programs to respond gracefully to runtime errors.,0.7489,Processes are programs that are currently being executed by the operating system.
22,How do computers manage running programs?,2,1,Artificial intelligence enables computers to perform tasks that normally require human intelligence.,0.7866,An operating system manages computer hardware and provides services to application programs.
23,How do computers manage running programs?,3,1,An operating system manages computer hardware and provides services to application programs.,0.9788,File systems organize and manage files stored on computer storage devices.
24,How can I quickly find a specific record in a database?,1,2,Java arrays store multiple values of the same data type in a fixed-size structure.,1.0204,Database indexes improve the speed of queries by providing efficient lookup structures.
25,How can I quickly find a specific record in a database?,2,2,Primary keys uniquely identify records within a database table.,1.2355,Primary keys uniquely identify records within a database table.
26,How can I quickly find a specific record in a database?,3,2,Transactions allow multiple database operations to be treated as a single logical unit.,1.2746,Relational databases organize information into tables containing rows and columns.
27,How can software automatically increase resources when demand grows?,1,5,Cloud platforms can automatically scale resources when application demand increases.,0.6095,Cloud platforms can automatically scale resources when application demand increases.
28,How can software automatically increase resources when demand grows?,2,1,Python lists are ordered and mutable collections that can store multiple values.,1.2749,Load balancing distributes incoming requests across multiple servers.
29,How can software automatically increase resources when demand grows?,3,1,Overfitting occurs when a machine learning model performs well on training data but poorly on new data.,1.3794,An operating system manages computer hardware and provides services to application programs.

In [21]:
pd.set_option("display.max_colwidth", 150)
pd.set_option("display.max_rows", 100)
final_df

,Query,Rank,Keyword Score,Keyword Result,Semantic Distance,Semantic Result
0,How do computers learn patterns from examples?,1,3,Machine learning algorithms learn patterns from data and use them to make predictions.,0.7062,Machine learning algorithms learn patterns from data and use them to make predictions.
1,How do computers learn patterns from examples?,2,2,Deep learning uses neural networks with multiple layers to learn complex patterns.,0.8453,Deep learning uses neural networks with multiple layers to learn complex patterns.
2,How do computers learn patterns from examples?,3,1,Java inheritance allows a class to acquire properties and methods from another class.,0.9056,Unsupervised learning discovers hidden patterns in data without predefined labels.
3,How can I store information in tables?,1,2,Python lists are ordered and mutable collections that can store multiple values.,0.7669,Relational databases organize information into tables containing rows and columns.
4,How can I store information in tables?,2,2,Java arrays store multiple values of the same data type in a fixed-size structure.,1.0805,"SQL is used to retrieve, insert, update, and delete information in relational databases."
5,How can I store information in tables?,3,2,"SQL is used to retrieve, insert, update, and delete information in relational databases.",1.2565,Database normalization reduces redundant data and improves data consistency.
6,How do websites communicate with backend systems?,1,1,Deep learning uses neural networks with multiple layers to learn complex patterns.,0.6763,Web browsers send requests to servers and receive responses containing web resources.
7,How do websites communicate with backend systems?,2,1,"CSS controls the appearance, layout, and visual presentation of websites.",0.9358,REST APIs allow different software applications to communicate using HTTP requests.
8,How do websites communicate with backend systems?,3,1,REST APIs allow different software applications to communicate using HTTP requests.,1.1138,JavaScript adds interactive behavior and dynamic functionality to web applications.
9,How can applications use computers over the internet?,1,3,Cloud computing provides computing resources such as servers and storage over the internet.,0.9880,REST APIs allow different software applications to communicate using HTTP requests.
10,How can applications use computers over the internet?,2,1,Python lists are ordered and mutable collections that can store multiple values.,1.0402,Web browsers send requests to servers and receive responses containing web resources.
11,How can applications use computers over the internet?,3,1,Java is an object-oriented programming language commonly used for enterprise applications.,1.0473,An operating system manages computer hardware and provides services to application programs.
12,How can I protect a computer network from attacks?,1,2,Java inheritance allows a class to acquire properties and methods from another class.,0.9364,"Cybersecurity protects computer systems, networks, and data from unauthorized access."
13,How can I protect a computer network from attacks?,2,2,Training a neural network involves adjusting model parameters to reduce prediction errors.,1.0198,Firewalls monitor and control network traffic based on predefined security rules.
14,How can I protect a computer network from attacks?,3,2,"Cybersecurity protects computer systems, networks, and data from unauthorized access.",1.5428,Virtual machines allow multiple isolated computing environments to run on shared hardware.
15,How do programs handle unexpected errors?,1,2,Python exception handling allows programs to respond gracefully to runtime errors.,0.5082,Python exception handling allows programs to respond gracefully to runtime errors.
16,How do programs handle unexpected errors?,2,2,"Java exception handling uses try, catch, and finally blocks to handle errors.",0.7650,"Java exception handling uses try, catch, and finally blocks to handle errors."
17,How do programs handle unexpected errors?,3,1,Training a neural network involves adjusting model parameters to reduce prediction errors.,1.3193,Python functions help developers organize reusable blocks of code.
18,How can a computer understand images?,1,2,Threads are smaller units of execution that can run within a process.,0.8488,Convolutional neural networks are particularly effective for analyzing images.
19,How can a computer understand images?,2,1,"Python is a popular programming language used for automation, data analysis, and artificial intelligence.",1.2930,Deep learning uses neural networks with multiple layers to learn complex patterns.
20,How can a computer understand images?,3,1,Python lists are ordered and mutable collections that can store multiple values.,1.3315,Artificial intelligence enables computers to perform tasks that normally require human intelligence.
21,How do computers manage running programs?,1,1,Python exception handling allows programs to respond gracefully to runtime errors.,0.7489,Processes are programs that are currently being executed by the operating system.
22,How do computers manage running programs?,2,1,Artificial intelligence enables computers to perform tasks that normally require human intelligence.,0.7866,An operating system manages computer hardware and provides services to application programs.
23,How do computers manage running programs?,3,1,An operating system manages computer hardware and provides services to application programs.,0.9788,File systems organize and manage files stored on computer storage devices.
24,How can I quickly find a specific record in a database?,1,2,Java arrays store multiple values of the same data type in a fixed-size structure.,1.0204,Database indexes improve the speed of queries by providing efficient lookup structures.
25,How can I quickly find a specific record in a database?,2,2,Primary keys uniquely identify records within a database table.,1.2355,Primary keys uniquely identify records within a database table.
26,How can I quickly find a specific record in a database?,3,2,Transactions allow multiple database operations to be treated as a single logical unit.,1.2746,Relational databases organize information into tables containing rows and columns.
27,How can software automatically increase resources when demand grows?,1,5,Cloud platforms can automatically scale resources when application demand increases.,0.6095,Cloud platforms can automatically scale resources when application demand increases.
28,How can software automatically increase resources when demand grows?,2,1,Python lists are ordered and mutable collections that can store multiple values.,1.2749,Load balancing distributes incoming requests across multiple servers.
29,How can software automatically increase resources when demand grows?,3,1,Overfitting occurs when a machine learning model performs well on training data but poorly on new data.,1.3794,An operating system manages computer hardware and provides services to application programs.