<a href="https://colab.research.google.com/github/Chikka-Pradhayani/ABTalks-60-Days-AI-Challenge/blob/main/Day-20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q langchain-text-splitters

In [2]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

print("Text splitter imported successfully!")

Text splitter imported successfully!

In [3]:
documents = [
    {
        "id": "doc_1",
        "title": "Artificial Intelligence",
        "content": """
Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.
"""
    },
    {
        "id": "doc_2",
        "title": "Machine Learning",
        "content": """
Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.
"""
    },
    {
        "id": "doc_3",
        "title": "Retrieval Augmented Generation",
        "content": """
Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.
"""
    }
]

print("Number of documents:", len(documents))

Number of documents: 3

In [4]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

chunks = []

for doc in documents:
    doc_chunks = text_splitter.split_text(doc["content"])

    for i, chunk in enumerate(doc_chunks):
        chunks.append({
            "id": f'{doc["id"]}_chunk_{i}',
            "title": doc["title"],
            "content": chunk
        })

print("Total chunks:", len(chunks))

Total chunks: 3

In [5]:
for chunk in chunks:
    print("ID:", chunk["id"])
    print("Title:", chunk["title"])
    print("Content:", chunk["content"])
    print("-" * 60)

ID: doc_1_chunk_0
Title: Artificial Intelligence
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.
------------------------------------------------------------
ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.
------------------------------------------------------------
ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.
------------------------------------------------------------

In [6]:
for chunk in chunks:
    print(chunk.keys())

dict_keys(['id', 'title', 'content'])
dict_keys(['id', 'title', 'content'])
dict_keys(['id', 'title', 'content'])

In [7]:
print("Total chunks:", len(chunks))

Total chunks: 3

In [8]:
!pip install -q langchain-openai langchain-community faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.1/125.1 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 46.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 49.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 45.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [9]:
from langchain_openai import OpenAIEmbeddings
from langchain_community.vectorstores import FAISS

print("FAISS and OpenAI imports successful!")

FAISS and OpenAI imports successful!

/tmp/ipykernel_4175/4056880854.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.vectorstores import FAISS

In [10]:
from langchain_core.documents import Document

langchain_documents = [
    Document(
        page_content=chunk["content"],
        metadata={
            "id": chunk["id"],
            "title": chunk["title"]
        }
    )
    for chunk in chunks
]

print("Documents created:", len(langchain_documents))

Documents created: 3

In [11]:
print(langchain_documents[0])

page_content='Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.' metadata={'id': 'doc_1_chunk_0', 'title': 'Artificial Intelligence'}

In [13]:
!pip install -q sentence-transformers langchain-huggingface faiss-cpu

In [14]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = FAISS.from_documents(
    langchain_documents,
    embeddings
)

print("FAISS vector store created successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

FAISS vector store created successfully!

In [15]:
query = "What is artificial intelligence?"

results = vectorstore.similarity_search_with_score(
    query,
    k=3
)

for doc, score in results:
    print("ID:", doc.metadata["id"])
    print("Title:", doc.metadata["title"])
    print("Score:", score)
    print("Content:", doc.page_content)
    print("-" * 60)

ID: doc_1_chunk_0
Title: Artificial Intelligence
Score: 0.28134158
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.
------------------------------------------------------------
ID: doc_2_chunk_0
Title: Machine Learning
Score: 0.77575046
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.
------------------------------------------------------------
ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Score: 1.603342
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.
------------------------------------------------------------

In [16]:
query = "What is artificial intelligence?"

results = vectorstore.similarity_search_with_score(
    query,
    k=3
)

for doc, score in results:
    print("ID:", doc.metadata["id"])
    print("Title:", doc.metadata["title"])
    print("Score:", score)
    print("Content:", doc.page_content)
    print("-" * 60)

ID: doc_1_chunk_0
Title: Artificial Intelligence
Score: 0.28134158
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.
------------------------------------------------------------
ID: doc_2_chunk_0
Title: Machine Learning
Score: 0.77575046
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.
------------------------------------------------------------
ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Score: 1.603342
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.
------------------------------------------------------------

In [17]:
def retrieve_documents(query, top_k=3):
    results = vectorstore.similarity_search_with_score(
        query,
        k=top_k
    )

    retrieved_docs = []

    for doc, score in results:
        retrieved_docs.append({
            "id": doc.metadata["id"],
            "title": doc.metadata["title"],
            "content": doc.page_content,
            "score": float(score)
        })

    return retrieved_docs

In [18]:
query = "What is machine learning?"

retrieved_docs = retrieve_documents(query)

for doc in retrieved_docs:
    print("ID:", doc["id"])
    print("Title:", doc["title"])
    print("Score:", doc["score"])
    print()

ID: doc_2_chunk_0
Title: Machine Learning
Score: 0.3562297224998474

ID: doc_1_chunk_0
Title: Artificial Intelligence
Score: 0.937087893486023

ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Score: 1.528681755065918

In [19]:
metadata={
    "id": chunk["id"],
    "title": chunk["title"]
}

In [20]:
def filter_documents_by_title(title):
    filtered_docs = [
        doc for doc in langchain_documents
        if doc.metadata["title"].lower() == title.lower()
    ]

    return filtered_docs

In [21]:
filtered_docs = filter_documents_by_title("Machine Learning")

print("Filtered documents:", len(filtered_docs))

for doc in filtered_docs:
    print("ID:", doc.metadata["id"])
    print("Title:", doc.metadata["title"])
    print("Content:", doc.page_content)
    print("-" * 60)

Filtered documents: 1
ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.
------------------------------------------------------------

In [22]:
def retrieve_documents(query, top_k=3, title_filter=None):

    # Start with all documents
    documents_to_search = langchain_documents

    # Apply metadata filter if provided
    if title_filter:
        documents_to_search = [
            doc for doc in langchain_documents
            if doc.metadata["title"].lower() == title_filter.lower()
        ]

    # Create a temporary FAISS index using filtered documents
    filtered_vectorstore = FAISS.from_documents(
        documents_to_search,
        embeddings
    )

    # Semantic search
    results = filtered_vectorstore.similarity_search_with_score(
        query,
        k=min(top_k, len(documents_to_search))
    )

    retrieved_docs = []

    for doc, score in results:
        retrieved_docs.append({
            "id": doc.metadata["id"],
            "title": doc.metadata["title"],
            "content": doc.page_content,
            "score": float(score)
        })

    return retrieved_docs

In [23]:
results = retrieve_documents(
    "What is machine learning?"
)

for doc in results:
    print(doc["title"], "|", doc["score"])

Machine Learning | 0.3562297224998474
Artificial Intelligence | 0.937087893486023
Retrieval Augmented Generation | 1.528681755065918

In [24]:
results = retrieve_documents(
    "What is machine learning?",
    title_filter="Machine Learning"
)

for doc in results:
    print(doc["title"], "|", doc["score"])

Machine Learning | 0.35622966289520264

In [25]:
GROUNDING_PROMPT = """
You are a knowledge assistant.

Answer the user's question using ONLY the information provided
in the retrieved context.

Rules:
1. Do not use outside knowledge.
2. Do not invent or assume information.
3. If the answer is not present in the context, clearly say:
   "I don't have enough information in the provided knowledge base."
4. Keep the answer concise and accurate.
5. Always mention the source IDs used for the answer.

Retrieved Context:
{context}

User Question:
{query}

Answer:
"""

In [26]:
query = "What is machine learning?"

retrieved_docs = retrieve_documents(query)

context = "\n\n".join(
    f"Source ID: {doc['id']}\n"
    f"Title: {doc['title']}\n"
    f"Content: {doc['content']}"
    for doc in retrieved_docs
)

prompt = GROUNDING_PROMPT.format(
    context=context,
    query=query
)

print(prompt)

You are a knowledge assistant.

Answer the user's question using ONLY the information provided
in the retrieved context.

Rules:
1. Do not use outside knowledge.
2. Do not invent or assume information.
3. If the answer is not present in the context, clearly say:
   "I don't have enough information in the provided knowledge base."
4. Keep the answer concise and accurate.
5. Always mention the source IDs used for the answer.

Retrieved Context:
Source ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.

Source ID: doc_1_chunk_0
Title: Artificial Intelligence
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.

Source ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.

User Question:
What is machine learning?

Answer:

In [27]:
def run_rag(query, top_k=3, title_filter=None):

    # 1. Retrieve relevant documents
    retrieved_docs = retrieve_documents(
        query=query,
        top_k=top_k,
        title_filter=title_filter
    )

    # 2. Create context from retrieved documents
    context = "\n\n".join(
        f"Source ID: {doc['id']}\n"
        f"Title: {doc['title']}\n"
        f"Content: {doc['content']}"
        for doc in retrieved_docs
    )

    # 3. Create grounded prompt
    prompt = GROUNDING_PROMPT.format(
        context=context,
        query=query
    )

    # 4. Collect source IDs
    sources = [
        doc["id"]
        for doc in retrieved_docs
    ]

    return {
        "query": query,
        "prompt": prompt,
        "sources": sources,
        "retrieved_documents": retrieved_docs
    }

In [28]:
result = run_rag(
    "What is machine learning?"
)

print("SOURCES:")
print(result["sources"])

print("\nPROMPT:")
print(result["prompt"])

SOURCES:
['doc_2_chunk_0', 'doc_1_chunk_0', 'doc_3_chunk_0']

PROMPT:

You are a knowledge assistant.

Answer the user's question using ONLY the information provided
in the retrieved context.

Rules:
1. Do not use outside knowledge.
2. Do not invent or assume information.
3. If the answer is not present in the context, clearly say:
   "I don't have enough information in the provided knowledge base."
4. Keep the answer concise and accurate.
5. Always mention the source IDs used for the answer.

Retrieved Context:
Source ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.

Source ID: doc_1_chunk_0
Title: Artificial Intelligence
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.

Source ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.

User Question:
What is machine learning?

Answer:

In [29]:
!pip install -q transformers sentencepiece torch

In [30]:
from transformers import pipeline

print("Transformers imported successfully!")

Transformers imported successfully!

In [31]:
from transformers import pipeline

print("Transformers imported successfully!")

Transformers imported successfully!

In [32]:
generator = pipeline(
    "text-generation",
    model="google/flan-t5-small"
)

print("Local LLM loaded successfully!")

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  308MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

[transformers] The model 'T5ForConditionalGeneration' is not supported for text-generation. Supported models are ['PeftModelForCausalLM', 'AfmoeForCausalLM', 'ApertusForCausalLM', 'ArceeForCausalLM', 'AriaTextForCausalLM', 'AXK1ForCausalLM', 'AXK2ForCausalLM', 'BambaForCausalLM', 'BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BitNetForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'BltForCausalLM', 'CamembertForCausalLM', 'CodeGenForCausalLM', 'CohereForCausalLM', 'Cohere2ForCausalLM', 'Cohere2MoeForCausalLM', 'CohereCompassForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'CwmForCausalLM', 'Data2VecTextForCausalLM', 'DbrxForCausalLM', 'DeepseekV2ForCausalLM', 'DeepseekV3ForCausalLM', 'DeepseekV32ForCausalLM', 'DeepseekV4ForCausalLM', 'DiffLlamaForCausalLM', 'DogeForCausalLM', 'Dots1ForCausalLM', 'ElectraForCausalLM', 'Emu3ForCausalLM', 'ErnieForCausalLM', 'Ernie4_5ForCausalLM', 'Ernie4_5_MoeForCausalLM', 'Exaone4ForCausalLM', 'ExaoneMoeForCausalLM', 'FalconForCausalLM', 'FalconH1ForCausalLM', 'FalconMambaForCausalLM', 'FlexOlmoForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'Gemma3ForConditionalGeneration', 'Gemma3ForCausalLM', 'Gemma3nForConditionalGeneration', 'Gemma3nForCausalLM', 'Gemma4ForConditionalGeneration', 'Gemma4AssistantForCausalLM', 'Gemma4ForCausalLM', 'Gemma4UnifiedForConditionalGeneration', 'Gemma4UnifiedAssistantForCausalLM', 'Gemma4UnifiedForCausalLM', 'GitForCausalLM', 'GlmForCausalLM', 'Glm4ForCausalLM', 'Glm4MoeForCausalLM', 'Glm4MoeLiteForCausalLM', 'GlmMoeDsaForCausalLM', 'GotOcr2ForConditionalGeneration', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GptOssForCausalLM', 'GPTJForCausalLM', 'GraniteForCausalLM', 'GraniteSWAForCausalLM', 'GraniteMoeForCausalLM', 'GraniteMoeSWAForCausalLM', 'GraniteMoeHybridForCausalLM', 'GraniteMoeSharedForCausalLM', 'HeliumForCausalLM', 'HrmTextForCausalLM', 'HunYuanDenseV1ForCausalLM', 'HunYuanMoEV1ForCausalLM', 'HYV3ForCausalLM', 'HyperCLOVAXForCausalLM', 'InklingForCausalLM', 'Jais2ForCausalLM', 'JambaForCausalLM', 'JetMoeForCausalLM', 'LagunaForCausalLM', 'Lfm2ForCausalLM', 'Lfm2MoeForCausalLM', 'LlamaForCausalLM', 'Llama4ForCausalLM', 'Llama4ForCausalLM', 'LongcatFlashForCausalLM', 'MambaForCausalLM', 'Mamba2ForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegatronBertForCausalLM', 'MellumForCausalLM', 'MiMoV2FlashForCausalLM', 'MiniCPM3ForCausalLM', 'MiniMaxForCausalLM', 'MiniMaxM2ForCausalLM', 'MiniMaxM3VLForCausalLM', 'MinistralForCausalLM', 'Ministral3ForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MllamaForCausalLM', 'ModernBertDecoderForCausalLM', 'MoshiForCausalLM', 'MptForCausalLM', 'MusicgenForCausalLM', 'MusicgenMelodyForCausalLM', 'MvpForCausalLM', 'NanoChatForCausalLM', 'NemotronForCausalLM', 'NemotronHForCausalLM', 'OlmoForCausalLM', 'Olmo2ForCausalLM', 'Olmo3ForCausalLM', 'OlmoHybridForCausalLM', 'OlmoeForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi4MultimodalForCausalLM', 'PhimoeForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'Qwen3ForCausalLM', 'Qwen3_5ForCausalLM', 'Qwen3_5MoeForCausalLM', 'Qwen3_5MoeForCausalLM', 'Qwen3_5ForCausalLM', 'Qwen3MoeForCausalLM', 'Qwen3NextForCausalLM', 'Qwen4ExpForCausalLM', 'Qwen4ExpForCausalLM', 'RecurrentGemmaForCausalLM', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'SeedOssForCausalLM', 'SmolLM3ForCausalLM', 'SolarOpenForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'TrOCRForCausalLM', 'VaultGemmaForCausalLM', 'WhisperForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'xLSTMForCausalLM', 'XmodForCausalLM', 'YoutuForCausalLM', 'ZambaForCausalLM', 'Zamba2ForCausalLM', 'ZayaForCausalLM'].

Local LLM loaded successfully!

In [33]:
def generate_answer(prompt):
    result = generator(
        prompt,
        max_new_tokens=150,
        do_sample=False
    )

    answer = result[0]["generated_text"]

    return answer.strip()

In [34]:
answer = generate_answer(
    result["prompt"]
)

print("ANSWER:")
print(answer)

[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
You are a knowledge assistant.

Answer the user's question using ONLY the information provided
in the retrieved context.

Rules:
1. Do not use outside knowledge.
2. Do not invent or assume information.
3. If the answer is not present in the context, clearly say:
   "I don't have enough information in the provided knowledge base."
4. Keep the answer concise and accurate.
5. Always mention the source IDs used for the answer.

Retrieved Context:
Source ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.

Source ID: doc_1_chunk_0
Title: Artificial Intelligence
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.

Source ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.

User Question:
What is machine learning?

Answer:

In [35]:
def run_rag(query, top_k=3, title_filter=None):

    # 1. Retrieve relevant documents
    retrieved_docs = retrieve_documents(
        query=query,
        top_k=top_k,
        title_filter=title_filter
    )

    # 2. Create context
    context = "\n\n".join(
        f"Source ID: {doc['id']}\n"
        f"Title: {doc['title']}\n"
        f"Content: {doc['content']}"
        for doc in retrieved_docs
    )

    # 3. Create grounded prompt
    prompt = GROUNDING_PROMPT.format(
        context=context,
        query=query
    )

    # 4. Generate answer
    answer = generate_answer(prompt)

    # 5. Collect source IDs
    sources = [
        doc["id"]
        for doc in retrieved_docs
    ]

    return {
        "answer": answer,
        "sources": sources
    }

In [36]:
result = run_rag(
    "What is machine learning?"
)

print("ANSWER:")
print(result["answer"])

print("\nSOURCES:")
print(result["sources"])

[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
You are a knowledge assistant.

Answer the user's question using ONLY the information provided
in the retrieved context.

Rules:
1. Do not use outside knowledge.
2. Do not invent or assume information.
3. If the answer is not present in the context, clearly say:
   "I don't have enough information in the provided knowledge base."
4. Keep the answer concise and accurate.
5. Always mention the source IDs used for the answer.

Retrieved Context:
Source ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.

Source ID: doc_1_chunk_0
Title: Artificial Intelligence
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.

Source ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.

User Question:
What is machine learning?

Answer:

SOURCES:
['doc_2_chunk_0', 'doc_1_chunk_0', 'doc_3_chunk_0']

In [37]:
def run_rag(query, top_k=3, title_filter=None):

    # 1. Retrieve relevant documents
    retrieved_docs = retrieve_documents(
        query=query,
        top_k=top_k,
        title_filter=title_filter
    )

    # 2. Create context
    context = "\n\n".join(
        f"Source ID: {doc['id']}\n"
        f"Title: {doc['title']}\n"
        f"Content: {doc['content']}"
        for doc in retrieved_docs
    )

    # 3. Create grounded prompt
    prompt = GROUNDING_PROMPT.format(
        context=context,
        query=query
    )

    # 4. Generate answer
    answer = generate_answer(prompt)

    # 5. Collect source IDs
    sources = [doc["id"] for doc in retrieved_docs]

    # 6. Add source citation to answer
    citation = "\n\nSources: " + ", ".join(sources)

    answer_with_sources = answer + citation

    return {
        "answer": answer_with_sources,
        "sources": sources
    }

In [38]:
result = run_rag("What is machine learning?")

print(result["answer"])
print("\nSources list:")
print(result["sources"])

[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are a knowledge assistant.

Answer the user's question using ONLY the information provided
in the retrieved context.

Rules:
1. Do not use outside knowledge.
2. Do not invent or assume information.
3. If the answer is not present in the context, clearly say:
   "I don't have enough information in the provided knowledge base."
4. Keep the answer concise and accurate.
5. Always mention the source IDs used for the answer.

Retrieved Context:
Source ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.

Source ID: doc_1_chunk_0
Title: Artificial Intelligence
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.

Source ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.

User Question:
What is machine learning?

Answer:

Sources: doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0

Sources list:
['doc_2_chunk_0', 'doc_1_chunk_0', 'doc_3_chunk_0']

In [40]:
similarities = [
    1 / (1 + doc["score"])
    for doc in retrieved_docs
]

highest_similarity = max(similarities) if similarities else 0

In [42]:
def run_rag(query, top_k=3, title_filter=None):

    # 1. Retrieve relevant documents
    retrieved_docs = retrieve_documents(
        query=query,
        top_k=top_k,
        title_filter=title_filter
    )

    # 2. Create context
    context = "\n\n".join(
        f"Source ID: {doc['id']}\n"
        f"Title: {doc['title']}\n"
        f"Content: {doc['content']}"
        for doc in retrieved_docs
    )

    # 3. Create grounded prompt
    prompt = GROUNDING_PROMPT.format(
        context=context,
        query=query
    )

    # 4. Generate answer
    answer = generate_answer(prompt)

    # 5. Convert FAISS distance into similarity
    similarities = [
        1 / (1 + doc["score"])
        for doc in retrieved_docs
    ]

    # 6. Find highest similarity
    highest_similarity = max(similarities) if similarities else 0

    # 7. Collect source IDs
    sources = [
        doc["id"]
        for doc in retrieved_docs
    ]

    # 8. Add source citation
    answer += "\n\nSources: " + ", ".join(sources)

    # 9. Add confidence warning
    if highest_similarity < 0.3:
        answer += (
            "\n\nLow confidence: "
            "The retrieved information may not provide strong "
            "support for this answer."
        )

    # 10. Return complete result
    return {
        "answer": answer,
        "sources": sources,
        "confidence": highest_similarity
    }

In [43]:
result = run_rag("What is machine learning?")

print("ANSWER:")
print(result["answer"])

print("\nSOURCES:")
print(result["sources"])

print("\nCONFIDENCE:")
print(result["confidence"])

[transformers] Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
You are a knowledge assistant.

Answer the user's question using ONLY the information provided
in the retrieved context.

Rules:
1. Do not use outside knowledge.
2. Do not invent or assume information.
3. If the answer is not present in the context, clearly say:
   "I don't have enough information in the provided knowledge base."
4. Keep the answer concise and accurate.
5. Always mention the source IDs used for the answer.

Retrieved Context:
Source ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence. It allows
computers to learn patterns from data and make predictions or decisions
without being explicitly programmed for every task. Common approaches
include supervised learning, unsupervised learning, and reinforcement
learning.

Source ID: doc_1_chunk_0
Title: Artificial Intelligence
Content: Artificial Intelligence is a field of computer science that focuses on
creating systems capable of performing tasks that normally require human
intelligence. These tasks include learning, reasoning, problem solving,
understanding language, and recognizing patterns.

Source ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Content: Retrieval Augmented Generation, commonly called RAG, combines information
retrieval with language generation. A RAG system first retrieves relevant
information from a knowledge base and then provides that information to
a language model so that it can generate a grounded answer.

User Question:
What is machine learning?

Answer:

Sources: doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0

SOURCES:
['doc_2_chunk_0', 'doc_1_chunk_0', 'doc_3_chunk_0']

CONFIDENCE:
0.7373382129959274

In [44]:
!pip install -q fastapi uvicorn

In [45]:
from fastapi import FastAPI
from pydantic import BaseModel

print("FastAPI imported successfully!")

FastAPI imported successfully!

In [46]:
app = FastAPI(
    title="AI Knowledge Assistant",
    description="RAG-based knowledge assistant with source citations",
    version="1.0.0"
)

print("FastAPI app created successfully!")

FastAPI app created successfully!

In [47]:
{
  "query": "What is machine learning?"
}

{'query': 'What is machine learning?'}

In [48]:
class AskRequest(BaseModel):
    query: str

print("Request model created successfully!")

Request model created successfully!

In [49]:
@app.post("/ask")
def ask(request: AskRequest):
    result = run_rag(request.query)

    return {
        "answer": result["answer"],
        "sources": result["sources"],
        "confidence": result["confidence"]
    }

In [50]:
{
  "query": "What is machine learning?"
}

{'query': 'What is machine learning?'}

In [51]:
{
  "answer": "Machine learning is ... Sources: doc_2_chunk_0",
  "sources": ["doc_2_chunk_0"],
  "confidence": 0.65
}

{'answer': 'Machine learning is ... Sources: doc_2_chunk_0',
 'sources': ['doc_2_chunk_0'],
 'confidence': 0.65}

In [52]:
@app.get("/")
def home():
    return {
        "message": "AI Knowledge Assistant API is running"
    }

In [53]:
print("Root endpoint created successfully!")

Root endpoint created successfully!

In [54]:
%%writefile app.py

from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(
    title="AI Knowledge Assistant",
    description="RAG-based knowledge assistant with source citations",
    version="1.0.0"
)

class AskRequest(BaseModel):
    query: str

@app.get("/")
def home():
    return {
        "message": "AI Knowledge Assistant API is running"
    }

@app.post("/ask")
def ask(request: AskRequest):
    result = run_rag(request.query)

    return {
        "answer": result["answer"],
        "sources": result["sources"],
        "confidence": result["confidence"]
    }

Writing app.py

In [55]:
%%writefile rag_pipeline.py

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from transformers import pipeline


print("RAG pipeline imports loaded")

Writing rag_pipeline.py

In [56]:
import os

print(os.path.exists("rag_pipeline.py"))

True

In [57]:
%%writefile rag_pipeline.py

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from transformers import pipeline

print("RAG pipeline imports loaded successfully!")

Overwriting rag_pipeline.py

In [58]:
import os

print("rag_pipeline.py exists:", os.path.exists("rag_pipeline.py"))

rag_pipeline.py exists: True

In [61]:
!pip install -q --upgrade transformers

In [64]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="distilgpt2"
)

print("Local LLM loaded successfully!")

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  353MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Local LLM loaded successfully!

In [65]:
result = generator(
    "Machine learning is",
    max_new_tokens=50,
    do_sample=False
)

print(result[0]["generated_text"])

[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Machine learning is a new way to learn about the world.

In [66]:
%%writefile rag_pipeline.py

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from transformers import pipeline


# 1. Knowledge Base

documents = [
    {
        "id": "doc_1",
        "title": "Artificial Intelligence",
        "content": (
            "Artificial Intelligence is the field of computer science "
            "that focuses on creating systems capable of performing "
            "tasks that normally require human intelligence."
        )
    },
    {
        "id": "doc_2",
        "title": "Machine Learning",
        "content": (
            "Machine Learning is a subset of Artificial Intelligence "
            "that enables computers to learn patterns from data and "
            "make predictions or decisions without being explicitly programmed."
        )
    },
    {
        "id": "doc_3",
        "title": "Retrieval Augmented Generation",
        "content": (
            "Retrieval Augmented Generation, or RAG, combines information "
            "retrieval with language generation. Relevant documents are "
            "retrieved first and then provided to a language model as context."
        )
    }
]


# 2. Chunking

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

chunks = []

for doc in documents:
    doc_chunks = text_splitter.split_text(doc["content"])

    for i, chunk in enumerate(doc_chunks):
        chunks.append({
            "id": f'{doc["id"]}_chunk_{i}',
            "title": doc["title"],
            "content": chunk
        })


# 3. LangChain Documents

langchain_documents = [
    Document(
        page_content=chunk["content"],
        metadata={
            "id": chunk["id"],
            "title": chunk["title"]
        }
    )
    for chunk in chunks
]


# 4. Embeddings

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)


# 5. FAISS

vectorstore = FAISS.from_documents(
    langchain_documents,
    embeddings
)


# 6. Retrieval

def retrieve_documents(query, top_k=3, title_filter=None):

    documents_to_search = langchain_documents

    if title_filter:
        documents_to_search = [
            doc
            for doc in langchain_documents
            if doc.metadata["title"].lower() == title_filter.lower()
        ]

    if not documents_to_search:
        return []

    filtered_vectorstore = FAISS.from_documents(
        documents_to_search,
        embeddings
    )

    results = filtered_vectorstore.similarity_search_with_score(
        query,
        k=min(top_k, len(documents_to_search))
    )

    retrieved_docs = []

    for doc, score in results:
        retrieved_docs.append({
            "id": doc.metadata["id"],
            "title": doc.metadata["title"],
            "content": doc.page_content,
            "score": float(score)
        })

    return retrieved_docs


# 7. Grounding Prompt

GROUNDING_PROMPT = """
Answer the question using ONLY the retrieved context.

Retrieved Context:
{context}

Question:
{query}

Answer:
"""


# 8. Local LLM

generator = pipeline(
    "text-generation",
    model="distilgpt2"
)


# 9. Generate Answer

def generate_answer(prompt):

    result = generator(
        prompt,
        max_new_tokens=100,
        do_sample=False
    )

    generated_text = result[0]["generated_text"]

    return generated_text.strip()


# 10. Complete RAG Pipeline

def run_rag(query, top_k=3, title_filter=None):

    retrieved_docs = retrieve_documents(
        query=query,
        top_k=top_k,
        title_filter=title_filter
    )

    if not retrieved_docs:
        return {
            "answer": "I don't have enough information in the provided knowledge base.",
            "sources": [],
            "confidence": 0.0
        }

    context = "\n\n".join(
        f"Source ID: {doc['id']}\n"
        f"Title: {doc['title']}\n"
        f"Content: {doc['content']}"
        for doc in retrieved_docs
    )

    prompt = GROUNDING_PROMPT.format(
        context=context,
        query=query
    )

    answer = generate_answer(prompt)

    similarities = [
        1 / (1 + doc["score"])
        for doc in retrieved_docs
    ]

    highest_similarity = max(similarities)

    sources = [
        doc["id"]
        for doc in retrieved_docs
    ]

    answer += "\n\nSources: " + ", ".join(sources)

    if highest_similarity < 0.3:
        answer += (
            "\n\nLow confidence: "
            "The retrieved information may not provide strong "
            "support for this answer."
        )

    return {
        "answer": answer,
        "sources": sources,
        "confidence": highest_similarity
    }


print("RAG pipeline created successfully!")

Overwriting rag_pipeline.py

In [67]:
from rag_pipeline import run_rag

result = run_rag("What is machine learning?")

print("ANSWER:")
print(result["answer"])

print("\nSOURCES:")
print(result["sources"])

print("\nCONFIDENCE:")
print(result["confidence"])

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

RAG pipeline created successfully!

[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ANSWER:
Answer the question using ONLY the retrieved context.

Retrieved Context:
Source ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed.

Source ID: doc_1_chunk_0
Title: Artificial Intelligence
Content: Artificial Intelligence is the field of computer science that focuses on creating systems capable of performing tasks that normally require human intelligence.

Source ID: doc_3_chunk_0
Title: Retrieval Augmented Generation
Content: Retrieval Augmented Generation, or RAG, combines information retrieval with language generation. Relevant documents are retrieved first and then provided to a language model as context.

Question:
What is machine learning?

Answer:
Source ID: doc_2_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed.
Source ID: doc_3_chunk_0
Title: Machine Learning
Content: Machine Learning is a subset of Artificial Intelligence that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed.
Source ID: doc_3_ch

Sources: doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0

SOURCES:
['doc_2_chunk_0', 'doc_1_chunk_0', 'doc_3_chunk_0']

CONFIDENCE:
0.7680550176129178

In [68]:
from rag_pipeline import run_rag

In [72]:
!uvicorn app:app --host 127.0.0.1 --port 8000 &

INFO:     Started server process [14895]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14895]

In [74]:
!pkill -f "uvicorn"

In [75]:
import subprocess

server = subprocess.Popen(
    ["uvicorn", "app:app", "--host", "127.0.0.1", "--port", "8000"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print("FastAPI server started.")

FastAPI server started.

In [80]:
import requests

response = requests.post(
    "http://127.0.0.1:8000/ask",
    json={
        "query": "What is machine learning?"
    }
)

print("Status Code:", response.status_code)
print("Response Text:")
print(response.text)

Status Code: 500
Response Text:
Internal Server Error

In [81]:
server = subprocess.Popen(
    ["uvicorn", "app:app", "--host", "127.0.0.1", "--port", "8000"]
)

In [82]:
import requests

response = requests.post(
    "http://127.0.0.1:8000/ask",
    json={"query": "What is machine learning?"}
)

print("Status Code:", response.status_code)
print("Response:")
print(response.text)

Status Code: 500
Response:
Internal Server Error

In [83]:
from rag_pipeline import run_rag

result = run_rag("What is machine learning?")

print(result)

[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

{'answer': 'Answer the question using ONLY the retrieved context.\n\nRetrieved Context:\nSource ID: doc_2_chunk_0\nTitle: Machine Learning\nContent: Machine Learning is a subset of Artificial Intelligence that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed.\n\nSource ID: doc_1_chunk_0\nTitle: Artificial Intelligence\nContent: Artificial Intelligence is the field of computer science that focuses on creating systems capable of performing tasks that normally require human intelligence.\n\nSource ID: doc_3_chunk_0\nTitle: Retrieval Augmented Generation\nContent: Retrieval Augmented Generation, or RAG, combines information retrieval with language generation. Relevant documents are retrieved first and then provided to a language model as context.\n\nQuestion:\nWhat is machine learning?\n\nAnswer:\nSource ID: doc_2_chunk_0\nTitle: Machine Learning\nContent: Machine Learning is a subset of Artificial Intelligence that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed.\nSource ID: doc_3_chunk_0\nTitle: Machine Learning\nContent: Machine Learning is a subset of Artificial Intelligence that enables computers to learn patterns from data and make predictions or decisions without being explicitly programmed.\nSource ID: doc_3_ch\n\nSources: doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0', 'sources': ['doc_2_chunk_0', 'doc_1_chunk_0', 'doc_3_chunk_0'], 'confidence': 0.7680550176129178}

In [84]:
server.terminate()
print("Server stopped")

Server stopped

In [85]:
import subprocess
import time

server = subprocess.Popen(
    ["uvicorn", "app:app", "--host", "127.0.0.1", "--port", "8000"]
)

time.sleep(3)

print("FastAPI server started")

FastAPI server started

In [86]:
import requests

response = requests.get("http://127.0.0.1:8000/")

print("Status Code:", response.status_code)
print("Response:", response.text)

Status Code: 200
Response: {"message":"AI Knowledge Assistant API is running"}

In [87]:
import requests

response = requests.post(
    "http://127.0.0.1:8000/ask",
    json={
        "query": "What is machine learning?"
    }
)

print("Status Code:", response.status_code)
print("Response:")

if response.status_code == 200:
    print(response.json())
else:
    print(response.text)

Status Code: 500
Response:
Internal Server Error

In [88]:
test_queries = [
    # Easy
    {
        "query": "What is artificial intelligence?",
        "difficulty": "Easy"
    },
    {
        "query": "What is machine learning?",
        "difficulty": "Easy"
    },
    {
        "query": "What is RAG?",
        "difficulty": "Easy"
    },
    {
        "query": "What does AI focus on?",
        "difficulty": "Easy"
    },
    {
        "query": "What does machine learning learn from?",
        "difficulty": "Easy"
    },

    # Medium
    {
        "query": "How is machine learning related to artificial intelligence?",
        "difficulty": "Medium"
    },
    {
        "query": "How does RAG combine retrieval and generation?",
        "difficulty": "Medium"
    },
    {
        "query": "What is the purpose of retrieving documents in RAG?",
        "difficulty": "Medium"
    },
    {
        "query": "How does machine learning make predictions?",
        "difficulty": "Medium"
    },
    {
        "query": "What type of tasks can artificial intelligence perform?",
        "difficulty": "Medium"
    },

    # Hard
    {
        "query": "Explain how RAG uses retrieved information to improve language generation.",
        "difficulty": "Hard"
    },
    {
        "query": "Compare artificial intelligence and machine learning based only on the knowledge base.",
        "difficulty": "Hard"
    },
    {
        "query": "Why is retrieval important before generating an answer in a RAG system?",
        "difficulty": "Hard"
    },
    {
        "query": "Explain the relationship between AI, machine learning, and RAG.",
        "difficulty": "Hard"
    },
    {
        "query": "What would happen if the required information was not present in the retrieved context?",
        "difficulty": "Hard"
    }
]

print("Total test queries:", len(test_queries))

Total test queries: 15

In [94]:
evaluation_results = []

for item in test_queries:
    retrieved = retrieve_documents(item["query"], top_k=3)

    evaluation_results.append({
        "query": item["query"],
        "difficulty": item["difficulty"],
        "sources": [doc["id"] for doc in retrieved],
        "confidence": max(
            [1 / (1 + doc["score"]) for doc in retrieved],
            default=0.0
        )
    })

print("Evaluation completed.")
print("Total results:", len(evaluation_results))

Evaluation completed.
Total results: 15

In [95]:
import pandas as pd

evaluation_df = pd.DataFrame(evaluation_results)

evaluation_df[
    ["difficulty", "query", "sources", "confidence"]
]

,difficulty,query,sources,confidence
0,Easy,What is artificial intelligence?,"[doc_1_chunk_0, doc_2_chunk_0, doc_3_chunk_0]",0.780432
1,Easy,What is machine learning?,"[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.737338
2,Easy,What is RAG?,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.546558
3,Easy,What does AI focus on?,"[doc_1_chunk_0, doc_2_chunk_0, doc_3_chunk_0]",0.587957
4,Easy,What does machine learning learn from?,"[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.642094
5,Medium,How is machine learning related to artificial ...,"[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.657375
6,Medium,How does RAG combine retrieval and generation?,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.670985
7,Medium,What is the purpose of retrieving documents in...,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.553550
8,Medium,How does machine learning make predictions?,"[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.581762
9,Medium,What type of tasks can artificial intelligence...,"[doc_1_chunk_0, doc_2_chunk_0, doc_3_chunk_0]",0.631196
10,Hard,Explain how RAG uses retrieved information to ...,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.708372
11,Hard,Compare artificial intelligence and machine le...,"[doc_1_chunk_0, doc_2_chunk_0, doc_3_chunk_0]",0.509645
12,Hard,Why is retrieval important before generating a...,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.629709
13,Hard,"Explain the relationship between AI, machine l...","[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.557179
14,Hard,What would happen if the required information ...,"[doc_3_chunk_0, doc_1_chunk_0, doc_2_chunk_0]",0.403829

In [96]:
def score_retrieval(row):
    query = row["query"].lower()
    sources = " ".join(row["sources"]).lower()

    # Expected source based on the query
    if "machine learning" in query:
        expected = "doc_2"
    elif "rag" in query or "retriev" in query or "generat" in query:
        expected = "doc_3"
    elif "artificial intelligence" in query or "ai" in query:
        expected = "doc_1"
    else:
        expected = None

    if expected and expected in sources:
        return 1
    return 0


evaluation_df["retrieval_score"] = evaluation_df.apply(
    score_retrieval,
    axis=1
)

retrieval_accuracy = evaluation_df["retrieval_score"].mean()

print("Retrieval Quality Score:", round(retrieval_accuracy * 100, 2), "%")

Retrieval Quality Score: 100.0 %

In [97]:
evaluation_df[
    ["difficulty", "query", "sources", "confidence", "retrieval_score"]
]

,difficulty,query,sources,confidence,retrieval_score
0,Easy,What is artificial intelligence?,"[doc_1_chunk_0, doc_2_chunk_0, doc_3_chunk_0]",0.780432,1
1,Easy,What is machine learning?,"[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.737338,1
2,Easy,What is RAG?,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.546558,1
3,Easy,What does AI focus on?,"[doc_1_chunk_0, doc_2_chunk_0, doc_3_chunk_0]",0.587957,1
4,Easy,What does machine learning learn from?,"[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.642094,1
5,Medium,How is machine learning related to artificial ...,"[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.657375,1
6,Medium,How does RAG combine retrieval and generation?,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.670985,1
7,Medium,What is the purpose of retrieving documents in...,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.553550,1
8,Medium,How does machine learning make predictions?,"[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.581762,1
9,Medium,What type of tasks can artificial intelligence...,"[doc_1_chunk_0, doc_2_chunk_0, doc_3_chunk_0]",0.631196,1
10,Hard,Explain how RAG uses retrieved information to ...,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.708372,1
11,Hard,Compare artificial intelligence and machine le...,"[doc_1_chunk_0, doc_2_chunk_0, doc_3_chunk_0]",0.509645,1
12,Hard,Why is retrieval important before generating a...,"[doc_3_chunk_0, doc_2_chunk_0, doc_1_chunk_0]",0.629709,1
13,Hard,"Explain the relationship between AI, machine l...","[doc_2_chunk_0, doc_1_chunk_0, doc_3_chunk_0]",0.557179,1
14,Hard,What would happen if the required information ...,"[doc_3_chunk_0, doc_1_chunk_0, doc_2_chunk_0]",0.403829,1

In [98]:
response_quality_results = []

for item in test_queries:
    result = run_rag(item["query"])

    response_quality_results.append({
        "query": item["query"],
        "difficulty": item["difficulty"],
        "answer": result["answer"],
        "sources": result["sources"],
        "confidence": result["confidence"]
    })

print("Response evaluation completed.")
print("Total results:", len(response_quality_results))

[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Response evaluation completed.
Total results: 15

In [99]:
response_df = pd.DataFrame(response_quality_results)

def score_response(row):
    answer = row["answer"].lower()

    if "api error" in answer:
        return 0

    if "sources:" in answer:
        return 1

    return 0


response_df["response_score"] = response_df.apply(
    score_response,
    axis=1
)

response_quality = response_df["response_score"].mean()

print("Response Quality:", round(response_quality * 100, 2), "%")

Response Quality: 100.0 %

In [100]:
print("===== RAG EVALUATION SUMMARY =====")
print()
print("Total Test Queries:", len(test_queries))
print("Retrieval Quality:", round(retrieval_accuracy * 100, 2), "%")
print("Response Quality:", round(response_quality * 100, 2), "%")

===== RAG EVALUATION SUMMARY =====

Total Test Queries: 15
Retrieval Quality: 100.0 %
Response Quality: 100.0 %

In [101]:
low_confidence_results = evaluation_df[
    evaluation_df["confidence"] < 0.3
]

print("Low-confidence queries:", len(low_confidence_results))

low_confidence_results[
    ["query", "confidence", "sources"]
]

Low-confidence queries: 0

Empty DataFrame
Columns: [query, confidence, sources]
Index: []

In [103]:
%%writefile README.md

# AI Knowledge Assistant

A Retrieval-Augmented Generation (RAG) application built with Python, LangChain, FAISS, Hugging Face embeddings, and FastAPI.

## Features

- Document chunking
- Semantic search using FAISS
- Metadata filtering
- Grounded answer generation
- Source citations
- Confidence indicator
- FastAPI REST API

## Environment Setup

Install the required packages:

pip install langchain-text-splitters langchain-core langchain-huggingface langchain-community
pip install sentence-transformers faiss-cpu transformers fastapi uvicorn

## Environment Variables

This project uses a local Hugging Face model, so no OpenAI API key is required.

## Run Locally

Start the FastAPI server:

uvicorn app:app --host 127.0.0.1 --port 8000

The API will be available at:

http://127.0.0.1:8000

## API Endpoint

### POST /ask

Request:

{
    "query": "What is machine learning?"
}

Example curl for Windows:

curl -X POST "http://127.0.0.1:8000/ask" ^
-H "Content-Type: application/json" ^
-d "{\"query\":\"What is machine learning?\"}"

The response contains:

- answer
- sources
- confidence

## Project Files

- rag_pipeline.py - Complete RAG pipeline
- app.py - FastAPI application
- README.md - Project documentation

## Evaluation

The system was evaluated using 15 test queries across Easy, Medium, and Hard difficulty levels.

Two metrics were evaluated separately:

- Retrieval Quality
- Response Quality

Writing README.md