<a href="https://colab.research.google.com/github/Chikka-Pradhayani/ABTalks-60-Days-AI-Challenge/blob/main/Day-17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
documents_with_metadata = [
    {
        "text": "The application uses Python as its primary programming language for backend development.",
        "metadata": {
            "source": "backend_guide.pdf",
            "category": "technical",
            "date": "2024-06-15",
            "document_type": "technical_reference"
        }
    },

    {
        "text": "The application uses React for building the frontend user interface.",
        "metadata": {
            "source": "frontend_guide.pdf",
            "category": "technical",
            "date": "2024-07-20",
            "document_type": "technical_reference"
        }
    },

    {
        "text": "PostgreSQL is used as the primary relational database for storing application data.",
        "metadata": {
            "source": "database_guide.pdf",
            "category": "technical",
            "date": "2024-08-10",
            "document_type": "technical_reference"
        }
    },

    {
        "text": "Redis is used for caching frequently accessed data and improving application performance.",
        "metadata": {
            "source": "performance_guide.pdf",
            "category": "technical",
            "date": "2023-11-05",
            "document_type": "technical_reference"
        }
    },

    {
        "text": "User authentication is implemented using JSON Web Tokens (JWT).",
        "metadata": {
            "source": "security_guide.pdf",
            "category": "security",
            "date": "2024-09-12",
            "document_type": "technical_reference"
        }
    },

    {
        "text": "The authentication API endpoint is /api/auth/login.",
        "metadata": {
            "source": "api_documentation.pdf",
            "category": "technical",
            "date": "2024-10-01",
            "document_type": "api_reference"
        }
    },

    {
        "text": "The registration API endpoint is /api/auth/register.",
        "metadata": {
            "source": "api_documentation.pdf",
            "category": "technical",
            "date": "2024-10-01",
            "document_type": "api_reference"
        }
    },

    {
        "text": "Users can upload PDF files with a maximum file size of 10 MB.",
        "metadata": {
            "source": "user_guide.pdf",
            "category": "product",
            "date": "2024-05-18",
            "document_type": "user_documentation"
        }
    },

    {
        "text": "The chunking system uses a chunk size of 500 characters with an overlap of 50 characters.",
        "metadata": {
            "source": "rag_configuration.pdf",
            "category": "technical",
            "date": "2024-11-15",
            "document_type": "technical_reference"
        }
    },

    {
        "text": "FAISS is used as the vector database for storing and searching document embeddings.",
        "metadata": {
            "source": "rag_architecture.pdf",
            "category": "technical",
            "date": "2024-12-01",
            "document_type": "architecture"
        }
    },

    {
        "text": "The application supports a maximum of 1,000 concurrent users.",
        "metadata": {
            "source": "system_specification.pdf",
            "category": "technical",
            "date": "2024-03-25",
            "document_type": "technical_reference"
        }
    },

    {
        "text": "The application provides document upload, semantic search, authentication, and course generation features.",
        "metadata": {
            "source": "product_overview.pdf",
            "category": "product",
            "date": "2024-04-10",
            "document_type": "overview"
        }
    },

    {
        "text": "The refund policy allows users to request a refund within 7 days of purchase.",
        "metadata": {
            "source": "refund_policy.pdf",
            "category": "policy",
            "date": "2024-01-15",
            "document_type": "policy_document"
        }
    },

    {
        "text": "The application is deployed using Docker containers.",
        "metadata": {
            "source": "deployment_guide.pdf",
            "category": "technical",
            "date": "2023-08-20",
            "document_type": "deployment_reference"
        }
    },

    {
        "text": "The backend exposes REST APIs for communication between the frontend and backend.",
        "metadata": {
            "source": "api_architecture.pdf",
            "category": "technical",
            "date": "2024-02-28",
            "document_type": "architecture"
        }
    }
]

print("Total documents:", len(documents_with_metadata))

Total documents: 15

In [2]:
from langchain_core.documents import Document
print("LangChain Document imported successfully!")

LangChain Document imported successfully!

In [3]:
langchain_documents = []

for item in documents_with_metadata:

    doc = Document(
        page_content=item["text"],
        metadata=item["metadata"]
    )

    langchain_documents.append(doc)

print("LangChain documents created:", len(langchain_documents))

LangChain documents created: 15

In [4]:
print("CONTENT:")
print(langchain_documents[0].page_content)

print("\nMETADATA:")
print(langchain_documents[0].metadata)

CONTENT:
The application uses Python as its primary programming language for backend development.

METADATA:
{'source': 'backend_guide.pdf', 'category': 'technical', 'date': '2024-06-15', 'document_type': 'technical_reference'}

In [5]:
metadata_texts = [
    doc.page_content
    for doc in langchain_documents
]

print("Texts ready:", len(metadata_texts))

Texts ready: 15

In [7]:
from sentence_transformers import SentenceTransformer

embedder = SentenceTransformer("all-MiniLM-L6-v2")

print("Embedder loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedder loaded successfully!

In [8]:
metadata_embeddings = embedder.encode(
    metadata_texts,
    convert_to_numpy=True
).astype("float32")

print("Embedding shape:", metadata_embeddings.shape)

Embedding shape: (15, 384)

In [15]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.13/dist-packages (from faiss-cpu) (2.1.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from faiss-cpu) (26.3)
Downloading faiss_cpu-1.15.0-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 83.9 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.15.0

In [16]:
import faiss
print("FAISS imported successfully!")

FAISS imported successfully!

In [17]:
metadata_index = faiss.IndexFlatL2(
    metadata_embeddings.shape[1]
)

metadata_index.add(
    metadata_embeddings.astype("float32")
)

print("FAISS index created!")
print("Vectors stored:", metadata_index.ntotal)

FAISS index created!
Vectors stored: 15

In [9]:
def filtered_retrieve(query, filters=None, top_k=5):

    query_embedding = embedder.encode(
        [query],
        convert_to_numpy=True
    ).astype("float32")

    # Search more candidates because some may be removed by filters
    search_k = min(top_k * 3, metadata_index.ntotal)

    distances, indices = metadata_index.search(
        query_embedding,
        search_k
    )

    results = []

    for idx, distance in zip(indices[0], distances[0]):

        if idx == -1:
            continue

        doc = langchain_documents[idx]

        metadata = doc.metadata

        # Apply metadata filters
        if filters:

            # Category filter
            if "category" in filters:
                if metadata.get("category") != filters["category"]:
                    continue

            # Document type filter
            if "document_type" in filters:
                if metadata.get("document_type") != filters["document_type"]:
                    continue

            # Source filter
            if "source" in filters:
                if metadata.get("source") != filters["source"]:
                    continue

            # Date filter
            if "date_after" in filters:
                if metadata.get("date", "") < filters["date_after"]:
                    continue

        results.append({
            "content": doc.page_content,
            "metadata": metadata,
            "distance": float(distance)
        })

        if len(results) >= top_k:
            break

    return results

In [18]:
results_no_filter = filtered_retrieve(
    "What database is used by the application?"
)

print("WITHOUT FILTER")
print("=" * 50)

for result in results_no_filter:
    print("\nContent:", result["content"])
    print("Metadata:", result["metadata"])
    print("Distance:", result["distance"])

WITHOUT FILTER
==================================================

Content: PostgreSQL is used as the primary relational database for storing application data.
Metadata: {'source': 'database_guide.pdf', 'category': 'technical', 'date': '2024-08-10', 'document_type': 'technical_reference'}
Distance: 0.624103844165802

Content: The application provides document upload, semantic search, authentication, and course generation features.
Metadata: {'source': 'product_overview.pdf', 'category': 'product', 'date': '2024-04-10', 'document_type': 'overview'}
Distance: 1.0454660654067993

Content: Redis is used for caching frequently accessed data and improving application performance.
Metadata: {'source': 'performance_guide.pdf', 'category': 'technical', 'date': '2023-11-05', 'document_type': 'technical_reference'}
Distance: 1.1311616897583008

Content: FAISS is used as the vector database for storing and searching document embeddings.
Metadata: {'source': 'rag_architecture.pdf', 'category': 'technical', 'date': '2024-12-01', 'document_type': 'architecture'}
Distance: 1.134435772895813

Content: The application supports a maximum of 1,000 concurrent users.
Metadata: {'source': 'system_specification.pdf', 'category': 'technical', 'date': '2024-03-25', 'document_type': 'technical_reference'}
Distance: 1.1610974073410034

In [19]:
results_category = filtered_retrieve(
    "What database is used by the application?",
    filters={
        "category": "technical"
    }
)

print("WITH CATEGORY FILTER")
print("=" * 50)

for result in results_category:
    print("\nContent:", result["content"])
    print("Metadata:", result["metadata"])
    print("Distance:", result["distance"])

WITH CATEGORY FILTER
==================================================

Content: PostgreSQL is used as the primary relational database for storing application data.
Metadata: {'source': 'database_guide.pdf', 'category': 'technical', 'date': '2024-08-10', 'document_type': 'technical_reference'}
Distance: 0.624103844165802

Content: Redis is used for caching frequently accessed data and improving application performance.
Metadata: {'source': 'performance_guide.pdf', 'category': 'technical', 'date': '2023-11-05', 'document_type': 'technical_reference'}
Distance: 1.1311616897583008

Content: FAISS is used as the vector database for storing and searching document embeddings.
Metadata: {'source': 'rag_architecture.pdf', 'category': 'technical', 'date': '2024-12-01', 'document_type': 'architecture'}
Distance: 1.134435772895813

Content: The application supports a maximum of 1,000 concurrent users.
Metadata: {'source': 'system_specification.pdf', 'category': 'technical', 'date': '2024-03-25', 'document_type': 'technical_reference'}
Distance: 1.1610974073410034

Content: The application uses Python as its primary programming language for backend development.
Metadata: {'source': 'backend_guide.pdf', 'category': 'technical', 'date': '2024-06-15', 'document_type': 'technical_reference'}
Distance: 1.1701810359954834

In [20]:
results_date = filtered_retrieve(
    "How is the application deployed?",
    filters={
        "date_after": "2024-01-01"
    }
)

print("WITH DATE FILTER")
print("=" * 50)

for result in results_date:
    print("\nContent:", result["content"])
    print("Date:", result["metadata"]["date"])
    print("Distance:", result["distance"])

WITH DATE FILTER
==================================================

Content: The application uses React for building the frontend user interface.
Date: 2024-07-20
Distance: 1.074824333190918

Content: The application uses Python as its primary programming language for backend development.
Date: 2024-06-15
Distance: 1.1704767942428589

Content: The application provides document upload, semantic search, authentication, and course generation features.
Date: 2024-04-10
Distance: 1.2583317756652832

Content: The backend exposes REST APIs for communication between the frontend and backend.
Date: 2024-02-28
Distance: 1.3964062929153442

Content: The application supports a maximum of 1,000 concurrent users.
Date: 2024-03-25
Distance: 1.417386531829834

In [21]:
comparison_queries = [
    {
        "query": "Which database is used by the application?",
        "filters": {"category": "technical"},
        "expected_source": "database_guide.pdf"
    },
    {
        "query": "How is user authentication implemented?",
        "filters": {"category": "security"},
        "expected_source": "security_guide.pdf"
    },
    {
        "query": "What is the maximum file size for uploads?",
        "filters": {"category": "product"},
        "expected_source": "user_guide.pdf"
    },
    {
        "query": "What is the refund policy?",
        "filters": {"category": "policy"},
        "expected_source": "refund_policy.pdf"
    },
    {
        "query": "How is the application deployed?",
        "filters": {
            "category": "technical",
            "date_after": "2024-01-01"
        },
        "expected_source": "deployment_guide.pdf"
    }
]

print("Queries:", len(comparison_queries))

Queries: 5

In [22]:
comparison_results = []

for item in comparison_queries:

    results = filtered_retrieve(
        item["query"],
        filters=None,
        top_k=5
    )

    comparison_results.append({
        "query": item["query"],
        "filters": item["filters"],
        "expected_source": item["expected_source"],
        "without_filters": results
    })

print("Completed unfiltered retrieval.")

Completed unfiltered retrieval.

In [23]:
for i, item in enumerate(comparison_queries):

    results = filtered_retrieve(
        item["query"],
        filters=item["filters"],
        top_k=5
    )

    comparison_results[i]["with_filters"] = results

print("Completed filtered retrieval.")

Completed filtered retrieval.

In [24]:
for result in comparison_results:

    print("\n" + "=" * 80)
    print("QUERY:", result["query"])

    print("\nWITHOUT FILTERS:")

    for r in result["without_filters"]:
        print(
            f"- {r['metadata']['source']} "
            f"| {r['metadata']['category']} "
            f"| {r['metadata']['date']} "
            f"| distance={r['distance']:.4f}"
        )

    print("\nWITH FILTERS:")

    for r in result["with_filters"]:
        print(
            f"- {r['metadata']['source']} "
            f"| {r['metadata']['category']} "
            f"| {r['metadata']['date']} "
            f"| distance={r['distance']:.4f}"
        )

================================================================================
QUERY: Which database is used by the application?

WITHOUT FILTERS:
- database_guide.pdf | technical | 2024-08-10 | distance=0.6576
- product_overview.pdf | product | 2024-04-10 | distance=1.1420
- performance_guide.pdf | technical | 2023-11-05 | distance=1.1764
- backend_guide.pdf | technical | 2024-06-15 | distance=1.1970
- deployment_guide.pdf | technical | 2023-08-20 | distance=1.1979

WITH FILTERS:
- database_guide.pdf | technical | 2024-08-10 | distance=0.6576
- performance_guide.pdf | technical | 2023-11-05 | distance=1.1764
- backend_guide.pdf | technical | 2024-06-15 | distance=1.1970
- deployment_guide.pdf | technical | 2023-08-20 | distance=1.1979
- system_specification.pdf | technical | 2024-03-25 | distance=1.2241

================================================================================
QUERY: How is user authentication implemented?

WITHOUT FILTERS:
- security_guide.pdf | security | 2024-09-12 | distance=0.4159
- api_documentation.pdf | technical | 2024-10-01 | distance=0.9746
- api_documentation.pdf | technical | 2024-10-01 | distance=1.2146
- product_overview.pdf | product | 2024-04-10 | distance=1.3806
- system_specification.pdf | technical | 2024-03-25 | distance=1.4386

WITH FILTERS:
- security_guide.pdf | security | 2024-09-12 | distance=0.4159

================================================================================
QUERY: What is the maximum file size for uploads?

WITHOUT FILTERS:
- user_guide.pdf | product | 2024-05-18 | distance=0.5064
- rag_configuration.pdf | technical | 2024-11-15 | distance=1.1028
- system_specification.pdf | technical | 2024-03-25 | distance=1.3557
- rag_architecture.pdf | technical | 2024-12-01 | distance=1.5640
- product_overview.pdf | product | 2024-04-10 | distance=1.6834

WITH FILTERS:
- user_guide.pdf | product | 2024-05-18 | distance=0.5064
- product_overview.pdf | product | 2024-04-10 | distance=1.6834

================================================================================
QUERY: What is the refund policy?

WITHOUT FILTERS:
- refund_policy.pdf | policy | 2024-01-15 | distance=0.6027
- performance_guide.pdf | technical | 2023-11-05 | distance=1.7449
- user_guide.pdf | product | 2024-05-18 | distance=1.7842
- security_guide.pdf | security | 2024-09-12 | distance=1.8448
- system_specification.pdf | technical | 2024-03-25 | distance=1.8530

WITH FILTERS:
- refund_policy.pdf | policy | 2024-01-15 | distance=0.6027

================================================================================
QUERY: How is the application deployed?

WITHOUT FILTERS:
- deployment_guide.pdf | technical | 2023-08-20 | distance=0.5484
- frontend_guide.pdf | technical | 2024-07-20 | distance=1.0748
- backend_guide.pdf | technical | 2024-06-15 | distance=1.1705
- product_overview.pdf | product | 2024-04-10 | distance=1.2583
- api_architecture.pdf | technical | 2024-02-28 | distance=1.3964

WITH FILTERS:
- frontend_guide.pdf | technical | 2024-07-20 | distance=1.0748
- backend_guide.pdf | technical | 2024-06-15 | distance=1.1705
- api_architecture.pdf | technical | 2024-02-28 | distance=1.3964
- system_specification.pdf | technical | 2024-03-25 | distance=1.4174
- database_guide.pdf | technical | 2024-08-10 | distance=1.5200

In [25]:
def calculate_precision(results, expected_source):

    if len(results) == 0:
        return 0.0

    relevant = sum(
        1
        for result in results
        if result["metadata"].get("source") == expected_source
    )

    return relevant / len(results)

In [26]:
precision_results = []

for item in comparison_results:

    expected_source = item["expected_source"]

    precision_without = calculate_precision(
        item["without_filters"],
        expected_source
    )

    precision_with = calculate_precision(
        item["with_filters"],
        expected_source
    )

    precision_results.append({
        "query": item["query"],
        "expected_source": expected_source,
        "precision_without_filters": precision_without,
        "precision_with_filters": precision_with
    })

print("Precision calculations completed!")

Precision calculations completed!

In [29]:
import pandas as pd

precision_df = pd.DataFrame(precision_results)

precision_df

,query,expected_source,precision_without_filters,precision_with_filters
0,Which database is used by the application?,database_guide.pdf,0.2,0.2
1,How is user authentication implemented?,security_guide.pdf,0.2,1.0
2,What is the maximum file size for uploads?,user_guide.pdf,0.2,0.5
3,What is the refund policy?,refund_policy.pdf,0.2,1.0
4,How is the application deployed?,deployment_guide.pdf,0.2,0.0

In [30]:
print("precision_results exists:",
      "precision_results" in globals())

print("Number of results:",
      len(precision_results) if "precision_results" in globals() else 0)

precision_results exists: True
Number of results: 5

In [31]:
import pandas as pd

precision_df = pd.DataFrame(precision_results)

precision_df

,query,expected_source,precision_without_filters,precision_with_filters
0,Which database is used by the application?,database_guide.pdf,0.2,0.2
1,How is user authentication implemented?,security_guide.pdf,0.2,1.0
2,What is the maximum file size for uploads?,user_guide.pdf,0.2,0.5
3,What is the refund policy?,refund_policy.pdf,0.2,1.0
4,How is the application deployed?,deployment_guide.pdf,0.2,0.0

In [32]:
avg_precision_without = precision_df[
    "precision_without_filters"
].mean()

avg_precision_with = precision_df[
    "precision_with_filters"
].mean()

print(
    f"Average precision WITHOUT filters: "
    f"{avg_precision_without:.2f}"
)

print(
    f"Average precision WITH filters: "
    f"{avg_precision_with:.2f}"
)

Average precision WITHOUT filters: 0.20
Average precision WITH filters: 0.54

In [33]:
improvement = (
    avg_precision_with -
    avg_precision_without
)

print(
    f"Precision improvement: "
    f"{improvement:+.2f}"
)

Precision improvement: +0.34

In [34]:
precision_df.to_csv(
    "day17_metadata_precision_comparison.csv",
    index=False
)

print("Saved: day17_metadata_precision_comparison.csv")

Saved: day17_metadata_precision_comparison.csv

In [36]:
import json

print("JSON imported successfully!")

JSON imported successfully!

In [37]:
with open(
    "day17_metadata_results.json",
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        comparison_results,
        f,
        indent=4,
        ensure_ascii=False
    )

print("Saved: day17_metadata_results.json")

Saved: day17_metadata_results.json