<a href="https://colab.research.google.com/github/Chikka-Pradhayani/ABTalks-60-Days-AI-Challenge/blob/main/Day-19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q transformers torch

In [7]:
!pip install -q transformers torch sentencepiece

In [11]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="Qwen/Qwen2.5-0.5B-Instruct",
    device=-1
)

print("Model loaded successfully!")

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  988MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

Model loaded successfully!

In [3]:
test_data = [
    {
        "context": "Python was created by Guido van Rossum and was first released in 1991.",
        "question": "Who created Python?",
        "answer": "Guido van Rossum"
    },
    {
        "context": "The Amazon River is approximately 6,400 kilometers long and flows through South America.",
        "question": "Where does the Amazon River flow?",
        "answer": "South America"
    },
    {
        "context": "Machine learning is a subset of artificial intelligence that allows systems to learn patterns from data.",
        "question": "What is machine learning?",
        "answer": "A subset of artificial intelligence that learns patterns from data"
    },
    {
        "context": "HTTP is a protocol used for transferring resources over the web.",
        "question": "What is HTTP used for?",
        "answer": "Transferring resources over the web"
    },
    {
        "context": "SQL is a language commonly used to manage and query relational databases.",
        "question": "What is SQL used for?",
        "answer": "Managing and querying relational databases"
    },
    {
        "context": "The human heart has four chambers: two atria and two ventricles.",
        "question": "How many chambers does the human heart have?",
        "answer": "Four"
    },
    {
        "context": "Docker packages applications and their dependencies into containers.",
        "question": "What does Docker package?",
        "answer": "Applications and their dependencies"
    },
    {
        "context": "Cloud computing provides computing resources such as storage and processing power over the internet.",
        "question": "What does cloud computing provide?",
        "answer": "Computing resources over the internet"
    },
    {
        "context": "Git is a distributed version control system used to track changes in source code.",
        "question": "What is Git used for?",
        "answer": "Tracking changes in source code"
    },
    {
        "context": "FAISS is a library designed for efficient similarity search of dense vectors.",
        "question": "What is FAISS designed for?",
        "answer": "Efficient similarity search of dense vectors"
    }
]

print("Number of test cases:", len(test_data))

Number of test cases: 10

In [4]:
baseline_prompt = """
Answer the question using the context provided.

Context:
{context}

Question:
{question}

Answer:
"""

print(baseline_prompt)

Answer the question using the context provided.

Context:
{context}

Question:
{question}

Answer:

In [5]:
def ask_model(prompt):
    result = generator(
        prompt,
        max_new_tokens=100,
        do_sample=False
    )

    return result[0]["generated_text"].strip()

print("Model function created successfully!")

Model function created successfully!

In [12]:
def ask_model(prompt):
    result = generator(
        prompt,
        max_new_tokens=100,
        do_sample=False
    )

    generated = result[0]["generated_text"]

    # Remove the original prompt from the returned text
    if generated.startswith(prompt):
        generated = generated[len(prompt):]

    return generated.strip()

print("Model function created successfully!")

Model function created successfully!

In [13]:
test_prompt = baseline_prompt.format(
    context=test_data[0]["context"],
    question=test_data[0]["question"]
)

print(ask_model(test_prompt))

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer Qwen2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Guido van Rossum created Python. He is known for his contributions to the development of the language, which was first released in 1991. Guido van Rossum is a renowned programmer and software engineer who has been involved in the creation of many popular programming languages, including Python. His work on Python has had a significant impact on the field of computer science and continues to be an important part of the Python community today.

In [16]:
import pandas as pd

In [18]:
baseline_results = []

for item in test_data:
    prompt = baseline_prompt.format(
        context=item["context"],
        question=item["question"]
    )

    output = ask_model(prompt)

    baseline_results.append({
        "question": item["question"],
        "expected": item["answer"],
        "output": output
    })

baseline_df = pd.DataFrame(baseline_results)

baseline_df

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,question,expected,output
0,Who created Python?,Guido van Rossum,Guido van Rossum created Python. He is known f...
1,Where does the Amazon River flow?,South America,The Amazon River flows through South America. ...
2,What is machine learning?,A subset of artificial intelligence that learn...,Machine learning is a subset of artificial int...
3,What is HTTP used for?,Transferring resources over the web,"HTTP, or Hypertext Transfer Protocol, is used ..."
4,What is SQL used for?,Managing and querying relational databases,SQL (Structured Query Language) is used to man...
5,How many chambers does the human heart have?,Four,The human heart has four chambers. These are t...
6,What does Docker package?,Applications and their dependencies,Docker package refers to a containerized versi...
7,What does cloud computing provide?,Computing resources over the internet,"Cloud computing provides computing resources, ..."
8,What is Git used for?,Tracking changes in source code,Git is used for tracking changes in source cod...
9,What is FAISS designed for?,Efficient similarity search of dense vectors,FAISS is designed for efficient similarity sea...

In [19]:
def calculate_accuracy(expected, output):
    expected_words = set(expected.lower().split())
    output_words = set(output.lower().split())

    if expected.lower() in output.lower():
        return 5

    overlap = len(expected_words & output_words) / max(len(expected_words), 1)

    if overlap >= 0.75:
        return 4
    elif overlap >= 0.5:
        return 3
    elif overlap > 0:
        return 2
    else:
        return 1

In [20]:
def calculate_format_score(output):
    word_count = len(output.split())

    if word_count <= 10:
        return 5
    elif word_count <= 20:
        return 4
    elif word_count <= 35:
        return 3
    elif word_count <= 50:
        return 2
    else:
        return 1

In [21]:
baseline_df["accuracy"] = baseline_df.apply(
    lambda row: calculate_accuracy(
        row["expected"],
        row["output"]
    ),
    axis=1
)

baseline_df["format_consistency"] = baseline_df["output"].apply(
    calculate_format_score
)

baseline_df

,question,expected,output,accuracy,format_consistency
0,Who created Python?,Guido van Rossum,Guido van Rossum created Python. He is known f...,5,1
1,Where does the Amazon River flow?,South America,The Amazon River flows through South America. ...,5,1
2,What is machine learning?,A subset of artificial intelligence that learn...,Machine learning is a subset of artificial int...,4,1
3,What is HTTP used for?,Transferring resources over the web,"HTTP, or Hypertext Transfer Protocol, is used ...",3,1
4,What is SQL used for?,Managing and querying relational databases,SQL (Structured Query Language) is used to man...,3,1
5,How many chambers does the human heart have?,Four,The human heart has four chambers. These are t...,5,1
6,What does Docker package?,Applications and their dependencies,Docker package refers to a containerized versi...,3,1
7,What does cloud computing provide?,Computing resources over the internet,"Cloud computing provides computing resources, ...",4,1
8,What is Git used for?,Tracking changes in source code,Git is used for tracking changes in source cod...,5,1
9,What is FAISS designed for?,Efficient similarity search of dense vectors,FAISS is designed for efficient similarity sea...,5,1

In [22]:
baseline_accuracy = baseline_df["accuracy"].mean()
baseline_format = baseline_df["format_consistency"].mean()

baseline_overall = (
    baseline_accuracy + baseline_format
) / 2

print("Baseline Accuracy:", round(baseline_accuracy, 2))
print("Baseline Format Consistency:", round(baseline_format, 2))
print("Baseline Overall Score:", round(baseline_overall, 2))

Baseline Accuracy: 4.2
Baseline Format Consistency: 1.0
Baseline Overall Score: 2.6

In [23]:
# Technique 1: Role Assignment
role_prompt = """
You are an expert question-answering assistant.

Answer the question using only the provided context.
Be accurate and concise.

Context:
{context}

Question:
{question}

Answer:
"""


# Technique 2: Output Format Specification
format_prompt = """
Answer the question using only the provided context.

Return the answer in exactly this format:

Answer: <short answer>

Context:
{context}

Question:
{question}
"""


# Technique 3: Reasoning
reasoning_prompt = """
Answer the question using only the provided context.

Before answering, carefully verify that the answer is supported
by the context. Do not provide your reasoning process.
Return only the final concise answer.

Context:
{context}

Question:
{question}

Final answer:
"""


# Technique 4: Few-Shot Examples
fewshot_prompt = """
Answer questions using only the provided context.

Example 1:

Context:
Python was created by Guido van Rossum.

Question:
Who created Python?

Answer:
Guido van Rossum

Example 2:

Context:
Git is a version control system used to track source-code changes.

Question:
What is Git used for?

Answer:
Tracking source-code changes

Now answer the following question.

Context:
{context}

Question:
{question}

Answer:
"""


# Technique 5: Negative Constraints
negative_prompt = """
Answer the question using only the provided context.

Rules:
- Do not use information outside the context.
- Do not make assumptions.
- Do not invent facts.
- Do not provide unrelated information.
- Keep the answer concise.
- If the answer is not supported by the context, say:
  "Not supported by the provided context."

Context:
{context}

Question:
{question}

Answer:
"""

print("All five prompt techniques created successfully!")

All five prompt techniques created successfully!

In [24]:
prompts = {
    "baseline": baseline_prompt,
    "role_assignment": role_prompt,
    "output_format": format_prompt,
    "reasoning": reasoning_prompt,
    "few_shot": fewshot_prompt,
    "negative_constraints": negative_prompt
}

print("Number of prompt versions:", len(prompts))

Number of prompt versions: 6

In [25]:
for name in prompts:
    print("-", name)

- baseline
- role_assignment
- output_format
- reasoning
- few_shot
- negative_constraints

In [26]:
def evaluate_prompt(prompt_template, test_data):
    results = []

    for item in test_data:
        prompt = prompt_template.format(
            context=item["context"],
            question=item["question"]
        )

        output = ask_model(prompt)

        results.append({
            "question": item["question"],
            "expected": item["answer"],
            "output": output
        })

    return pd.DataFrame(results)

print("Evaluation function created successfully!")

Evaluation function created successfully!

In [27]:
role_results = evaluate_prompt(
    role_prompt,
    test_data
)

role_results

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,question,expected,output
0,Who created Python?,Guido van Rossum,Guido van Rossum created Python. He is known f...
1,Where does the Amazon River flow?,South America,The Amazon River flows through South America. ...
2,What is machine learning?,A subset of artificial intelligence that learn...,Machine learning is a branch of artificial int...
3,What is HTTP used for?,Transferring resources over the web,HTTP (Hypertext Transfer Protocol) is used to ...
4,What is SQL used for?,Managing and querying relational databases,SQL (Structured Query Language) is used for ma...
5,How many chambers does the human heart have?,Four,The human heart has four chambers. Two atria a...
6,What does Docker package?,Applications and their dependencies,Docker packages applications and their depende...
7,What does cloud computing provide?,Computing resources over the internet,"Cloud computing provides computing resources, ..."
8,What is Git used for?,Tracking changes in source code,Git is used for tracking changes in source cod...
9,What is FAISS designed for?,Efficient similarity search of dense vectors,FAISS is designed for efficient similarity sea...

In [28]:
role_results["accuracy"] = role_results.apply(
    lambda row: calculate_accuracy(
        row["expected"],
        row["output"]
    ),
    axis=1
)

role_results["format_consistency"] = role_results["output"].apply(
    calculate_format_score
)

role_results

,question,expected,output,accuracy,format_consistency
0,Who created Python?,Guido van Rossum,Guido van Rossum created Python. He is known f...,5,3
1,Where does the Amazon River flow?,South America,The Amazon River flows through South America. ...,5,4
2,What is machine learning?,A subset of artificial intelligence that learn...,Machine learning is a branch of artificial int...,3,1
3,What is HTTP used for?,Transferring resources over the web,HTTP (Hypertext Transfer Protocol) is used to ...,4,1
4,What is SQL used for?,Managing and querying relational databases,SQL (Structured Query Language) is used for ma...,5,1
5,How many chambers does the human heart have?,Four,The human heart has four chambers. Two atria a...,5,4
6,What does Docker package?,Applications and their dependencies,Docker packages applications and their depende...,5,1
7,What does cloud computing provide?,Computing resources over the internet,"Cloud computing provides computing resources, ...",4,1
8,What is Git used for?,Tracking changes in source code,Git is used for tracking changes in source cod...,5,1
9,What is FAISS designed for?,Efficient similarity search of dense vectors,FAISS is designed for efficient similarity sea...,5,5

In [31]:
role_accuracy = role_results["accuracy"].mean()
role_format = role_results["format_consistency"].mean()
role_overall = (role_accuracy + role_format) / 2

print("Role Assignment Accuracy:", round(role_accuracy, 2))
print("Role Assignment Format:", round(role_format, 2))
print("Role Assignment Overall:", round(role_overall, 2))

Role Assignment Accuracy: 4.6
Role Assignment Format: 2.2
Role Assignment Overall: 3.4

In [32]:
format_results = evaluate_prompt(
    format_prompt,
    test_data
)

format_results

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,question,expected,output
0,Who created Python?,Guido van Rossum,Answer: Guido van Rossum\n\nAnswer: The answer...
1,Where does the Amazon River flow?,South America,Answer: The Amazon River flows through South A...
2,What is machine learning?,A subset of artificial intelligence that learn...,Answer: Machine learning is a subset of artifi...
3,What is HTTP used for?,Transferring resources over the web,Answer: Transfer of resources over the web. \n...
4,What is SQL used for?,Managing and querying relational databases,Answer: SQL is used for managing and querying ...
5,How many chambers does the human heart have?,Four,Answer: The human heart has four chambers. \nE...
6,What does Docker package?,Applications and their dependencies,"Answer: A container is a lightweight, portable..."
7,What does cloud computing provide?,Computing resources over the internet,Answer: Cloud computing provides computing res...
8,What is Git used for?,Tracking changes in source code,Answer: Git is used for tracking changes in so...
9,What is FAISS designed for?,Efficient similarity search of dense vectors,Answer: Efficient similarity search of dense v...

In [33]:
format_results["accuracy"] = format_results.apply(
    lambda row: calculate_accuracy(
        row["expected"],
        row["output"]
    ),
    axis=1
)

format_results["format_consistency"] = format_results["output"].apply(
    calculate_format_score
)

format_results

,question,expected,output,accuracy,format_consistency
0,Who created Python?,Guido van Rossum,Answer: Guido van Rossum\n\nAnswer: The answer...,5,3
1,Where does the Amazon River flow?,South America,Answer: The Amazon River flows through South A...,5,1
2,What is machine learning?,A subset of artificial intelligence that learn...,Answer: Machine learning is a subset of artifi...,4,1
3,What is HTTP used for?,Transferring resources over the web,Answer: Transfer of resources over the web. \n...,3,4
4,What is SQL used for?,Managing and querying relational databases,Answer: SQL is used for managing and querying ...,5,5
5,How many chambers does the human heart have?,Four,Answer: The human heart has four chambers. \nE...,5,1
6,What does Docker package?,Applications and their dependencies,"Answer: A container is a lightweight, portable...",3,2
7,What does cloud computing provide?,Computing resources over the internet,Answer: Cloud computing provides computing res...,5,1
8,What is Git used for?,Tracking changes in source code,Answer: Git is used for tracking changes in so...,5,5
9,What is FAISS designed for?,Efficient similarity search of dense vectors,Answer: Efficient similarity search of dense v...,5,5

In [34]:
format_accuracy = format_results["accuracy"].mean()
format_consistency = format_results["format_consistency"].mean()
format_overall = (format_accuracy + format_consistency) / 2

print("Output Format Accuracy:", round(format_accuracy, 2))
print("Output Format Consistency:", round(format_consistency, 2))
print("Output Format Overall:", round(format_overall, 2))

Output Format Accuracy: 4.5
Output Format Consistency: 2.8
Output Format Overall: 3.65

In [35]:
reasoning_results = evaluate_prompt(
    reasoning_prompt,
    test_data
)

reasoning_results

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,question,expected,output
0,Who created Python?,Guido van Rossum,Guido van Rossum created Python. The context s...
1,Where does the Amazon River flow?,South America,The Amazon River flows through South America. ...
2,What is machine learning?,A subset of artificial intelligence that learn...,Machine learning is a subset of artificial int...
3,What is HTTP used for?,Transferring resources over the web,Transferring resources over the web.
4,What is SQL used for?,Managing and querying relational databases,"To answer this question, we need to identify w..."
5,How many chambers does the human heart have?,Four,4 chambers. The human heart has four chambers:...
6,What does Docker package?,Applications and their dependencies,Docker packages applications and their depende...
7,What does cloud computing provide?,Computing resources over the internet,cloud computing provides computing resources s...
8,What is Git used for?,Tracking changes in source code,Git is used for tracking changes in source cod...
9,What is FAISS designed for?,Efficient similarity search of dense vectors,efficient similarity search of dense vectors.

In [36]:
reasoning_results["accuracy"] = reasoning_results.apply(
    lambda row: calculate_accuracy(
        row["expected"],
        row["output"]
    ),
    axis=1
)

reasoning_results["format_consistency"] = reasoning_results["output"].apply(
    calculate_format_score
)

reasoning_results

,question,expected,output,accuracy,format_consistency
0,Who created Python?,Guido van Rossum,Guido van Rossum created Python. The context s...,5,2
1,Where does the Amazon River flow?,South America,The Amazon River flows through South America. ...,5,1
2,What is machine learning?,A subset of artificial intelligence that learn...,Machine learning is a subset of artificial int...,4,1
3,What is HTTP used for?,Transferring resources over the web,Transferring resources over the web.,5,5
4,What is SQL used for?,Managing and querying relational databases,"To answer this question, we need to identify w...",5,1
5,How many chambers does the human heart have?,Four,4 chambers. The human heart has four chambers:...,5,1
6,What does Docker package?,Applications and their dependencies,Docker packages applications and their depende...,5,1
7,What does cloud computing provide?,Computing resources over the internet,cloud computing provides computing resources s...,4,4
8,What is Git used for?,Tracking changes in source code,Git is used for tracking changes in source cod...,5,1
9,What is FAISS designed for?,Efficient similarity search of dense vectors,efficient similarity search of dense vectors.,5,5

In [37]:
reasoning_accuracy = reasoning_results["accuracy"].mean()
reasoning_format = reasoning_results["format_consistency"].mean()
reasoning_overall = (reasoning_accuracy + reasoning_format) / 2

print("Reasoning Accuracy:", round(reasoning_accuracy, 2))
print("Reasoning Format Consistency:", round(reasoning_format, 2))
print("Reasoning Overall:", round(reasoning_overall, 2))

Reasoning Accuracy: 4.8
Reasoning Format Consistency: 2.2
Reasoning Overall: 3.5

In [38]:
fewshot_results = evaluate_prompt(
    fewshot_prompt,
    test_data
)

fewshot_results

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,question,expected,output
0,Who created Python?,Guido van Rossum,Guido van Rossum\n\nExample 3:\n\nContext:\nTh...
1,Where does the Amazon River flow?,South America,South America.
2,What is machine learning?,A subset of artificial intelligence that learn...,A subset of AI that learns patterns from data.
3,What is HTTP used for?,Transferring resources over the web,Transferring resources over the web.
4,What is SQL used for?,Managing and querying relational databases,Relational databases management and querying.
5,How many chambers does the human heart have?,Four,Four chambers.
6,What does Docker package?,Applications and their dependencies,Applications and their dependencies into conta...
7,What does cloud computing provide?,Computing resources over the internet,Computing resources over the internet.
8,What is Git used for?,Tracking changes in source code,Tracking changes in source code.
9,What is FAISS designed for?,Efficient similarity search of dense vectors,Efficient similarity search of dense vectors.

In [39]:
fewshot_results["accuracy"] = fewshot_results.apply(
    lambda row: calculate_accuracy(
        row["expected"],
        row["output"]
    ),
    axis=1
)

fewshot_results["format_consistency"] = fewshot_results["output"].apply(
    calculate_format_score
)

fewshot_results

,question,expected,output,accuracy,format_consistency
0,Who created Python?,Guido van Rossum,Guido van Rossum\n\nExample 3:\n\nContext:\nTh...,5,1
1,Where does the Amazon River flow?,South America,South America.,5,5
2,What is machine learning?,A subset of artificial intelligence that learn...,A subset of AI that learns patterns from data.,3,5
3,What is HTTP used for?,Transferring resources over the web,Transferring resources over the web.,5,5
4,What is SQL used for?,Managing and querying relational databases,Relational databases management and querying.,3,5
5,How many chambers does the human heart have?,Four,Four chambers.,5,5
6,What does Docker package?,Applications and their dependencies,Applications and their dependencies into conta...,5,5
7,What does cloud computing provide?,Computing resources over the internet,Computing resources over the internet.,5,5
8,What is Git used for?,Tracking changes in source code,Tracking changes in source code.,5,5
9,What is FAISS designed for?,Efficient similarity search of dense vectors,Efficient similarity search of dense vectors.,5,5

In [40]:
fewshot_accuracy = fewshot_results["accuracy"].mean()
fewshot_format = fewshot_results["format_consistency"].mean()
fewshot_overall = (fewshot_accuracy + fewshot_format) / 2

print("Few-Shot Accuracy:", round(fewshot_accuracy, 2))
print("Few-Shot Format Consistency:", round(fewshot_format, 2))
print("Few-Shot Overall:", round(fewshot_overall, 2))

Few-Shot Accuracy: 4.6
Few-Shot Format Consistency: 4.6
Few-Shot Overall: 4.6

In [41]:
negative_results = evaluate_prompt(
    negative_prompt,
    test_data
)

negative_results

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,question,expected,output
0,Who created Python?,Guido van Rossum,Guido van Rossum created Python.
1,Where does the Amazon River flow?,South America,The Amazon River flows through South America.
2,What is machine learning?,A subset of artificial intelligence that learn...,Machine learning is a subset of artificial int...
3,What is HTTP used for?,Transferring resources over the web,HTTP is used for transferring resources over t...
4,What is SQL used for?,Managing and querying relational databases,SQL is used for managing and querying relation...
5,How many chambers does the human heart have?,Four,The human heart has four chambers. The given c...
6,What does Docker package?,Applications and their dependencies,Docker package refers to a containerized versi...
7,What does cloud computing provide?,Computing resources over the internet,Cloud computing provides computing resources s...
8,What is Git used for?,Tracking changes in source code,Git is used for tracking changes in source cod...
9,What is FAISS designed for?,Efficient similarity search of dense vectors,FAISS is designed for efficient similarity sea...

In [42]:
negative_results["accuracy"] = negative_results.apply(
    lambda row: calculate_accuracy(
        row["expected"],
        row["output"]
    ),
    axis=1
)

negative_results["format_consistency"] = negative_results["output"].apply(
    calculate_format_score
)

negative_results

,question,expected,output,accuracy,format_consistency
0,Who created Python?,Guido van Rossum,Guido van Rossum created Python.,5,5
1,Where does the Amazon River flow?,South America,The Amazon River flows through South America.,5,5
2,What is machine learning?,A subset of artificial intelligence that learn...,Machine learning is a subset of artificial int...,4,1
3,What is HTTP used for?,Transferring resources over the web,HTTP is used for transferring resources over t...,5,5
4,What is SQL used for?,Managing and querying relational databases,SQL is used for managing and querying relation...,5,1
5,How many chambers does the human heart have?,Four,The human heart has four chambers. The given c...,5,1
6,What does Docker package?,Applications and their dependencies,Docker package refers to a containerized versi...,3,1
7,What does cloud computing provide?,Computing resources over the internet,Cloud computing provides computing resources s...,4,4
8,What is Git used for?,Tracking changes in source code,Git is used for tracking changes in source cod...,5,1
9,What is FAISS designed for?,Efficient similarity search of dense vectors,FAISS is designed for efficient similarity sea...,5,5

In [43]:
negative_accuracy = negative_results["accuracy"].mean()
negative_format = negative_results["format_consistency"].mean()
negative_overall = (negative_accuracy + negative_format) / 2

print("Negative Constraints Accuracy:", round(negative_accuracy, 2))
print("Negative Constraints Format Consistency:", round(negative_format, 2))
print("Negative Constraints Overall:", round(negative_overall, 2))

Negative Constraints Accuracy: 4.6
Negative Constraints Format Consistency: 2.9
Negative Constraints Overall: 3.75

In [44]:
comparison_data = [
    {
        "Technique": "Baseline",
        "Accuracy": baseline_accuracy,
        "Format Consistency": baseline_format,
        "Overall Score": baseline_overall
    },
    {
        "Technique": "Role Assignment",
        "Accuracy": role_accuracy,
        "Format Consistency": role_format,
        "Overall Score": role_overall
    },
    {
        "Technique": "Output Format",
        "Accuracy": format_accuracy,
        "Format Consistency": format_consistency,
        "Overall Score": format_overall
    },
    {
        "Technique": "Reasoning",
        "Accuracy": reasoning_accuracy,
        "Format Consistency": reasoning_format,
        "Overall Score": reasoning_overall
    },
    {
        "Technique": "Few-Shot Examples",
        "Accuracy": fewshot_accuracy,
        "Format Consistency": fewshot_format,
        "Overall Score": fewshot_overall
    },
    {
        "Technique": "Negative Constraints",
        "Accuracy": negative_accuracy,
        "Format Consistency": negative_format,
        "Overall Score": negative_overall
    }
]

comparison_df = pd.DataFrame(comparison_data)

comparison_df = comparison_df.round(2)

comparison_df

              Technique  Accuracy  Format Consistency  Overall Score
0              Baseline       4.2                 1.0           2.60
1       Role Assignment       4.6                 2.2           3.40
2         Output Format       4.5                 2.8           3.65
3             Reasoning       4.8                 2.2           3.50
4     Few-Shot Examples       4.6                 4.6           4.60
5  Negative Constraints       4.6                 2.9           3.75

In [45]:
best_row = comparison_df.loc[
    comparison_df["Overall Score"].idxmax()
]

print("Best Technique:", best_row["Technique"])
print("Best Overall Score:", best_row["Overall Score"])

Best Technique: Few-Shot Examples
Best Overall Score: 4.6

In [46]:
improvement = (
    best_row["Overall Score"] - baseline_overall
)

print("Improvement over Baseline:", round(improvement, 2))

Improvement over Baseline: 2.0

In [47]:
prompt_versions = {
    "baseline": {
        "average_eval_score": round(baseline_overall, 2),
        "description": "Simple question-answering prompt without additional prompting techniques."
    },

    "role_assignment": {
        "average_eval_score": round(role_overall, 2),
        "description": "Added an expert role to guide the model toward accurate answers."
    },

    "output_format": {
        "average_eval_score": round(format_overall, 2),
        "description": "Added explicit output-format instructions to improve consistency."
    },

    "reasoning": {
        "average_eval_score": round(reasoning_overall, 2),
        "description": "Added an instruction to verify the answer before producing the final response."
    },

    "few_shot": {
        "average_eval_score": round(fewshot_overall, 2),
        "description": "Added examples showing the desired question-answering behavior."
    },

    "negative_constraints": {
        "average_eval_score": round(negative_overall, 2),
        "description": "Added restrictions against hallucination, assumptions, and unsupported information."
    }
}

In [48]:
import pprint

pprint.pprint(prompt_versions)

{'baseline': {'average_eval_score': np.float64(2.6),
              'description': 'Simple question-answering prompt without '
                             'additional prompting techniques.'},
 'few_shot': {'average_eval_score': np.float64(4.6),
              'description': 'Added examples showing the desired '
                             'question-answering behavior.'},
 'negative_constraints': {'average_eval_score': np.float64(3.75),
                          'description': 'Added restrictions against '
                                         'hallucination, assumptions, and '
                                         'unsupported information.'},
 'output_format': {'average_eval_score': np.float64(3.65),
                   'description': 'Added explicit output-format instructions '
                                  'to improve consistency.'},
 'reasoning': {'average_eval_score': np.float64(3.5),
               'description': 'Added an instruction to verify the answer '
                              'before producing the final response.'},
 'role_assignment': {'average_eval_score': np.float64(3.4),
                     'description': 'Added an expert role to guide the model '
                                    'toward accurate answers.'}}

In [49]:
best_technique = comparison_df.loc[
    comparison_df["Overall Score"].idxmax()
]

print("Best Technique:", best_technique["Technique"])
print("Accuracy:", best_technique["Accuracy"])
print("Format Consistency:", best_technique["Format Consistency"])
print("Overall Score:", best_technique["Overall Score"])

Best Technique: Few-Shot Examples
Accuracy: 4.6
Format Consistency: 4.6
Overall Score: 4.6

In [50]:
improvement = (
    best_technique["Overall Score"] - baseline_overall
)

print(
    "Improvement over baseline:",
    round(improvement, 2)
)

Improvement over baseline: 2.0

In [51]:
technique = best_technique["Technique"]

hypotheses = {
    "Role Assignment":
        "Role assignment may have improved performance by giving the model a clearer behavioral identity and emphasizing accurate question answering.",

    "Output Format":
        "Output-format instructions may have improved performance by reducing ambiguity about the expected response structure and making answers more consistent.",

    "Reasoning":
        "The reasoning instruction may have improved accuracy by encouraging the model to verify that its answer was supported by the provided context before responding.",

    "Few-Shot Examples":
        "Few-shot examples may have performed well because they demonstrated the expected question-answering behavior directly, reducing ambiguity about how the model should respond.",

    "Negative Constraints":
        "Negative constraints may have improved performance by explicitly preventing assumptions, hallucinations, and unrelated information."
}

hypothesis = hypotheses.get(
    technique,
    "The selected technique may have performed better because its instructions provided clearer guidance for the specific question-answering task."
)

print("Hypothesis:")
print(hypothesis)

Hypothesis:
Few-shot examples may have performed well because they demonstrated the expected question-answering behavior directly, reducing ambiguity about how the model should respond.

In [52]:
grounding_system_prompt = """
You are a grounded RAG assistant.

Your answers must be based ONLY on the information provided in the context.

Rules:
1. Use only the provided context to answer the question.
2. Do not use outside knowledge or information from your training data.
3. Do not guess or make assumptions.
4. If the answer is not directly supported by the context, refuse to answer.
5. For unsupported questions, respond exactly:
   "I cannot answer this question because the provided context does not contain enough information."
6. Keep supported answers concise.
"""

print(grounding_system_prompt)

You are a grounded RAG assistant.

Your answers must be based ONLY on the information provided in the context.

Rules:
1. Use only the provided context to answer the question.
2. Do not use outside knowledge or information from your training data.
3. Do not guess or make assumptions.
4. If the answer is not directly supported by the context, refuse to answer.
5. For unsupported questions, respond exactly:
   "I cannot answer this question because the provided context does not contain enough information."
6. Keep supported answers concise.

In [53]:
out_of_context_questions = [
    "Who is the current President of the United States?",
    "What is the capital of Australia?",
    "Who founded Microsoft?",
    "What is the population of India?",
    "Who won the FIFA World Cup in 2022?"
]

print("Number of out-of-context questions:", len(out_of_context_questions))

Number of out-of-context questions: 5

In [54]:
context = "\n".join(
    [item["context"] for item in test_data]
)

print(context)

Python was created by Guido van Rossum and was first released in 1991.
The Amazon River is approximately 6,400 kilometers long and flows through South America.
Machine learning is a subset of artificial intelligence that allows systems to learn patterns from data.
HTTP is a protocol used for transferring resources over the web.
SQL is a language commonly used to manage and query relational databases.
The human heart has four chambers: two atria and two ventricles.
Docker packages applications and their dependencies into containers.
Cloud computing provides computing resources such as storage and processing power over the internet.
Git is a distributed version control system used to track changes in source code.
FAISS is a library designed for efficient similarity search of dense vectors.

In [55]:
def grounded_answer(context, question):

    prompt = f"""
{grounding_system_prompt}

Context:
{context}

Question:
{question}

Answer:
"""

    return ask_model(prompt)

print("Grounding function created successfully!")

Grounding function created successfully!

In [56]:
grounding_results = []

for question in out_of_context_questions:

    answer = grounded_answer(
        context,
        question
    )

    grounding_results.append({
        "Question": question,
        "Model Response": answer
    })

grounding_df = pd.DataFrame(grounding_results)

grounding_df

[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=100) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

,Question,Model Response
0,Who is the current President of the United Sta...,Guido van Rossum is the current President of t...
1,What is the capital of Australia?,Australia's capital city is Canberra. The give...
2,Who founded Microsoft?,Guido van Rossum founded Microsoft. The contex...
3,What is the population of India?,Based solely on the information provided in th...
4,Who won the FIFA World Cup in 2022?,Guido van Rossum won the FIFA World Cup in 202...

In [58]:
def check_refusal(response):
    response = response.lower()

    refusal_phrases = [
        "cannot answer",
        "not enough information",
        "not supported",
        "not provided",
        "cannot be determined",
        "insufficient information"
    ]

    return any(
        phrase in response
        for phrase in refusal_phrases
    )

In [59]:
grounding_df["Refused Correctly"] = grounding_df[
    "Model Response"
].apply(check_refusal)

grounding_df

,Question,Model Response,Refused Correctly
0,Who is the current President of the United Sta...,Guido van Rossum is the current President of t...,False
1,What is the capital of Australia?,Australia's capital city is Canberra. The give...,True
2,Who founded Microsoft?,Guido van Rossum founded Microsoft. The contex...,False
3,What is the population of India?,Based solely on the information provided in th...,True
4,Who won the FIFA World Cup in 2022?,Guido van Rossum won the FIFA World Cup in 202...,False

In [60]:
grounding_accuracy = (
    grounding_df["Refused Correctly"].mean() * 100
)

print(
    f"Grounding refusal accuracy: {grounding_accuracy:.1f}%"
)

Grounding refusal accuracy: 40.0%

In [61]:
print("=" * 70)
print("DAY 19 — PROMPT ENGINEERING FOR RELIABLE LLM OUTPUTS")
print("=" * 70)

print("\n1. TASK")
print("Question Answering using provided context")

print("\n2. PROMPT TECHNIQUE COMPARISON")
print(comparison_df.to_string(index=False))

print("\n3. BEST TECHNIQUE")
print("Technique:", best_technique["Technique"])
print("Overall Score:", best_technique["Overall Score"])
print("Improvement over Baseline:", round(improvement, 2))

print("\n4. HYPOTHESIS")
print(hypothesis)

print("\n5. GROUNDING SYSTEM PROMPT")
print(grounding_system_prompt)

print("\n6. OUT-OF-CONTEXT TEST RESULTS")
print(grounding_df.to_string(index=False))

print(
    f"\n7. GROUNDING REFUSAL ACCURACY: "
    f"{grounding_accuracy:.1f}%"
)

print("\n" + "=" * 70)
print("DAY 19 EXPERIMENT COMPLETED")
print("=" * 70)

======================================================================
DAY 19 — PROMPT ENGINEERING FOR RELIABLE LLM OUTPUTS
======================================================================

1. TASK
Question Answering using provided context

2. PROMPT TECHNIQUE COMPARISON
           Technique  Accuracy  Format Consistency  Overall Score
            Baseline       4.2                 1.0           2.60
     Role Assignment       4.6                 2.2           3.40
       Output Format       4.5                 2.8           3.65
           Reasoning       4.8                 2.2           3.50
   Few-Shot Examples       4.6                 4.6           4.60
Negative Constraints       4.6                 2.9           3.75

3. BEST TECHNIQUE
Technique: Few-Shot Examples
Overall Score: 4.6
Improvement over Baseline: 2.0

4. HYPOTHESIS
Few-shot examples may have performed well because they demonstrated the expected question-answering behavior directly, reducing ambiguity about how the model should respond.

5. GROUNDING SYSTEM PROMPT

You are a grounded RAG assistant.

Your answers must be based ONLY on the information provided in the context.

Rules:
1. Use only the provided context to answer the question.
2. Do not use outside knowledge or information from your training data.
3. Do not guess or make assumptions.
4. If the answer is not directly supported by the context, refuse to answer.
5. For unsupported questions, respond exactly:
   "I cannot answer this question because the provided context does not contain enough information."
6. Keep supported answers concise.


6. OUT-OF-CONTEXT TEST RESULTS
                                          Question                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Model Response  Refused Correctly
Who is the current President of the United States?                                                   Guido van Rossum is the current President of the United States. The context states that Python was created by Guido van Rossum and was first released in 1991. It also mentions that the Amazon River is approximately 6,400 kilometers long and flows through South America. Machine learning is a subset of artificial intelligence that allows systems to learn patterns from data. HTTP is a protocol used for transferring resources over the web. SQL is a language commonly used to manage and query              False
                 What is the capital of Australia?                                                                                                                                                                                                                                      Australia's capital city is Canberra. The given context does not provide any information about the capital of Australia. Therefore, I cannot answer this question based solely on the provided context. \n\nMy response: I cannot answer this question because the provided context does not contain enough information.               True
                            Who founded Microsoft?                                                                                 Guido van Rossum founded Microsoft. The context states that Python was created by Guido van Rossum and was first released in 1991. It also mentions that Microsoft was founded in 1980 by Bill Gates and Paul Allen. Therefore, Microsoft was founded by Guido van Rossum. This information is directly supported by the given context. \n\nMy response: Guido van Rossum founded Microsoft. Based solely on the information provided in the context, I can confidently state              False
                  What is the population of India? Based solely on the information provided in the context, there is no mention of the population of India. The context focuses on technology-related topics like Python, machine learning, and cloud computing, but it does not include any information about India's population. Therefore, I cannot provide an answer to this question using the given context. \n\nResponse: I cannot answer this question because the provided context does not contain enough information. Please provide additional context or information related to India's population.               True
               Who won the FIFA World Cup in 2022?                                                                                                              Guido van Rossum won the FIFA World Cup in 2022. The context states that Python was created by Guido van Rossum and was first released in 1991. It also mentions that the Amazon River is approximately 6,400 kilometers long and flows through South America. Lastly, it lists several other technologies mentioned like Docker, Git, and FAISS. However, there is no mention of any specific person winning the FIFA World Cup. Therefore, the              False

7. GROUNDING REFUSAL ACCURACY: 40.0%

======================================================================
DAY 19 EXPERIMENT COMPLETED
======================================================================