<a href="https://colab.research.google.com/github/Chikka-Pradhayani/ABTalks-60-Days-AI-Challenge/blob/main/Day_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q langchain langchain-text-splitters sentence-transformers

In [2]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
import numpy as np
import pandas as pd

In [3]:
document_text = """
Artificial intelligence is one of the most important areas of modern computer science.
It combines computer systems, algorithms, data, and mathematical techniques to create
systems capable of performing tasks that normally require human intelligence.

Machine learning is a major branch of artificial intelligence. Instead of explicitly
programming every rule, machine learning systems learn patterns from data. These systems
can be trained using supervised learning, unsupervised learning, and reinforcement
learning techniques.

Deep learning is a specialized area of machine learning based on artificial neural
networks with multiple layers. Deep learning has achieved significant results in image
recognition, natural language processing, speech recognition, recommendation systems,
and many other applications.

Natural language processing focuses on enabling computers to understand and process
human language. Modern NLP systems use large datasets and neural network architectures
to analyze text, generate responses, summarize documents, translate languages, and
answer questions.

Large language models have changed the way NLP applications are developed. These models
are trained on large collections of text and learn statistical relationships between
words, phrases, and concepts. They can subsequently be adapted for tasks such as
question answering, summarization, classification, and information retrieval.

Information retrieval is the process of finding relevant information from a large
collection of documents. Search engines, recommendation systems, and question-answering
systems commonly use information retrieval techniques.

A major challenge in retrieval augmented generation systems is handling documents that
are too large to fit into the context window of a language model. Chunking addresses
this problem by dividing a document into smaller pieces that can be independently
processed and retrieved.

Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Overlap between neighboring chunks can reduce the problem of losing information at
chunk boundaries. When a sentence or concept crosses a boundary, overlapping regions
allow the same information to appear in more than one chunk.

Fixed-size chunking is one of the simplest chunking strategies. It divides text into
pieces according to a fixed number of characters or tokens. Although simple, fixed-size
chunking may split sentences and paragraphs in unnatural locations.

Recursive character splitting provides a more context-aware approach. It attempts to
split text using separators such as paragraphs, newlines, sentences, and spaces before
falling back to smaller units.

The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

""" * 20

print("Document loaded successfully!")
print("Number of characters:", len(document_text))

Document loaded successfully!
Number of characters: 75680

In [4]:
print(document_text[:1000])

Artificial intelligence is one of the most important areas of modern computer science.
It combines computer systems, algorithms, data, and mathematical techniques to create
systems capable of performing tasks that normally require human intelligence.

Machine learning is a major branch of artificial intelligence. Instead of explicitly
programming every rule, machine learning systems learn patterns from data. These systems
can be trained using supervised learning, unsupervised learning, and reinforcement
learning techniques.

Deep learning is a specialized area of machine learning based on artificial neural
networks with multiple layers. Deep learning has achieved significant results in image
recognition, natural language processing, speech recognition, recommendation systems,
and many other applications.

Natural language processing focuses on enabling computers to understand and process
human language. Modern NLP systems use large datasets and neural network architectures
to analyze

In [5]:
char_count = len(document_text)
word_count = len(document_text.split())
line_count = len(document_text.splitlines())
print("Document Statistics")
print("-" * 30)
print("Characters :", char_count)
print("Words      :", word_count)
print("Lines      :", line_count)

Document Statistics
------------------------------
Characters : 75680
Words      : 10440
Lines      : 1340

In [6]:
print(document_text[:2000])

Artificial intelligence is one of the most important areas of modern computer science.
It combines computer systems, algorithms, data, and mathematical techniques to create
systems capable of performing tasks that normally require human intelligence.

Machine learning is a major branch of artificial intelligence. Instead of explicitly
programming every rule, machine learning systems learn patterns from data. These systems
can be trained using supervised learning, unsupervised learning, and reinforcement
learning techniques.

Deep learning is a specialized area of machine learning based on artificial neural
networks with multiple layers. Deep learning has achieved significant results in image
recognition, natural language processing, speech recognition, recommendation systems,
and many other applications.

Natural language processing focuses on enabling computers to understand and process
human language. Modern NLP systems use large datasets and neural network architectures
to analyze text, generate responses, summarize documents, translate languages, and
answer questions.

Large language models have changed the way NLP applications are developed. These models
are trained on large collections of text and learn statistical relationships between
words, phrases, and concepts. They can subsequently be adapted for tasks such as
question answering, summarization, classification, and information retrieval.

Information retrieval is the process of finding relevant information from a large
collection of documents. Search engines, recommendation systems, and question-answering
systems commonly use information retrieval techniques.

A major challenge in retrieval augmented generation systems is handling documents that
are too large to fit into the context window of a language model. Chunking addresses
this problem by dividing a document into smaller pieces that can be independently
processed and retrieved.

Chunking strategies have a significant effect on retrieval quality. If

In [8]:
if char_count >= 10000:
    print("Document is sufficiently long for the chunking experiment.")
else:
    print("Document may be too short. Use a longer document.")

Document is sufficiently long for the chunking experiment.

In [9]:
def fixed_size_chunking(text, chunk_size):
    """
    Split text into fixed-size chunks without overlap.
    """
    chunks = []
    for start in range(0, len(text), chunk_size):
        chunk = text[start:start + chunk_size]
        chunks.append(chunk)
    return chunks

In [10]:
chunks_100 = fixed_size_chunking(document_text, 100)
print("Number of chunks:", len(chunks_100))
print("\nFirst chunk:")
print(chunks_100[0])
print("\nSecond chunk:")
print(chunks_100[1])

Number of chunks: 757

First chunk:

Artificial intelligence is one of the most important areas of modern computer science.
It combines

Second chunk:
computer systems, algorithms, data, and mathematical techniques to create
systems capable of perform

In [11]:
def fixed_size_chunking_with_overlap(text, chunk_size, chunk_overlap):
    """
    Split text into fixed-size chunks with configurable overlap.
    """

    if chunk_overlap >= chunk_size:
        raise ValueError("chunk_overlap must be smaller than chunk_size")

    chunks = []
    start = 0

    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]

        if chunk:
            chunks.append(chunk)

        start += chunk_size - chunk_overlap

    return chunks

In [13]:
chunks = fixed_size_chunking_with_overlap(
    document_text,
    chunk_size=300,
    chunk_overlap=50
)

In [14]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)
recursive_chunks = text_splitter.split_text(document_text)
print("Number of chunks:", len(recursive_chunks))

Number of chunks: 320

In [15]:
print("----- Chunk 1 -----")
print(recursive_chunks[0])
print("\n----- Chunk 2 -----")
print(recursive_chunks[1])

----- Chunk 1 -----
Artificial intelligence is one of the most important areas of modern computer science.
It combines computer systems, algorithms, data, and mathematical techniques to create
systems capable of performing tasks that normally require human intelligence.

----- Chunk 2 -----
Machine learning is a major branch of artificial intelligence. Instead of explicitly
programming every rule, machine learning systems learn patterns from data. These systems
can be trained using supervised learning, unsupervised learning, and reinforcement
learning techniques.

In [16]:
for i, chunk in enumerate(recursive_chunks[:5]):
    print(f"Chunk {i+1}: {len(chunk)} characters")

Chunk 1: 250 characters
Chunk 2: 277 characters
Chunk 3: 284 characters
Chunk 4: 271 characters
Chunk 5: 253 characters

In [17]:
chunk_sizes = [100, 300, 500, 1000]
overlaps = [0, 50, 100]
all_chunks = {}
for chunk_size in chunk_sizes:
    for overlap in overlaps:
        if overlap >= chunk_size:
            continue
        splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=overlap
        )
        chunks_config = splitter.split_text(document_text)
        config_name = f"size={chunk_size}, overlap={overlap}"
        all_chunks[config_name] = chunks_config
print("Total configurations:", len(all_chunks))

Total configurations: 11

In [18]:
for config, chunks_list in all_chunks.items():
    print(f"{config} → {len(chunks_list)} chunks")

size=100, overlap=0 → 1020 chunks
size=100, overlap=50 → 1020 chunks
size=300, overlap=0 → 320 chunks
size=300, overlap=50 → 320 chunks
size=300, overlap=100 → 320 chunks
size=500, overlap=0 → 221 chunks
size=500, overlap=50 → 221 chunks
size=500, overlap=100 → 221 chunks
size=1000, overlap=0 → 87 chunks
size=1000, overlap=50 → 87 chunks
size=1000, overlap=100 → 87 chunks

In [19]:
configuration_data = []
for config, chunks_list in all_chunks.items():
    size = int(config.split(",")[0].split("=")[1])
    overlap = int(config.split(",")[1].split("=")[1])
    configuration_data.append({
        "Chunk Size": size,
        "Overlap": overlap,
        "Number of Chunks": len(chunks_list)
    })
config_df = pd.DataFrame(configuration_data)
config_df

    Chunk Size  Overlap  Number of Chunks
0          100        0              1020
1          100       50              1020
2          300        0               320
3          300       50               320
4          300      100               320
5          500        0               221
6          500       50               221
7          500      100               221
8         1000        0                87
9         1000       50                87
10        1000      100                87

In [20]:
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
print("Embedding model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embedding model loaded successfully!

In [21]:
query = "How does chunk size and overlap affect retrieval quality in document processing?"
print("Query:", query)

Query: How does chunk size and overlap affect retrieval quality in document processing?

In [22]:
query_embedding = embedding_model.encode(
    query,
    convert_to_numpy=True
)
print("Query embedding shape:", query_embedding.shape)

Query embedding shape: (384,)

In [25]:
from numpy.linalg import norm
def cosine_similarity(vector_a, vector_b):
    return np.dot(vector_a, vector_b) / (
        norm(vector_a) * norm(vector_b)
    )

In [26]:
test_chunks = all_chunks["size=300, overlap=50"]
test_embeddings = embedding_model.encode(
    test_chunks,
    convert_to_numpy=True
)
scores = []
for i, chunk_embedding in enumerate(test_embeddings):
    score = cosine_similarity(
        query_embedding,
        chunk_embedding
    )
    scores.append((i, score))

In [27]:
scores.sort(key=lambda x: x[1], reverse=True)
top_3 = scores[:3]
for rank, (index, score) in enumerate(top_3, start=1):
    print(f"\n{'='*60}")
    print(f"Rank {rank}")
    print(f"Similarity Score: {score:.4f}")
    print(f"Chunk Index: {index}")
    print(f"{'='*60}")
    print(test_chunks[index])

============================================================
Rank 1
Similarity Score: 0.7940
Chunk Index: 8
============================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

============================================================
Rank 2
Similarity Score: 0.7940
Chunk Index: 24
============================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

============================================================
Rank 3
Similarity Score: 0.7940
Chunk Index: 40
============================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

In [28]:
def retrieve_top_chunks(chunks, query_embedding, top_k=3):
    """
    Retrieve the top-k most similar chunks for a query.
    """
    chunk_embeddings = embedding_model.encode(
        chunks,
        convert_to_numpy=True
    )
    scores = []
    for i, chunk_embedding in enumerate(chunk_embeddings):
        score = cosine_similarity(
            query_embedding,
            chunk_embedding
        )
        scores.append((i, score))
    scores.sort(key=lambda x: x[1], reverse=True)
    return scores[:top_k]

In [29]:
retrieval_results = {}
for config, chunks_list in all_chunks.items():
    top_chunks = retrieve_top_chunks(
        chunks_list,
        query_embedding,
        top_k=3
    )
    retrieval_results[config] = top_chunks
print("Retrieval completed for all configurations!")

Retrieval completed for all configurations!

In [30]:
for config, results in retrieval_results.items():
    print("\n" + "=" * 80)
    print(config)
    print("=" * 80)
    chunks_list = all_chunks[config]
    for rank, (index, score) in enumerate(results, start=1):
        print(f"\nRank {rank} | Score: {score:.4f}")
        print("-" * 60)
        print(chunks_list[index])

================================================================================
size=100, overlap=0
================================================================================

Rank 1 | Score: 0.8101
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical

Rank 2 | Score: 0.8101
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical

Rank 3 | Score: 0.8101
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical

================================================================================
size=100, overlap=50
================================================================================

Rank 1 | Score: 0.8101
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical

Rank 2 | Score: 0.8101
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical

Rank 3 | Score: 0.8101
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical

================================================================================
size=300, overlap=0
================================================================================

Rank 1 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 2 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 3 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

================================================================================
size=300, overlap=50
================================================================================

Rank 1 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 2 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 3 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

================================================================================
size=300, overlap=100
================================================================================

Rank 1 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 2 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 3 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

================================================================================
size=500, overlap=0
================================================================================

Rank 1 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 2 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 3 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

================================================================================
size=500, overlap=50
================================================================================

Rank 1 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 2 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 3 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

================================================================================
size=500, overlap=100
================================================================================

Rank 1 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 2 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

Rank 3 | Score: 0.7940
------------------------------------------------------------
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

================================================================================
size=1000, overlap=0
================================================================================

Rank 1 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

Rank 2 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

Rank 3 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

================================================================================
size=1000, overlap=50
================================================================================

Rank 1 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

Rank 2 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

Rank 3 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

================================================================================
size=1000, overlap=100
================================================================================

Rank 1 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

Rank 2 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

Rank 3 | Score: 0.7937
------------------------------------------------------------
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

In [31]:
comparison_data = []
for config, results in retrieval_results.items():
    size = int(config.split(",")[0].split("=")[1])
    overlap = int(config.split(",")[1].split("=")[1])
    scores = [score for _, score in results]
    comparison_data.append({
        "Chunk Size": size,
        "Overlap": overlap,
        "Top 1 Score": scores[0],
        "Top 2 Score": scores[1],
        "Top 3 Score": scores[2],
        "Average Score": np.mean(scores)
    })
comparison_df = pd.DataFrame(comparison_data)
comparison_df = comparison_df.sort_values(
    "Average Score",
    ascending=False
).reset_index(drop=True)
comparison_df

    Chunk Size  Overlap  Top 1 Score  Top 2 Score  Top 3 Score  Average Score
0          100        0     0.810057     0.810057     0.810057       0.810057
1          100       50     0.810057     0.810057     0.810057       0.810057
2          300        0     0.793958     0.793958     0.793958       0.793958
3          300       50     0.793958     0.793958     0.793958       0.793958
4          300      100     0.793958     0.793958     0.793958       0.793958
5          500        0     0.793958     0.793958     0.793958       0.793958
6          500       50     0.793958     0.793958     0.793958       0.793958
7          500      100     0.793958     0.793958     0.793958       0.793958
8         1000        0     0.793682     0.793682     0.793682       0.793682
9         1000       50     0.793682     0.793682     0.793682       0.793682
10        1000      100     0.793682     0.793682     0.793682       0.793682

In [32]:
for config, results in retrieval_results.items():
    best_index, best_score = results[0]
    best_chunk = all_chunks[config][best_index]
    print("\n" + "=" * 90)
    print(f"Configuration: {config}")
    print(f"Similarity Score: {best_score:.4f}")
    print("=" * 90)
    print(best_chunk)

==========================================================================================
Configuration: size=100, overlap=0
Similarity Score: 0.8101
==========================================================================================
The choice of chunk size depends on the document and the retrieval task. Technical

==========================================================================================
Configuration: size=100, overlap=50
Similarity Score: 0.8101
==========================================================================================
The choice of chunk size depends on the document and the retrieval task. Technical

==========================================================================================
Configuration: size=300, overlap=0
Similarity Score: 0.7940
==========================================================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

==========================================================================================
Configuration: size=300, overlap=50
Similarity Score: 0.7940
==========================================================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

==========================================================================================
Configuration: size=300, overlap=100
Similarity Score: 0.7940
==========================================================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

==========================================================================================
Configuration: size=500, overlap=0
Similarity Score: 0.7940
==========================================================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

==========================================================================================
Configuration: size=500, overlap=50
Similarity Score: 0.7940
==========================================================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

==========================================================================================
Configuration: size=500, overlap=100
Similarity Score: 0.7940
==========================================================================================
Chunking strategies have a significant effect on retrieval quality. If chunks are too
small, important context may be lost because related information is separated into
different chunks. If chunks are too large, retrieval may return unnecessary information
and consume more context window space.

==========================================================================================
Configuration: size=1000, overlap=0
Similarity Score: 0.7937
==========================================================================================
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

==========================================================================================
Configuration: size=1000, overlap=50
Similarity Score: 0.7937
==========================================================================================
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

==========================================================================================
Configuration: size=1000, overlap=100
Similarity Score: 0.7937
==========================================================================================
The choice of chunk size depends on the document and the retrieval task. Technical
documents may require larger chunks because concepts are often explained across several
sentences. Short articles may work better with smaller chunks.

Retrieval experiments can be used to compare different chunking configurations.
A fixed query can be executed against every configuration and the retrieved results
can then be evaluated for relevance and contextual completeness.

A useful chunking experiment should measure not only whether the correct information
is retrieved but also whether the retrieved chunk contains enough surrounding context
to understand that information.

Therefore, chunk size and overlap should be treated as important parameters in a
retrieval pipeline. Testing multiple configurations on the same document provides
evidence for selecting an appropriate strategy.

In [33]:
context_comparison = []
for config, results in retrieval_results.items():
    best_index, best_score = results[0]
    best_chunk = all_chunks[config][best_index]
    context_comparison.append({
        "Configuration": config,
        "Similarity Score": round(best_score, 4),
        "Retrieved Characters": len(best_chunk),
        "Retrieved Text": best_chunk
    })
context_df = pd.DataFrame(context_comparison)
context_df

,Configuration,Similarity Score,Retrieved Characters,Retrieved Text
0,"size=100, overlap=0",0.8101,82,The choice of chunk size depends on the docume...
1,"size=100, overlap=50",0.8101,82,The choice of chunk size depends on the docume...
2,"size=300, overlap=0",0.7940,295,Chunking strategies have a significant effect ...
3,"size=300, overlap=50",0.7940,295,Chunking strategies have a significant effect ...
4,"size=300, overlap=100",0.7940,295,Chunking strategies have a significant effect ...
5,"size=500, overlap=0",0.7940,295,Chunking strategies have a significant effect ...
6,"size=500, overlap=50",0.7940,295,Chunking strategies have a significant effect ...
7,"size=500, overlap=100",0.7940,295,Chunking strategies have a significant effect ...
8,"size=1000, overlap=0",0.7937,879,The choice of chunk size depends on the docume...
9,"size=1000, overlap=50",0.7937,879,The choice of chunk size depends on the docume...
10,"size=1000, overlap=100",0.7937,879,The choice of chunk size depends on the docume...

In [34]:
best_row = context_df.loc[
    context_df["Similarity Score"].idxmax()
]
print("Best configuration based on similarity score:")
print(best_row["Configuration"])
print("\nSimilarity Score:")
print(best_row["Similarity Score"])
print("\nRetrieved Context:")
print(best_row["Retrieved Text"])

Best configuration based on similarity score:
size=100, overlap=0

Similarity Score:
0.8101

Retrieved Context:
The choice of chunk size depends on the document and the retrieval task. Technical

In [35]:
best_configuration = context_df.loc[
    context_df["Similarity Score"].idxmax(),
    "Configuration"
]
print("Most contextually complete configuration:")
print(best_configuration)
print("\nReason:")
print(
    "This configuration provided a strong semantic match to the query "
    "while preserving sufficient surrounding context in the retrieved chunk."
)

Most contextually complete configuration:
size=100, overlap=0

Reason:
This configuration provided a strong semantic match to the query while preserving sufficient surrounding context in the retrieved chunk.

In [36]:
def find_boundary_failures(text, chunk_size, chunk_overlap=0, max_examples=3):
    """
    Find cases where a chunk boundary occurs inside a sentence.
    """
    failures = []
    step = chunk_size - chunk_overlap
    start = 0
    while start < len(text) and len(failures) < max_examples:
        end = min(start + chunk_size, len(text))
        if end >= len(text):
            break
        before = text[end - 1]
        after = text[end]
        punctuation = ".!?\n"
        if before not in punctuation:
            sentence_start = text.rfind(".", 0, end)
            sentence_start = max(
                sentence_start,
                text.rfind("!", 0, end),
                text.rfind("?", 0, end)
            )
            sentence_start += 1
            sentence_end_candidates = [
                text.find(".", end),
                text.find("!", end),
                text.find("?", end)
            ]
            valid_candidates = [
                position
                for position in sentence_end_candidates
                if position != -1
            ]
            if valid_candidates:
                sentence_end = min(valid_candidates) + 1
                failures.append({
                    "boundary_position": end,
                    "sentence_start": sentence_start,
                    "sentence_end": sentence_end,
                    "sentence": text[sentence_start:sentence_end]
                })
        start += step
    return failures

In [37]:
failures = find_boundary_failures(
    document_text,
    chunk_size=300,
    chunk_overlap=0,
    max_examples=3
)
print("Number of boundary failures found:", len(failures))

Number of boundary failures found: 3

In [38]:
for i, failure in enumerate(failures, start=1):
    print("\n" + "=" * 80)
    print(f"Boundary Failure Example {i}")
    print("=" * 80)
    print("Exact boundary position:",
          failure["boundary_position"])
    print("\nSentence:")
    print(failure["sentence"])

================================================================================
Boundary Failure Example 1
================================================================================
Exact boundary position: 300

Sentence:


Machine learning is a major branch of artificial intelligence.

================================================================================
Boundary Failure Example 2
================================================================================
Exact boundary position: 600

Sentence:


Deep learning is a specialized area of machine learning based on artificial neural
networks with multiple layers.

================================================================================
Boundary Failure Example 3
================================================================================
Exact boundary position: 900

Sentence:


Natural language processing focuses on enabling computers to understand and process
human language.

In [39]:
for i, failure in enumerate(failures, start=1):
    position = failure["boundary_position"]
    print("\n" + "=" * 80)
    print(f"Example {i}")
    print(f"Boundary at character position: {position}")
    print("=" * 80)
    print("\n--- Text BEFORE boundary ---")
    print(document_text[position - 100:position])
    print("\n--- Text AFTER boundary ---")
    print(document_text[position:position + 100])

================================================================================
Example 1
Boundary at character position: 300
================================================================================

--- Text BEFORE boundary ---
ing tasks that normally require human intelligence.

Machine learning is a major branch of artificia

--- Text AFTER boundary ---
l intelligence. Instead of explicitly
programming every rule, machine learning systems learn pattern

================================================================================
Example 2
Boundary at character position: 600
================================================================================

--- Text BEFORE boundary ---
forcement
learning techniques.

Deep learning is a specialized area of machine learning based on art

--- Text AFTER boundary ---
ificial neural
networks with multiple layers. Deep learning has achieved significant results in imag

================================================================================
Example 3
Boundary at character position: 900
================================================================================

--- Text BEFORE boundary ---
er applications.

Natural language processing focuses on enabling computers to understand and proces

--- Text AFTER boundary ---
s
human language. Modern NLP systems use large datasets and neural network architectures
to analyze

In [40]:
final_results = comparison_df.copy()
final_results["Rank"] = (
    final_results["Average Score"]
    .rank(method="min", ascending=False)
    .astype(int)
)
final_results = final_results.sort_values("Rank")
final_results

,Chunk Size,Overlap,Top 1 Score,Top 2 Score,Top 3 Score,Average Score,Rank
0,100,0,0.810057,0.810057,0.810057,0.810057,1
1,100,50,0.810057,0.810057,0.810057,0.810057,1
2,300,0,0.793958,0.793958,0.793958,0.793958,3
3,300,50,0.793958,0.793958,0.793958,0.793958,3
4,300,100,0.793958,0.793958,0.793958,0.793958,3
5,500,0,0.793958,0.793958,0.793958,0.793958,3
6,500,50,0.793958,0.793958,0.793958,0.793958,3
7,500,100,0.793958,0.793958,0.793958,0.793958,3
8,1000,0,0.793682,0.793682,0.793682,0.793682,9
9,1000,50,0.793682,0.793682,0.793682,0.793682,9
10,1000,100,0.793682,0.793682,0.793682,0.793682,9

In [41]:
best_result = final_results.iloc[0]
best_chunk_size = int(best_result["Chunk Size"])
best_overlap = int(best_result["Overlap"])
print("BEST CONFIGURATION")
print("=" * 40)
print("Chunk Size :", best_chunk_size)
print("Overlap    :", best_overlap)
print("Average Similarity :", round(
    best_result["Average Score"], 4
))

BEST CONFIGURATION
========================================
Chunk Size : 100
Overlap    : 0
Average Similarity : 0.8101

In [42]:
best_config_name = (
    f"size={best_chunk_size}, overlap={best_overlap}"
)
best_chunks = all_chunks[best_config_name]
best_retrieval = retrieve_top_chunks(
    best_chunks,
    query_embedding,
    top_k=3
)
print("Best Configuration:", best_config_name)
for rank, (index, score) in enumerate(best_retrieval, start=1):
    print("\n" + "=" * 80)
    print(f"Rank {rank}")
    print(f"Similarity Score: {score:.4f}")
    print("=" * 80)
    print(best_chunks[index])

Best Configuration: size=100, overlap=0

================================================================================
Rank 1
Similarity Score: 0.8101
================================================================================
The choice of chunk size depends on the document and the retrieval task. Technical

================================================================================
Rank 2
Similarity Score: 0.8101
================================================================================
The choice of chunk size depends on the document and the retrieval task. Technical

================================================================================
Rank 3
Similarity Score: 0.8101
================================================================================
The choice of chunk size depends on the document and the retrieval task. Technical

In [43]:
print("FINAL CHUNKING STRATEGY RECOMMENDATION")
print("=" * 60)
print(
    f"Recommended chunk size: {best_chunk_size} characters")
print(
    f"Recommended chunk overlap: {best_overlap} characters")
print(
    f"Average retrieval similarity: "
    f"{best_result['Average Score']:.4f}")
print("\nReasoning:")
print(
    "This configuration provided the strongest retrieval performance "
    "among the tested configurations while maintaining sufficient "
    "context around retrieved information. The selected overlap also "
    "helps reduce information loss at chunk boundaries."
)

FINAL CHUNKING STRATEGY RECOMMENDATION
============================================================
Recommended chunk size: 100 characters
Recommended chunk overlap: 0 characters
Average retrieval similarity: 0.8101

Reasoning:
This configuration provided the strongest retrieval performance among the tested configurations while maintaining sufficient context around retrieved information. The selected overlap also helps reduce information loss at chunk boundaries.